// @ts-nocheck
// Generated by Claude Design (Opus 4.7) v0.7 — Friends + DM page.

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { useFriends, usePendingFriends } from '@/hooks';

const { useState: useStateD } = React;
const { Button: BtnD, Avatar: AvD, Badge: BdgD } = UI;
const { ServerRail: RailD, Row: RowD, SectionLabel: SLD, IdentityCard: IdD, ChatMessage: CMD } = SHARED;

const DM_THREAD = [
  { who: '咲夜', t: '20:48', msg: '今晚要打 Lunatic 吗' },
  { who: 'me',   t: '20:49', msg: '打的，4B 路线还是老样子' },
  { who: '咲夜', t: '20:49', msg: '稳，我先去开房间', samegroup: true },
  { kind: 'embed', t: '20:50' },
  { who: 'me',   t: '20:51', msg: '收到，我两分钟后到' },
  { who: '咲夜', t: '20:53', msg: '魔理沙 也来 总共 3 个 等多 1 个就开打' },
  { who: 'me',   t: '20:54', msg: '@yuyuko 在不？要不要来打 Lunatic 4B', mention: 'yuyuko' },
  { who: '咲夜', t: '20:55', msg: '我去拉幽幽子 你先调下手感', samegroup: false },
];

function MiniRoomShare({ onJoin }: any) {
  return (
    <div style={{
      maxWidth: 380, padding: 10, borderRadius: 'var(--r-md)',
      background: 'var(--bg-1)', border: '1px solid var(--border)',
      borderLeft: '2px solid var(--accent)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span className="t-tag" style={{ color: 'var(--accent)' }}>OFFICIAL · TH08 · ROOM</span>
        <span className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>#4912</span>
      </div>
      <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>永夜抄 Lunatic · 4B 路线练习</div>
      <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2 }}><span style={{ color: 'var(--fg-1)' }}>主</span> 咲夜 · 28ms · <span className="num" style={{ color: 'var(--fg-1)', fontWeight: 600 }}>3/6</span></div>
      <div style={{ display: 'flex', gap: 6, marginTop: 8 }}>
        <BtnD variant="primary" size="sm" style={{ flex: 1 }} onClick={onJoin}><span className="cjk">立即加入</span></BtnD>
        <BtnD variant="ghost" size="sm"><Lu name="copy" size={11} /></BtnD>
      </div>
    </div>
  );
}

function FriendRow({ f, kind = 'all', onMessage }: any) {
  const action = kind === 'pending' ? (
    f.dir === 'in' ? (
      <div style={{ display: 'flex', gap: 6 }}>
        <button title="接受" className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-0)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="check" size={13} /></button>
        <button title="忽略" className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-2)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="x" size={13} /></button>
      </div>
    ) : <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>等待回应</span>
  ) : (
    <div style={{ display: 'flex', gap: 6 }}>
      <button title="发消息" onClick={onMessage} className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="message-square" size={13} /></button>
      <button title="更多" className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="more-horizontal" size={13} /></button>
    </div>
  );
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 16px', borderTop: '1px solid var(--border)' }}>
      <AvD size={36} name={f.name} status={f.status} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
          <span className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{f.name}</span>
          <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)' }}>@{f.handle}</span>
          {f.mutual ? <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>· {f.mutual} 个共同好友</span> : null}
        </div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2, display: 'flex', alignItems: 'center', gap: 6 }}>
          {f.game ? <span className="num" style={{ fontSize: 10, padding: '1px 5px', border: '1px solid var(--border)', borderRadius: 3, color: 'var(--fg-1)' }}>{f.game}</span> : null}
          {f.subtle}
        </div>
      </div>
      {action}
    </div>
  );
}

function FriendsTab({ tab, onMessage, onAdd }: any) {
  const { data: friends = [] } = useFriends();
  const { data: pending = [] } = usePendingFriends();
  const filtered = tab === 'online' ? friends.filter(f => f.status !== 'offline')
    : tab === 'pending' ? []
    : tab === 'blocked' ? []
    : friends;
  return (
    <div style={{ flex: 1, overflowY: 'auto' }}>
      <div style={{ paddingInline: 16, paddingTop: 14, paddingBottom: 8, position: 'sticky', top: 0, background: 'var(--bg-0)' }}>
        <div style={{ height: 32, background: 'var(--bg-1)', borderRadius: 6, border: '1px solid var(--border)', paddingInline: 10, display: 'flex', alignItems: 'center', gap: 8 }}>
          <Lu name="search" size={13} color="var(--fg-2)" />
          <input className="cjk t-body" placeholder="搜索好友" style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: 'var(--fg-0)' }} />
        </div>
        <div className="cjk t-tag" style={{ color: 'var(--fg-2)', marginTop: 14 }}>
          {tab === 'online' ? `在线 — ${filtered.length}` : tab === 'all' ? `所有好友 — ${friends.length}` : tab === 'pending' ? `待处理 — ${pending.length}` : '已屏蔽 — 0'}
        </div>
      </div>
      {tab === 'pending' ? pending.map(p => <FriendRow key={p.handle} f={p} kind="pending" />) : filtered.map(f => <FriendRow key={f.handle} f={f} onMessage={() => onMessage(f.handle)} />)}
      {tab === 'blocked' && (
        <div style={{ padding: 40, textAlign: 'center' }}>
          <div className="cjk t-body" style={{ color: 'var(--fg-2)' }}>没有屏蔽任何人</div>
        </div>
      )}
    </div>
  );
}

function FriendsHome({ active = 'online', onMessage, onAddFriend }: any) {
  const [tab, setTab] = useStateD(active);
  return (
    <main style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', background: 'var(--bg-0)' }}>
      <div style={{ height: 48, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 14, borderBottom: '1px solid var(--border)' }}>
        <Lu name="users" size={14} color="var(--fg-2)" />
        <span className="cjk h-display-sm">好友</span>
        <span style={{ width: 1, height: 16, background: 'var(--border)' }} />
        {[
          { id: 'online', label: '在线' },
          { id: 'all', label: '全部' },
          { id: 'pending', label: '待处理', count: 1 },
          { id: 'blocked', label: '已屏蔽' },
        ].map(t => (
          <button key={t.id} onClick={() => setTab(t.id)} className="btn-pressable" style={{
            height: 26, paddingInline: 10, borderRadius: 6, border: 'none',
            background: tab === t.id ? 'var(--bg-2)' : 'transparent',
            color: tab === t.id ? 'var(--fg-0)' : 'var(--fg-2)',
            fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-sans)',
            display: 'inline-flex', alignItems: 'center', gap: 6,
          }}><span className="cjk">{t.label}</span>{t.count ? <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--accent)' }} /> : null}</button>
        ))}
        <span style={{ flex: 1 }} />
        <BtnD variant="primary" size="sm" onClick={onAddFriend}><Lu name="user-plus" size={12} /><span className="cjk" style={{ marginLeft: 6 }}>添加好友</span></BtnD>
      </div>
      <FriendsTab tab={tab} onMessage={onMessage} />
    </main>
  );
}

function DMThread({ peer, onPin, onAddUser }: any) {
  return (
    <main style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', background: 'var(--bg-0)' }}>
      <div style={{ height: 48, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 12, borderBottom: '1px solid var(--border)' }}>
        <AvD size={26} name={peer.name} status={peer.status} />
        <div>
          <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{peer.name} <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)', fontWeight: 500 }}>@{peer.handle}</span></div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{peer.subtle}</div>
        </div>
        <span style={{ flex: 1 }} />
        <button title="置顶" onClick={onPin} className="btn-pressable" style={{ width: 28, height: 28, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="pin" size={13} /></button>
        <button title="邀请群聊" onClick={onAddUser} className="btn-pressable" style={{ width: 28, height: 28, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="user-plus" size={13} /></button>
      </div>
      <div style={{ flex: 1, overflowY: 'auto', padding: '14px 18px', display: 'flex', flexDirection: 'column', gap: 4 }}>
        <div style={{ padding: '14px 0', borderBottom: '1px solid var(--border)', marginBottom: 12 }}>
          <div className="cjk h-display-md">这是你和 {peer.name} 的私聊起点</div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4 }}>添加好友于 2024.03.14 · 共同群组 3 个 · 共同好友 8 人</div>
        </div>
        {DM_THREAD.map((m, i) => {
          if (m.kind === 'embed') return (
            <div key={i} style={{ paddingLeft: 50, marginTop: 4, marginBottom: 6 }}><MiniRoomShare /></div>
          );
          return <CMD key={i} msg={m} samegroup={m.samegroup} />;
        })}
        <div className="cjk t-caption" style={{ color: 'var(--fg-3)', display: 'flex', alignItems: 'center', gap: 6, marginTop: 6, paddingLeft: 50 }}>
          <span style={{ display: 'inline-flex', gap: 3 }}>
            <span className="typing-dot" style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--fg-2)' }} />
            <span className="typing-dot" style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--fg-2)' }} />
            <span className="typing-dot" style={{ width: 4, height: 4, borderRadius: '50%', background: 'var(--fg-2)' }} />
          </span>
          {peer.name} 正在输入…
        </div>
      </div>
      <div style={{ padding: '6px 18px 16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: 'var(--bg-1)', borderRadius: 'var(--r-md)', border: '1px solid var(--border-strong)', paddingInline: 12, height: 40 }}>
          <Lu name="plus" size={14} color="var(--fg-2)" />
          <input className="cjk t-body" placeholder={`发个消息给 ${peer.name}`} style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: 'var(--fg-0)' }} />
          <Lu name="image" size={13} color="var(--fg-2)" />
          <Lu name="smile" size={13} color="var(--fg-2)" />
        </div>
      </div>
    </main>
  );
}

function DMSidebar({ activeId, onPick }: any) {
  const { data: friends = [] } = useFriends();
  return (
    <aside style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
      <div style={{ padding: '12px 14px', borderBottom: '1px solid var(--border)' }}>
        <div style={{ height: 30, background: 'var(--bg-2)', borderRadius: 6, border: '1px solid var(--border)', paddingInline: 10, display: 'flex', alignItems: 'center', gap: 8 }}>
          <Lu name="search" size={12} color="var(--fg-2)" />
          <span className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>找一个 DM 或好友</span>
        </div>
      </div>
      <div style={{ padding: '8px 6px' }}>
        <RowD active={!activeId} onClick={() => onPick(null)} leading={<Lu name="users" size={14} color="var(--fg-2)" />}>
          <span className="cjk t-body" style={{ fontWeight: 600, color: 'var(--fg-0)' }}>好友</span>
        </RowD>
        <RowD onClick={() => onPick('inbox')} leading={<Lu name="inbox" size={14} color="var(--fg-2)" />}>
          <span className="cjk t-body">消息请求</span>
        </RowD>
      </div>
      <div style={{ padding: '4px 8px 0' }}>
        <SLD right={<button className="btn-pressable" style={{ width: 16, height: 16, border: 'none', background: 'transparent', color: 'var(--fg-3)', cursor: 'pointer' }}><Lu name="plus" size={11} /></button>}>私聊</SLD>
      </div>
      <div style={{ padding: '6px 6px', overflowY: 'auto', flex: 1 }}>
        {friends.filter(f => f.status !== 'offline').slice(0, 5).map((f, i) => (
          <RowD key={f.handle} active={activeId === f.handle} onClick={() => onPick(f.handle)}
            leading={<AvD size={26} name={f.name} status={f.status} />}
            trailing={i === 0 ? <BdgD count={3} /> : null}>
            <div>
              <div className="cjk t-body" style={{ fontWeight: 600, color: activeId === f.handle ? 'var(--fg-0)' : 'var(--fg-1)' }}>{f.name}</div>
              <div className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>@{f.handle}</div>
            </div>
          </RowD>
        ))}
      </div>
      <IdD />
    </aside>
  );
}

type DMProps = {
  theme?: 'dark' | 'light';
  view?: 'friends' | 'dm';
  peer?: string;
  onNavigate?: (target: { name: string; [k: string]: any }) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function DM({ theme = 'dark', view = 'friends', peer, onNavigate, onToast }: DMProps) {
  const { data: friends = [] } = useFriends();
  const peerObj = peer ? friends.find(f => f.handle === peer) || friends[1] : friends[1];
  const nav = (t: any) => onNavigate && onNavigate(t);
  const stub = (label: string) => onToast && onToast({ tone: 'info', title: label });
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)' }}>
      <RailD active="dm" onPick={(p: string) => {
        if (p === 'home') nav({ name: 'lobby' });
        else if (p === 'settings') nav({ name: 'settings' });
        else if (p === 'discover') stub('发现');
        else if (p === 'add-server') stub('添加服务器');
        else nav({ name: 'lobby', gameId: p });
      }} />
      <DMSidebar activeId={view === 'dm' ? (peerObj && peerObj.handle) : null} onPick={(handle: string | null) => {
        if (!handle) nav({ name: 'dm', view: 'friends' });
        else nav({ name: 'dm', view: 'dm', peer: handle });
      }} />
      {view === 'dm' && peerObj
        ? <DMThread peer={peerObj} onPin={() => stub('置顶对话')} onAddUser={() => stub('邀请进群聊')} />
        : <FriendsHome active="online" onMessage={(handle: string) => nav({ name: 'dm', view: 'dm', peer: handle })} onAddFriend={() => stub('添加好友')} />}
    </div>
  );
}

export { DM };
