// Generated by Claude Design (Opus 4.7) v0.7 — Friends + DM page.
//
// The bug this page was built around, because it is the one that looks most
// like working code:
//
//     const peerObj = peer ? friends.find(f => f.handle === peer) || friends[1]
//                          : friends[1];
//
// A peer that is not in the friend list silently became the *second friend in
// the array*. Every path into this page that named a handle the client could
// not resolve therefore opened a different person's conversation: the sidebar's
// 消息请求 row passed the literal string 'inbox' and landed in a DM with
// whoever happened to be friends[1]. No exception, no console error — a link
// that went to the wrong place, which is the one class of bug a
// "nothing threw" check cannot see. A handle now resolves to exactly that
// person or to an explicit "no such person" panel.

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { useBackendReachable, BackendBanner } from '@/components/backend-status';
import { ChatComposer, sendFailureToast } from '@/components/chat-composer';
import { useFriends, usePendingFriends, useDMThread, useMe, useProfile, useRooms } from '@/hooks';
import { Unavailable } from '@/components/unavailable';
import { resolveSharedRoom, SHARED_ROOM_MISSING } from '@/lib/room-share';
import { copyToClipboard, currentViewUrl } from '@/lib/clipboard';
import type { Friend, PendingFriend, Profile, RoomShareEmbed } from '@/lib/api/types';
import type { FriendsTabId, NavTarget } from '@/router';

const { useState: useStateD, useMemo: useMemoD } = React;
const { Button: BtnD, Avatar: AvD, Input: InpD } = UI;
const { ServerRail: RailD, Row: RowD, SectionLabel: SLD, IdentityCard: IdD, ChatMessage: CMD } = SHARED;

// The thread used to be a hardcoded array while `useDMThread` /
// `GET /v1/dm/{handle}/chat` sat unused next to it: the page showed 咲夜's
// canned 20:48 conversation for *every* peer. Both now come from the API.

/**
 * The room card inside a DM.
 *
 * Every field here used to be a literal — "永夜抄 Lunatic · 4B 路线练习",
 * "#4912", "主 咲夜 · 28ms · 3/6" — rendered identically for every share in
 * every thread, with a 立即加入 button wired to `onJoin`. It now renders the
 * fields the message actually carries.
 */
function MiniRoomShare({ share, onJoin, onJoinBlocked, onCopy }: {
  share: RoomShareEmbed;
  onJoin?: () => void;
  onJoinBlocked?: string;
  onCopy?: () => void;
}) {
  return (
    <div style={{
      maxWidth: 380, padding: 10, borderRadius: 'var(--r-md)',
      background: 'var(--bg-1)', border: '1px solid var(--border)',
      borderLeft: '2px solid var(--accent)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span className="t-tag" style={{ color: 'var(--accent)' }}>ROOM</span>
        <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>共享房间</span>
      </div>
      <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{share.title}</div>
      <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2 }}>
        <span style={{ color: 'var(--fg-1)' }}>主</span> {share.host} · {share.ping}ms ·{' '}
        <span className="num" style={{ color: 'var(--fg-1)', fontWeight: 600 }}>{share.taken}/{share.total}</span>
      </div>
      <div style={{ display: 'flex', gap: 6, marginTop: 8 }}>
        {onJoinBlocked ? (
          <Unavailable reason={onJoinBlocked}>
            <BtnD variant="primary" size="sm" disabled style={{ flex: 1 }}><span className="cjk">立即加入</span></BtnD>
          </Unavailable>
        ) : (
          <BtnD variant="primary" size="sm" style={{ flex: 1 }} onClick={onJoin}><span className="cjk">立即加入</span></BtnD>
        )}
        <BtnD variant="ghost" size="sm" title="复制当前页面链接" aria-label="复制当前页面链接" onClick={onCopy}><Lu name="copy" size={11} /></BtnD>
      </div>
    </div>
  );
}

/**
 * `kind: 'pending'` and `f: PendingFriend` are the same fact stated twice, so
 * they are one discriminated union here: within the pending branch `f` is a
 * `PendingFriend` and `f.dir` is guaranteed, with no cast to arrange it.
 */
type FriendRowProps =
  | { f: PendingFriend; kind: 'pending'; onMessage?: never }
  | { f: Friend; kind?: 'all'; onMessage?: () => void };

/** The four tabs on the friends page. The id union lives in the router. */
const FRIEND_TAB_LABELS: Record<FriendsTabId, string> = {
  online: '在线',
  all: '全部',
  pending: '待处理',
  blocked: '已屏蔽',
};

/** What accepting or ignoring a request would need from the server. */
const FRIEND_WRITE_MISSING =
  '接受 / 忽略好友请求需要 PATCH /v1/friends/{handle}；服务端目前只有 GET /v1/friends 和 GET /v1/friends/pending。';

function FriendRow(props: FriendRowProps) {
  const f = props.f;
  const action = props.kind !== 'pending' ? (
    <div style={{ display: 'flex', gap: 6 }}>
      <button title="发消息" onClick={props.onMessage} className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="message-square" size={13} /></button>
      <Unavailable reason="更多操作还没有可列的动作：拉黑、删除好友和备注都要服务端先有对应的写接口。">
        <button title="更多" disabled className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-1)', cursor: 'not-allowed', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="more-horizontal" size={13} /></button>
      </Unavailable>
    </div>
  ) : props.f.dir === 'in' ? (
    <div style={{ display: 'flex', gap: 6 }}>
      <Unavailable reason={FRIEND_WRITE_MISSING}>
        <button title="接受" disabled className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-0)', cursor: 'not-allowed', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="check" size={13} /></button>
      </Unavailable>
      <Unavailable reason={FRIEND_WRITE_MISSING}>
        <button title="忽略" disabled className="btn-pressable" style={{ width: 30, height: 30, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-2)', cursor: 'not-allowed', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="x" size={13} /></button>
      </Unavailable>
    </div>
  ) : (
    <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>等待回应</span>
  );
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 16px', borderTop: '1px solid var(--border)' }}>
      <AvD size={36} name={f.name} status={f.status} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
          <span className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{f.name}</span>
          <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)' }}>@{f.handle}</span>
          {f.mutual ? <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>· {f.mutual} 个共同好友</span> : null}
        </div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2, display: 'flex', alignItems: 'center', gap: 6 }}>
          {f.game ? <span className="num" style={{ fontSize: 10, padding: '1px 5px', border: '1px solid var(--border)', borderRadius: 3, color: 'var(--fg-1)' }}>{f.game}</span> : null}
          {f.subtle}
        </div>
      </div>
      {action}
    </div>
  );
}

function FriendsTab({ tab, query, onMessage }: { tab: FriendsTabId; query: string; onMessage?: (handle: string) => void }) {
  const { data: friends = [] } = useFriends();
  const friendsFailed = useBackendReachable() === 'down';
  const { data: pending = [] } = usePendingFriends();
  // The search box was a real <input> wired to nothing: typing filtered no
  // list, and the list it sat above was never going to change. It filters now.
  const q = query.trim().toLowerCase();
  const matches = (name: string, handle: string) =>
    !q || name.toLowerCase().includes(q) || handle.toLowerCase().includes(q);

  const visible = useMemoD(() => {
    const list = tab === 'online'
      ? friends.filter((f) => f.status !== 'offline')
      : tab === 'pending' ? [] : friends;
    return list.filter((f) => matches(f.name, f.handle));
  }, [tab, friends, q]);
  const visiblePending = useMemoD(
    () => pending.filter((p) => matches(p.name, p.handle)),
    [pending, q],
  );

  return (
    <div style={{ flex: 1, overflowY: 'auto' }}>
      <div style={{ paddingInline: 16, paddingTop: 14, paddingBottom: 8, position: 'sticky', top: 0, background: 'var(--bg-0)' }}>
        <div className="cjk t-tag" style={{ color: 'var(--fg-2)', marginTop: 14 }}>
          {FRIEND_TAB_LABELS[tab]} — {tab === 'pending' ? visiblePending.length : visible.length}
        </div>
      </div>
      {(() => {
        if (tab === 'blocked') return <UI.EmptyState icon="user-x" title="没有屏蔽任何人" body="屏蔽列表需要服务端存一份；/v1/friends 目前只返回好友，不返回屏蔽。" />;
        const rows = tab === 'pending'
          ? visiblePending.map((p) => <FriendRow key={p.handle} f={p} kind="pending" />)
          : visible.map((f) => <FriendRow key={f.handle} f={f} onMessage={() => onMessage?.(f.handle)} />);
        if (rows.length > 0) return rows;
        if (q) {
          return <UI.EmptyState icon="search" title={`没有匹配「${query}」的好友`} body="清除搜索词就能看到完整列表。" />;
        }
        return (
          <UI.EmptyState
            icon={tab === 'pending' ? 'user-plus' : 'users'}
            title={
              friendsFailed ? '读不到好友列表'
                : tab === 'pending' ? '没有待处理的请求'
                : tab === 'online' ? '现在没有在线的好友'
                : '还没有好友'
            }
            body={
              friendsFailed ? '连不上服务器，请确认服务端已启动。'
                : tab === 'pending' ? '别人的好友请求会出现在这里。'
                : '服务端还没有好友，所以这里也是空的。'
            }
          />
        );
      })()}
    </div>
  );
}

function FriendsHome({ active = 'online', onMessage, onTab }: {
  active?: FriendsTabId;
  onMessage?: (handle: string) => void;
  onTab?: (tab: FriendsTabId) => void;
}) {
  const [tab, setTab] = useStateD<FriendsTabId>(active);
  const [query, setQuery] = useStateD('');
  // The dot on 待处理 was a literal `count: 1` in a hardcoded array, while the
  // header in the same component counted the real pending list.
  const { data: pending = [] } = usePendingFriends();
  const { data: me } = useMe();
  const pick = (next: FriendsTabId) => { setTab(next); setQuery(''); onTab?.(next); };
  return (
    <main className="thp-col-main" style={{ display: 'flex', flexDirection: 'column', background: 'var(--bg-0)' }}>
      <div style={{ height: 48, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 14, borderBottom: '1px solid var(--border)' }}>
        <Lu name="users" size={14} color="var(--fg-2)" />
        <span className="cjk h-display-sm">好友</span>
        <span style={{ width: 1, height: 16, background: 'var(--border)' }} />
        {(Object.keys(FRIEND_TAB_LABELS) as FriendsTabId[]).map((id) => (
          <button
            key={id}
            onClick={() => pick(id)}
            aria-current={tab === id}
            className="btn-pressable"
            style={{
              height: 26, paddingInline: 10, borderRadius: 6, border: 'none',
              background: tab === id ? 'var(--bg-2)' : 'transparent',
              color: tab === id ? 'var(--fg-0)' : 'var(--fg-2)',
              fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-sans)',
              display: 'inline-flex', alignItems: 'center', gap: 6,
            }}
          >
            <span className="cjk">{FRIEND_TAB_LABELS[id]}</span>
            {id === 'pending' && pending.length > 0 ? <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--accent)' }} /> : null}
          </button>
        ))}
        <span style={{ flex: 1 }} />
        {/* The one action on this page that has no server behind it. It said
            "该功能将在 V1 后期开放" in a toast, which is not an answer. */}
        <Unavailable reason="添加好友需要 POST /v1/friends；服务端只有 GET /v1/friends，现在发不出邀请。">
          <BtnD variant="primary" size="sm" disabled>
            <Lu name="user-plus" size={12} />
            <span className="cjk" style={{ marginLeft: 6 }}>添加好友</span>
          </BtnD>
        </Unavailable>
      </div>
      <div style={{ padding: '14px 16px 0' }}>
        <InpD
          leading={<Lu name="search" size={13} color="var(--fg-2)" />}
          placeholder="搜索好友"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
      </div>
      <FriendsTab tab={tab} query={query} onMessage={onMessage} />
      <div style={{ padding: '8px 16px 14px', borderTop: '1px solid var(--border)' }}>
        <span className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>
          你是 <span className="num">{me ? `@${me.handle}` : '…'}</span> · 列表来自 GET /v1/friends
        </span>
      </div>
    </main>
  );
}

/**
 * Resolves a handle to the person it names, for the thread header.
 *
 * A DM peer does not have to be a friend: the handle can come from a room seat,
 * a share or a pasted link. The friend list is the fast path, and
 * `GET /v1/users/{handle}` — a route that already exists — is the fallback.
 */
function usePeerIdentity(handle: string): Friend | null | 'unknown' {
  const { data: friends } = useFriends();
  const found = friends?.find((f) => f.handle === handle);
  const needsLookup = !found && !!handle;
  const { data: profile, isLoading } = useProfile(needsLookup ? handle : '');
  if (found) return found;
  if (profile) {
    return {
      name: profile.name,
      handle: profile.handle,
      status: profile.status,
      subtle: profile.presence,
    };
  }
  return needsLookup && !isLoading ? 'unknown' : null;
}

function DMThread({ handle, peer, onToast }: {
  handle: string;
  peer: Friend | null | 'unknown';
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
}) {
  // Real thread from GET /v1/dm/{handle}/chat. The page previously rendered a
  // module-level constant, so every peer got the same canned conversation.
  const { data: msgs = [], isLoading, error } = useDMThread(handle);
  const failed = useBackendReachable() === 'down';
  // Every game, so a shared TH07 room resolves as readily as a TH08 one.
  const { data: rooms = [] } = useRooms();

  // A DM channel id is the peer's handle: the server seeds dm messages with
  // scopeID = the other party's handle, which is the same spelling
  // GET /v1/dm/{handle}/chat reads. CreateChannelMessage only knows about group
  // channels today, so this POST currently 404s — the composer reports that
  // honestly instead of claiming a send it did not make.
  const channelId = handle;

  if (peer === 'unknown') {
    return (
      <main className="thp-col-main" style={{ display: 'flex', flexDirection: 'column', background: 'var(--bg-0)' }}>
        <UI.EmptyState
          icon="user-x"
          title={`服务器上没有 @${handle}`}
          body="这个 handle 既不在好友列表里，GET /v1/users/{handle} 也没有返回资料。"
          action={
            <BtnD variant="secondary" size="md" onClick={() => { window.location.hash = '#/dm/friends'; }}>
              <span className="cjk">回到好友列表</span>
            </BtnD>
          }
        />
      </main>
    );
  }

  const name = peer?.name ?? handle;
  return (
    <main className="thp-col-main" style={{ display: 'flex', flexDirection: 'column', background: 'var(--bg-0)' }}>
      <div style={{ height: 48, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 12, borderBottom: '1px solid var(--border)' }}>
        <AvD size={26} name={name} status={peer?.status} />
        <div>
          <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{name} <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)', fontWeight: 500 }}>@{handle}</span></div>
          {/* `peer.subtle` used to be a hardcoded "添加好友于 2024.03.14 · 共同群组
              3 个 · 共同好友 8 人" repeated for every peer, including people the
              client has never met. Now it is whatever the API said, or nothing. */}
          {peer?.subtle ? <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{peer.subtle}</div> : null}
        </div>
        <span style={{ flex: 1 }} />
        <Unavailable reason="置顶对话需要服务端把置顶状态存到这条会话上；/v1/dm/{handle}/chat 只返回消息。">
          <button title="置顶" disabled className="btn-pressable" style={{ width: 28, height: 28, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'not-allowed', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="pin" size={13} /></button>
        </Unavailable>
        <Unavailable reason="邀请进群聊需要服务端建群和加成员的写接口；本轮没有这些接口。">
          <button title="邀请群聊" disabled className="btn-pressable" style={{ width: 28, height: 28, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'not-allowed', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="user-plus" size={13} /></button>
        </Unavailable>
      </div>
      <div style={{ flex: 1, overflowY: 'auto', padding: '14px 18px', display: 'flex', flexDirection: 'column', gap: 4 }}>
        <div style={{ padding: '14px 0', borderBottom: '1px solid var(--border)', marginBottom: 12 }}>
          <div className="cjk h-display-md">与 {name} 的私聊</div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4 }}>{msgs.length > 0 ? `共 ${msgs.length} 条消息 · 通过 @${handle} 投递` : `通过 @${handle} 投递`}</div>
        </div>
        {isLoading ? (
          <div className="cjk t-caption" style={{ color: 'var(--fg-3)', padding: '20px 0', textAlign: 'center' }}>正在读取与 {name} 的私聊…</div>
        ) : failed || error ? (
          <UI.EmptyState
            icon="unplug"
            title={failed ? '连不上服务器' : '读不到私聊记录'}
            body={failed ? '服务端没有响应，稍后会自动重试。' : '这个私聊线程暂时读不出来，可能已经在路上了。'}
          />
        ) : msgs.length === 0 ? (
          <UI.EmptyState
            icon="message-square"
            title="还没有聊过"
            body={`还没有和 ${name} 的消息。发一条就是这串私聊的起点。`}
          />
        ) : msgs.map((m, i) => (
          <div key={i}>
            <CMD msg={m} samegroup={m.samegroup} />
            {m.share ? (
              <div style={{ marginLeft: 38, marginTop: 6 }}>
                <MiniRoomShare
                  share={m.share}
                  onJoin={() => {
                    const target = resolveSharedRoom(m.share!, rooms);
                    if (target) window.location.hash = `#/room/${target.id}`;
                    else onToast?.({ tone: 'warn', title: '这张分享卡指向的房间不在列表里', body: SHARED_ROOM_MISSING });
                  }}
                  onCopy={async () => {
                    const ok = await copyToClipboard(currentViewUrl());
                    onToast?.(ok
                      ? { tone: 'success', title: '已复制', body: currentViewUrl() }
                      : { tone: 'warn', title: '复制失败', body: '浏览器拒绝了剪贴板写入，请手动复制地址栏的链接。' });
                  }}
                />
              </div>
            ) : null}
          </div>
        ))}
      </div>
      {/* No "X 正在输入…" line. It was hardcoded and permanent: the peer was
          "typing" forever, on every thread, with no event behind it. */}
      <ChatComposer
        channelId={channelId}
        placeholder={`发个消息给 ${name}`}
        onSent={() => onToast?.({ tone: 'success', title: '已发送' })}
        onFailed={(_c, error) => onToast?.(sendFailureToast(error))}
      />
    </main>
  );
}

function DMSidebar({ activeHandle, me, onPick, onOpenTab, onSettings, onProfile }: {
  activeHandle: string | null;
  me: Profile | null;
  onPick: (handle: string) => void;
  onOpenTab: (tab: FriendsTabId) => void;
  onSettings: () => void;
  onProfile: () => void;
}) {
  const { data: friends = [] } = useFriends();
  const { data: pending = [] } = usePendingFriends();
  const sidebarFailed = useBackendReachable() === 'down';
  const [query, setQuery] = useStateD('');
  // The badge on the first row was a literal `count={3}`: an unread count for
  // a thread this client has never read and cannot track. No unread route
  // exists, so there is no number to show.
  const q = query.trim().toLowerCase();
  const recent = friends
    .filter((f) => f.status !== 'offline')
    .filter((f) => !q || f.handle.toLowerCase().includes(q) || f.name.toLowerCase().includes(q))
    .slice(0, 5);
  return (
    <aside className="thp-col-nav" style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
      <div style={{ padding: '12px 14px', borderBottom: '1px solid var(--border)' }}>
        {/* This was a div with placeholder text styled like an input. It is now
            a real input, and it filters the list directly below it. */}
        <InpD
          leading={<Lu name="search" size={12} color="var(--fg-2)" />}
          placeholder="找一个 DM 或好友"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
      </div>
      <div style={{ padding: '8px 6px' }}>
        <RowD active={!activeHandle} onClick={() => onOpenTab('online')} leading={<Lu name="users" size={14} color="var(--fg-2)" />}>
          <span className="cjk t-body" style={{ fontWeight: 600, color: 'var(--fg-0)' }}>好友</span>
        </RowD>
        {/* This row passed the literal string 'inbox' to the DM route, which
            resolved to no peer and therefore fell back to friends[1] — the
            消息请求 button opened an unrelated conversation. It now opens the
            pending tab, which is what the label says. */}
        <RowD onClick={() => onOpenTab('pending')} leading={<Lu name="inbox" size={14} color="var(--fg-2)" />}>
          <span className="cjk t-body">消息请求</span>
          {pending.length > 0 ? (
            <span className="num" style={{ marginLeft: 6, fontSize: 10, color: 'var(--fg-2)' }}>{pending.length}</span>
          ) : null}
        </RowD>
      </div>
      <div style={{ padding: '4px 8px 0' }}>
        <SLD right={
          <Unavailable reason="发起新私聊需要一个可搜索的用户目录；服务端只有按 handle 取资料，没有搜索。">
            <button disabled className="btn-pressable" style={{ width: 16, height: 16, border: 'none', background: 'transparent', color: 'var(--fg-3)', cursor: 'not-allowed', display: 'inline-flex' }}><Lu name="plus" size={11} /></button>
          </Unavailable>
        }>私聊</SLD>
      </div>
      <div style={{ padding: '6px 6px', overflowY: 'auto', flex: 1 }}>
        {recent.length === 0 ? (
          <div className="cjk t-caption" style={{ color: 'var(--fg-3)', padding: '10px 8px', lineHeight: 1.6 }}>
            {sidebarFailed ? '连不上服务器，暂时拿不到最近联系人。' : '还没有在线的好友可以私聊。'}
          </div>
        ) : recent.map((f) => (
          <RowD
            key={f.handle}
            active={activeHandle === f.handle}
            onClick={() => onPick(f.handle)}
            leading={<AvD size={26} name={f.name} status={f.status} />}
          >
            <div style={{ minWidth: 0 }}>
              <div className="cjk t-body" style={{ fontWeight: 600, color: activeHandle === f.handle ? 'var(--fg-0)' : 'var(--fg-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{f.name}</div>
              <div className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>@{f.handle}</div>
            </div>
          </RowD>
        ))}
      </div>
      <IdD me={me ?? null} onSettings={onSettings} onProfile={onProfile} />
    </aside>
  );
}

type DMProps = {
  theme?: 'dark' | 'light';
  view?: 'friends' | 'dm';
  peer?: string;
  tab?: FriendsTabId;
  onNavigate?: (target: NavTarget) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function DM({ theme = 'dark', view = 'friends', peer, tab = 'online', onNavigate, onToast }: DMProps) {
  const nav = (t: NavTarget) => onNavigate && onNavigate(t);
  // Resolved, not guessed. See the note at the top of this file.
  const peerIdentity = usePeerIdentity(view === 'dm' ? (peer ?? '') : '');
  const { data: me } = useMe();
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)', position: 'relative' }}>
      <BackendBanner />
      <RailD active="dm" onPick={(p: string) => {
        if (p === 'home') nav({ name: 'lobby' });
        else if (p === 'settings') nav({ name: 'settings' });
        else if (p === 'discover') nav({ name: 'lobby' });
        else if (p === 'add-server') onToast?.({ tone: 'warn', title: '还不能添加服务器', body: '后端地址来自 VITE_API_BASE_URL，没有运行时切换服务器这个接口。' });
        else nav({ name: 'lobby', gameId: p });
      }} />
      <DMSidebar
        activeHandle={view === 'dm' ? (peer ?? null) : null}
        me={me ?? null}
        onPick={(handle) => nav({ name: 'dm', view: 'dm', peer: handle })}
        onOpenTab={(next) => nav({ name: 'dm', view: 'friends', tab: next })}
        onSettings={() => nav({ name: 'settings' })}
        onProfile={() => nav({ name: 'profile' })}
      />
      {view === 'dm' && peer
        ? <DMThread handle={peer} peer={peerIdentity} onToast={onToast} />
        : <FriendsHome active={tab} onMessage={(handle) => nav({ name: 'dm', view: 'dm', peer: handle })} onTab={(next) => nav({ name: 'dm', view: 'friends', tab: next })} />}
    </div>
  );
}

export { DM };
