
// Generated by Claude Design (Opus 4.7) v0.7 — Group page.

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { api } from '@/lib/api/client';
import { useAsync } from '@/hooks/use-async';
import { useMe } from '@/hooks';
import { useBackendReachable, BackendBanner } from '@/components/backend-status';
import { ChatComposer, sendFailureToast } from '@/components/chat-composer';
import type { Channel } from '@/lib/api/types';
import type { NavTarget } from '@/router';

const { useState: useStateG } = React;
const { Button: BtnG, Badge: BdgG } = UI;
const { ServerRail: RailG, Row: RowG, IdentityCard: IdG, ChatMessage: CMG } = SHARED;

/**
 * What the page shows when there is no group to render: still loading, server
 * unreachable, or a group the server says does not exist.
 *
 * All three used to look identical, and the identical-looking one was the
 * loaded one -- the page held its group card, channel tree, announcement and
 * message log in module-level constants, so it rendered a complete group with
 * the backend stopped. `getGroup` and `getGroupAnnouncement` are the two routes
 * that throw rather than degrade, so useAsync hands their failures over as
 * `error`; the reachability probe is what separates "no such group" from
 * "could not ask".
 */
function groupStatus({ loading, unreachable, handle, onRetry, onBack }: {
  loading: boolean;
  unreachable: boolean;
  handle: string;
  onRetry: () => void;
  onBack: () => void;
}) {
  if (loading) {
    return (
      <UI.EmptyState
        icon="loader"
        title="正在读取群组…"
        body={`正在向服务器请求 /v1/groups/${handle}`}
      />
    );
  }
  if (unreachable) {
    return (
      <UI.EmptyState
        icon="wifi-off"
        title="读不到这个群组"
        body="连不上服务器。下面的频道和消息可能是空的，也可能只是没读到。"
        action={
          <BtnG variant="primary" size="md" onClick={onRetry}>
            <Lu name="refresh-cw" size={12} />
            <span className="cjk" style={{ marginLeft: 6 }}>重试</span>
          </BtnG>
        }
      />
    );
  }
  return (
    <UI.EmptyState
      icon="users"
      title={`群组 @${handle} 不存在`}
      body="服务器回答了，但它手上没有这个群组。"
      action={
        <BtnG variant="secondary" size="md" onClick={onBack}>
          <span className="cjk">返回大厅</span>
        </BtnG>
      }
    />
  );
}

function ChannelRow({ item, active, index = 0, onClick }: {
  item: Channel;
  active: boolean;
  index?: number;
  onClick: () => void;
}) {
  const lead = <span style={{ color: 'var(--fg-2)', fontWeight: 500, fontSize: 14, width: 14, textAlign: 'center' }}>#</span>;
  const tail = item.unread
    ? <BdgG count={item.unread} />
    : item.voice
      ? <span className="num" style={{ fontSize: 9.5, color: 'var(--fg-2)' }}>{item.count ?? 0}</span>
      : item.tag
        ? <span className="cjk" style={{ fontSize: 9.5, color: 'var(--fg-2)', padding: '1px 6px', border: '1px solid var(--border)', borderRadius: 3, background: 'var(--bg-1)' }}>{item.tag}</span>
        : null;
  return (
    <RowG active={active} onClick={onClick} leading={lead} trailing={tail} animateIn index={index}>
      <span className="cjk t-body" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: active ? 600 : 500, color: active ? 'var(--fg-0)' : 'var(--fg-1)' }}>{item.label}</span>
    </RowG>
  );
}


type GroupProps = {
  theme?: 'dark' | 'light';
  handle?: string;
  onNavigate?: (target: NavTarget) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function Group({ theme = 'dark', handle = 'yegumi', onNavigate, onToast }: GroupProps) {
  const nav = (t: NavTarget) => onNavigate && onNavigate(t);
  const stub = (label: string) => onToast && onToast({ tone: 'info', title: label });
  const [pickedId, setPickedId] = useStateG<string | null>(null);

  // Group, channel tree and announcement are one load: the announcement is a
  // single object rather than a list, and its route throws both when the group
  // has none and when the server is down, so it is caught here and the
  // difference is made at render time by the reachability probe.
  const { data: head, isLoading, refetch } = useAsync(async () => {
    const [group, cats] = await Promise.all([
      api.getGroup(handle),
      api.listGroupChannels(handle),
    ]);
    const announcement = await api.getGroupAnnouncement(handle).catch(() => null);
    return { group, cats, announcement };
  }, [handle]);

  const unreachable = useBackendReachable() === 'down';
  const { data: me } = useMe();
  const group = head?.group ?? null;
  const cats = head?.cats ?? [];
  const announcement = head?.announcement ?? null;
  // The channel id is taken from the channel list the server returned, never
  // rebuilt by concatenating the handle: that list is the only thing that knows
  // which spelling a channel answers to.
  const channels = cats.flatMap((cat) => cat.items);
  const active = channels.find((c) => c.id === pickedId)
    ?? channels.find((c) => !c.voice && (c.mention ?? c.unread))
    ?? channels.find((c) => !c.voice)
    ?? channels[0];

  const { data: messages = [], isLoading: messagesLoading, refetch: refetchMessages } = useAsync(
    () => (active ? api.listGroupMessages(handle, active.id) : Promise.resolve([])),
    [handle, active?.id],
  );

  const shares = messages.filter((m) => m.share);
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)', position: 'relative' }}>
      <BackendBanner />
      <RailG active={handle} onPick={(p: string) => {
        if (p === 'home') nav({ name: 'lobby' });
        else if (p === 'settings') nav({ name: 'settings' });
        else if (p === 'discover') stub('发现');
        else if (p === 'add-server') stub('添加服务器');
        else nav({ name: 'lobby', gameId: p });
      }} />
      <aside className="thp-col-nav" style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
        <div style={{
          padding: '14px 14px 12px',
          background: 'var(--bg-2)',
          borderBottom: '1px solid var(--border)',
          borderLeft: '2px solid var(--accent)',
        }}>
          <div className="cjk h-display-sm" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{group ? group.name : '未载入'}</div>
          <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)', marginTop: 2 }}>@{group ? group.handle : handle} · {group ? `since ${group.established}` : '—'}</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 }}>
            <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-1)' }}>
              <span style={{ color: 'var(--fg-0)', fontWeight: 700 }}>{group ? group.online : '—'}</span><span style={{ color: 'var(--fg-3)' }}> / {group ? group.members : '—'} </span>online
            </span>
            <span style={{ flex: 1 }} />
            <button title="搜索" onClick={() => stub('群内搜索')} className="btn-pressable" style={{ width: 22, height: 22, border: 'none', background: 'transparent', color: 'var(--fg-2)', cursor: 'pointer', borderRadius: 4, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="search" size={12} /></button>
            <button title="群组设置" onClick={() => stub('群组设置')} className="btn-pressable" style={{ width: 22, height: 22, border: 'none', background: 'transparent', color: 'var(--fg-2)', cursor: 'pointer', borderRadius: 4, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="chevron-down" size={12} /></button>
          </div>
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: '8px 6px' }}>
          {cats.length === 0 ? (
            <UI.EmptyState
              icon="hash"
              title={!group ? '群组未载入' : unreachable ? '读不到频道列表' : '这个群组还没有频道'}
              body={!group
                ? '这个群组还没有载入，频道列表读不了。'
                : unreachable
                  ? '连不上服务器，频道列表可能已经在路上了。'
                  : '创建第一个频道之后，这里会显示频道树。'}
            />
          ) : cats.map(cat => (
            <div key={cat.id} style={{ marginTop: 8 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 4, paddingInline: 8, marginBottom: 2 }}>
                <Lu name="chevron-down" size={10} color="var(--fg-3)" />
                <span className="cjk t-tag" style={{ color: 'var(--fg-2)', flex: 1 }}>{cat.label}</span>
                <button className="btn-pressable" style={{ width: 16, height: 16, border: 'none', background: 'transparent', color: 'var(--fg-3)', cursor: 'pointer' }}><Lu name="plus" size={11} /></button>
              </div>
              <div>
                {cat.items.map((item, j) => (
                  <ChannelRow key={item.id} item={item} active={item.id === active?.id} index={j} onClick={() => setPickedId(item.id)} />
                ))}
              </div>
            </div>
          ))}
        </div>
        <IdG me={me ?? null} onSettings={() => nav({ name: 'settings' })} onProfile={() => nav({ name: 'profile' })} />
      </aside>
      <main className="thp-col-main" style={{ display: 'flex', flexDirection: 'column', background: 'var(--bg-0)' }}>
        <div style={{ height: 48, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 12, borderBottom: '1px solid var(--border)' }}>
          <span style={{ color: 'var(--fg-2)', fontSize: 16, fontWeight: 500 }}>#</span>
          <span className="cjk h-display-sm" style={{ minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{active ? active.label : '未选中频道'}</span>
          <span style={{ width: 1, height: 16, background: 'var(--border)' }} />
          <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{active ? active.id : ''}</span>
          <span style={{ flex: 1 }} />
          <button onClick={() => stub('频道通知设置')} className="btn-pressable" style={{ width: 26, height: 26, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="bell" size={13} /></button>
          <button onClick={() => stub('置顶消息列表')} className="btn-pressable" style={{ width: 26, height: 26, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="pin" size={13} /></button>
          <button onClick={() => stub('成员名单')} className="btn-pressable" style={{ width: 26, height: 26, border: 'none', background: 'transparent', color: 'var(--fg-2)', borderRadius: 6, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="users" size={13} /></button>
          <div style={{ height: 26, width: 180, background: 'var(--bg-2)', borderRadius: 6, border: '1px solid var(--border)', paddingInline: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
            <Lu name="search" size={12} color="var(--fg-2)" />
            <span className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>搜索消息</span>
          </div>
        </div>
        {!group ? (
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            {groupStatus({ loading: isLoading, unreachable, handle, onRetry: refetch, onBack: () => nav({ name: 'lobby' }) })}
          </div>
        ) : (
        <>
        <div style={{ flex: 1, overflowY: 'auto', paddingBottom: 12 }}>
          {!announcement ? (
            <div style={{ margin: '14px 18px 8px', padding: 14, border: '1px dashed var(--border)', borderRadius: 'var(--r-md)' }}>
              <UI.EmptyState
                icon="pin"
                title={unreachable ? '读不到置顶公告' : '还没有置顶公告'}
                body={unreachable
                  ? '连不上服务器，公告可能已经在路上了。'
                  : '这个群组还没有置顶公告，管理员发布后会显示在这里。'}
              />
            </div>
          ) : (
          <div style={{ margin: '14px 18px 8px', padding: 14, background: 'var(--bg-1)', border: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', borderRadius: 'var(--r-md)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
              <Lu name="pin" size={12} color="var(--accent)" />
              <span className="t-tag" style={{ color: 'var(--accent)' }}>置顶公告</span>
              <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)' }}>{announcement.pinnedBy} · {announcement.time}</span>
            </div>
            <div className="cjk h-display-sm">{announcement.title}</div>
            <div className="cjk t-body" style={{ color: 'var(--fg-1)', marginTop: 6, lineHeight: 1.65, whiteSpace: 'pre-line' }}>{announcement.body}</div>
          </div>
          )}
          <div style={{ padding: '8px 18px', display: 'flex', flexDirection: 'column', gap: 6 }}>
            {messagesLoading ? (
              <UI.EmptyState icon="loader" title="正在读取消息…" body={`正在向服务器请求 #${active?.id ?? ''} 的历史`} />
            ) : messages.length === 0 ? (
              <UI.EmptyState
                icon="message-square"
                title={unreachable ? '读不到消息' : '这个频道还没有消息'}
                body={unreachable
                  ? '连不上服务器，消息可能已经在路上了。'
                  : '还没有人在这个频道说话。'}
              />
            ) : messages.map((m, i) => (
              // A bare embed carries no author and no text -- the room it
              // shares is the whole message. Rendering it through ChatMessage
              // as well would put an empty avatar line above the card.
              m.kind === 'embed' ? (
                <div key={i} style={{ marginTop: 6 }}>
                  {m.share
                    ? <SHARED.ServerCardFlat compact {...m.share} onJoin={() => stub('加入房间')} />
                    : <div className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>{m.t} 分享了一个房间</div>}
                </div>
              ) : (
                <div key={i}>
                  <CMG msg={m} samegroup={m.samegroup} />
                  {m.share ? (
                    <div style={{ marginLeft: 38, marginTop: 6 }}>
                      <SHARED.ServerCardFlat compact {...m.share} onJoin={() => stub('加入房间')} />
                    </div>
                  ) : null}
                </div>
              )
            ))}
          </div>
        </div>
        <div style={{ padding: '6px 18px 16px' }}>
          {active?.voice ? (
            <div className="cjk t-caption" style={{ color: 'var(--fg-2)', textAlign: 'center', padding: '12px 0' }}>
              {active.label} 是语音频道，暂不支持文字消息。
            </div>
          ) : (
            <ChatComposer
              channelId={active?.id ?? ''}
              placeholder={active ? `发个消息到 #${active.label}` : '先选一个频道'}
              onSent={() => {
                // The POST already returned the stored message, so the one
                // thing left to do is re-read the channel: the server also
                // fans the message out over the channel's WebSocket, and a
                // refetch is what makes this tab agree with the server even
                // if that subscription is not up yet.
                void refetchMessages();
              }}
              onFailed={(_channelId, error) => onToast && onToast(sendFailureToast(error))}
              disabled={!active}
            />
          )}
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginTop: 6 }}>
            {/* Was "支持 Markdown · /room 分享当前房间 · @ 提及". None of the
                three is implemented: the composer POSTs the raw string, the
                server stores it verbatim (no markdown parsing, no /room
                command — CreateChannelMessage writes `in.Text` as-is), and
                `mention` is only ever set by the server, never by typing @. */}
            <span className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>纯文本发送 · @ 提及由服务端解析后才会高亮</span>
          </div>
        </div>
        </>
        )}
      </main>
      <aside className="thp-col-aside" style={{ width: 308, background: 'var(--bg-1)', borderLeft: '1px solid var(--border)', padding: 16, overflowY: 'auto' }}>
        <div className="t-tag" style={{ color: 'var(--fg-2)' }}>Room-Share · 本频道分享</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14, marginTop: 10 }}>
          {shares.length === 0 ? (
            <UI.EmptyState
              icon="share-2"
              title={!group ? '群组未载入' : unreachable ? '读不到分享记录' : '这个频道还没有分享过房间'}
              body={!group
                ? '这个群组还没有载入，分享记录读不了。'
                : unreachable
                  ? '连不上服务器，分享记录可能已经在路上了。'
                  : '这个频道还没有带房间卡片的消息。'}
            />
          ) : shares.map((m, i) => (
            <SHARED.ServerCardFlat key={i} compact {...m.share} onJoin={() => stub('加入房间')} />
          ))}
        </div>
        <div style={{ marginTop: 18, padding: 12, border: '1px dashed var(--border)', borderRadius: 'var(--r-md)' }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>房间卡片从哪来</div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-1)', marginTop: 6, lineHeight: 1.7 }}>
            卡片由服务端挂在消息的 <span className="num" style={{ color: 'var(--accent)', background: 'var(--bg-2)', padding: '1px 5px', borderRadius: 3 }}>share</span> 字段上，本客户端不生成它。
            这里过去写着「输入 /room 即可分享」，但输入框不会解析命令：消息按原样 POST，服务端也只是把正文存下来。
          </div>
        </div>
      </aside>
    </div>
  );
}

export { Group };
