// @ts-nocheck
// Generated by Claude Design (Opus 4.7) v0.7 — Lobby page.
// Locally wired to use hooks (useRooms / useLobbyFriends / useLobbyChat) and
// onNavigate callbacks. FEATURED tournament strip removed (no v1 feature).

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { useRooms, useLobbyFriends, useLobbyChat } from '@/hooks';
import type { Room as RoomT } from '@/lib/api/types';

const { useState: useStateL } = React;
const { Button: BtnL, Avatar: AvL, Input: InpL } = UI;
const { ServerRail: RailL, Row: RowL, SectionLabel: SLL, Tabs: TabsL, IdentityCard: IdL, StatusDot: SDL, ChatMessage: CML } = SHARED;

function RoomRow({ r, active, index = 0, onClick }: any) {
  const [hov, setHov] = useStateL(false);
  return (
    <div
      onMouseEnter={() => setHov(true)} onMouseLeave={() => setHov(false)}
      onClick={onClick}
      className="anim-row-in"
      style={{
        display: 'flex', alignItems: 'center', gap: 12,
        padding: '12px 14px',
        background: active ? 'var(--bg-2)' : hov ? 'var(--hover)' : 'var(--bg-1)',
        border: '1px solid',
        borderColor: active ? 'var(--border-strong)' : 'var(--border)',
        borderRadius: 'var(--r-md)',
        cursor: 'pointer',
        transform: hov && !active ? 'translateX(2px)' : 'translateX(0)',
        transition: 'background var(--duration-fast) var(--ease-out-quart), border-color var(--duration-fast) var(--ease-out-quart), transform var(--duration-fast) var(--ease-out-quart)',
        '--i': index,
      } as any}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
          <span className="t-tag" style={{ color: 'var(--fg-2)', padding: '1px 6px', border: '1px solid var(--border)', borderRadius: 4 }}>{r.kind === 'Official' ? '官方' : '个人'}</span>
          <span className="cjk t-body-lg" style={{ color: 'var(--fg-0)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r.title}</span>
        </div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          <span><span style={{ color: 'var(--fg-1)' }}>主</span> {r.host}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span>
          <span className="num">{r.ping}ms</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span><span>{r.region}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span><span>{r.diff}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span><span>{r.mode}</span>
        </div>
      </div>
      <div style={{ display: 'flex', alignItems: 'center' }}>
        {Array.from({ length: r.taken }).map((_, i) => (
          <span key={i} style={{
            width: 22, height: 22, borderRadius: '50%',
            background: 'var(--bg-2)', border: '2px solid var(--bg-1)',
            marginLeft: i === 0 ? 0 : -6,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            color: 'var(--fg-1)', fontSize: 9, fontWeight: 600,
          }}>{['幽','妖','咲','魔','灵','蕾'][i]}</span>
        ))}
        {Array.from({ length: r.total - r.taken }).map((_, i) => (
          <span key={`e${i}`} style={{
            width: 22, height: 22, borderRadius: '50%',
            background: 'transparent', border: '1px dashed var(--border-strong)',
            marginLeft: -6,
          }} />
        ))}
        <span className="num" style={{ marginLeft: 8, fontSize: 11, color: 'var(--fg-2)' }}>{r.taken}/{r.total}</span>
      </div>
    </div>
  );
}

type LobbyProps = {
  theme?: 'dark' | 'light';
  gameId?: 'th06' | 'th07' | 'th08' | 'th09';
  onNavigate?: (target: { name: string; [k: string]: any }) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function Lobby({ theme = 'dark', gameId = 'th08', onNavigate, onToast }: LobbyProps) {
  const { data: rooms = [] } = useRooms(gameId);
  const { data: friends = [] } = useLobbyFriends();
  const { data: chat = [] } = useLobbyChat(gameId);

  const nav = (t: any) => onNavigate && onNavigate(t);
  const stub = (label: string) => onToast && onToast({ tone: 'info', title: label, body: '该功能将在 V1 后期开放' });

  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)' }}>
      <RailL active={gameId} onPick={(id: string) => {
        if (id === 'home') nav({ name: 'lobby', gameId: 'th08' });
        else if (id === 'settings') nav({ name: 'settings' });
        else if (id === 'discover') stub('发现');
        else if (id === 'add-server') stub('添加服务器');
        else nav({ name: 'lobby', gameId: id });
      }} />
      {/* Col 2 — Lobby navigator */}
      <aside style={{ width: 256, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
        <div style={{ padding: 14, borderBottom: '1px solid var(--border)' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div className="cjk h-display-sm" style={{ color: 'var(--fg-0)' }}>大厅</div>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 10.5, color: 'var(--fg-2)' }}>
              <SDL status="online" /> CN-East · <span className="num" style={{ color: 'var(--fg-1)' }}>24ms</span>
            </span>
          </div>
          <div style={{ marginTop: 10 }}>
            <InpL leading={<Lu name="search" size={14} />} placeholder="搜索房间 · 玩家 · 频道" kbd="⌘K" onFocus={() => stub('搜索')} />
          </div>
        </div>
        <div style={{ padding: 10, overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div>
            <SLL>分类</SLL>
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 1 }}>
              <RowL active leading={<Lu name="globe" size={14} />} onClick={() => stub('官方房间过滤')}>
                <span className="cjk t-body" style={{ fontWeight: 600, color: 'var(--fg-0)' }}>官方房间</span>
              </RowL>
              <RowL leading={<Lu name="user" size={14} />} onClick={() => stub('个人房间过滤')}>
                <span className="cjk t-body">个人房间</span>
              </RowL>
              <RowL leading={<Lu name="users" size={14} />} trailing={<Lu name="lock" size={11} color="var(--fg-3)" />} style={{ opacity: 0.55 }}>
                <span className="cjk t-body" style={{ color: 'var(--fg-2)' }}>社区频道</span>
              </RowL>
            </div>
          </div>
          <div>
            <SLL>版本</SLL>
            <div style={{ marginTop: 6, display: 'flex', gap: 4, flexWrap: 'wrap' }}>
              {['TH06','TH07','TH08','TH09'].map(v => {
                const id = v.toLowerCase() as 'th06'|'th07'|'th08'|'th09';
                const on = id === gameId;
                return (
                  <button key={v} className="num btn-pressable" onClick={() => nav({ name: 'lobby', gameId: id })} style={{
                    height: 24, paddingInline: 8, display: 'inline-flex', alignItems: 'center',
                    borderRadius: 6, fontSize: 11, fontWeight: 600, cursor: 'pointer',
                    background: on ? 'var(--bg-3)' : 'var(--bg-2)',
                    color: on ? 'var(--fg-0)' : 'var(--fg-2)',
                    border: `1px solid ${on ? 'var(--border-strong)' : 'var(--border)'}`,
                  }}>{v}</button>
                );
              })}
            </div>
          </div>
          <div>
            <SLL right={<span style={{ fontSize: 10.5, color: 'var(--fg-3)' }}>2</span>}>我的房间</SLL>
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 1 }}>
              <RowL onClick={() => nav({ name: 'room', id: 1 })} leading={<span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--status-online)' }} />}>
                <span className="cjk t-body" style={{ color: 'var(--fg-0)' }}>昨日的房间</span>
                <div className="t-caption" style={{ color: 'var(--fg-2)' }}>TH08 · 3 人</div>
              </RowL>
              <RowL onClick={() => nav({ name: 'room', id: 2 })} leading={<span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--fg-3)' }} />}>
                <span className="cjk t-body" style={{ color: 'var(--fg-0)' }}>咲夜的茶话会</span>
                <div className="t-caption" style={{ color: 'var(--fg-2)' }}>TH07 · 待机中</div>
              </RowL>
            </div>
          </div>
          <div>
            <SLL right={<span className="num" style={{ fontSize: 10.5, color: 'var(--status-online)' }}>{friends.filter(f => f.status === 'online').length}</span>}>好友在线</SLL>
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 1 }}>
              {friends.map(f => (
                <RowL key={f.handle} onClick={() => nav({ name: 'dm', view: 'dm', peer: f.handle })}
                  leading={<AvL size={22} name={f.name} status={f.status} />}>
                  <div className="cjk t-body" style={{ color: 'var(--fg-0)' }}>{f.name}</div>
                  <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{f.game}</div>
                </RowL>
              ))}
            </div>
          </div>
        </div>
        <IdL onSettings={() => nav({ name: 'settings' })} onProfile={() => nav({ name: 'profile' })} />
      </aside>

      {/* Col 3 — Rooms list */}
      <main style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border)' }}>
        <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ flex: 1 }}>
            <h2 className="cjk h-display-md" style={{ margin: 0 }}>
              永夜抄 <span style={{ color: 'var(--fg-2)' }}>·</span> <span className="num" style={{ color: 'var(--fg-1)', fontSize: 14 }}>{gameId.toUpperCase()}</span>
            </h2>
            <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2 }}>当前 {rooms.length} 个房间在线 · {rooms.reduce((s, r) => s + r.taken, 0)} 名玩家</div>
          </div>
          <BtnL variant="ghost" size="sm" icon={<Lu name="arrow-up-down" size={13} />} onClick={() => stub('排序')}><span className="cjk">排序</span></BtnL>
          <BtnL variant="ghost" size="sm" icon={<Lu name="filter" size={13} />} onClick={() => stub('筛选')}><span className="cjk">筛选</span></BtnL>
          <BtnL variant="primary" size="sm" icon={<Lu name="plus" size={13} />} onClick={() => stub('新房间')}><span className="cjk">新房间</span></BtnL>
        </div>

        <div style={{ flex: 1, overflowY: 'auto', padding: 14, display: 'flex', flexDirection: 'column', gap: 10 }}>
          {/* Room list */}
          {rooms.map((r, i) => <RoomRow key={r.id} r={r} active={r.id === 1} index={i} onClick={() => nav({ name: 'room', id: r.id })} />)}
        </div>
      </main>

      {/* Col 4 — Chat */}
      <aside style={{ width: 320, background: 'var(--bg-0)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
        <div style={{ padding: '0 14px', borderBottom: '1px solid var(--border)' }}>
          <TabsL
            tabs={[
              { id: 'lobby',  label: <span className="cjk">大厅</span> },
              { id: 'fr',     label: <span className="cjk">好友</span>, dot: true },
              { id: 'room',   label: <span className="cjk">房间</span> },
            ]}
            active="lobby" onChange={() => {}}
          />
        </div>
        <div style={{ padding: '10px 14px', borderBottom: '1px solid var(--border)' }}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
            <span style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--fg-0)' }}># lobby-{gameId}</span>
            <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>47 online</span>
          </div>
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 12 }}>
          {chat.map((m, i) => {
            const prev = chat[i-1];
            const samegroup = prev && prev.who === m.who;
            return (
              <div key={i}>
                <CML msg={m} samegroup={samegroup} />
                {m.share ? (
                  <div style={{ marginLeft: 38, marginTop: 6 }}>
                    <SHARED.ServerCardFlat compact {...m.share} onJoin={() => nav({ name: 'room', id: 1 })} />
                  </div>
                ) : null}
              </div>
            );
          })}
          <div className="cjk t-caption" style={{ color: 'var(--fg-3)', textAlign: 'center', padding: '14px 0', borderTop: '1px dashed var(--border)', marginTop: 10 }}>
            现在还没人在玩永夜抄，要不你来开第一桌？
          </div>
        </div>
        <ChatComposer onSend={(text) => onToast && onToast({ tone: 'success', title: '已发送', body: text.slice(0, 40) })} />
      </aside>
    </div>
  );
}

function ChatComposer({ onSend, placeholder = '发个消息到 #闲聊…' }: { onSend?: (text: string) => void; placeholder?: string }) {
  const [text, setText] = useStateL('');
  const send = () => {
    const t = text.trim();
    if (!t) return;
    onSend && onSend(t);
    setText('');
  };
  return (
    <div style={{ padding: 12, borderTop: '1px solid var(--border)' }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: 6,
        background: 'var(--bg-2)', borderRadius: 'var(--r-md)',
        border: '1px solid var(--border-strong)', paddingInline: 10, height: 36,
      }}>
        <input
          className="cjk t-body" placeholder={placeholder}
          value={text} onChange={(e) => setText(e.target.value)}
          onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); } }}
          style={{ flex: 1, background: 'transparent', border: 'none', outline: 'none', color: 'var(--fg-0)' }}
        />
        <button className="btn-pressable" style={{ width: 24, height: 24, border: 'none', background: 'transparent', color: 'var(--fg-2)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="smile" size={14} /></button>
        <button className="btn-pressable" onClick={send} style={{ width: 26, height: 26, border: 'none', background: 'var(--accent)', color: 'var(--bg-0)', borderRadius: 6, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="send-horizontal" size={13} /></button>
      </div>
    </div>
  );
}

export { Lobby };
