
// Generated by Claude Design (Opus 4.7) v0.7 — Lobby page.
// Every control on this page either does the thing it looks like it does, or
// says on its face that the backend cannot do it yet.

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { useRooms, useLobbyFriends, useLobbyChat, useMe } from '@/hooks';
import { useBackendReachable, BackendBanner } from '@/components/backend-status';
import { ChatComposer, sendFailureToast } from '@/components/chat-composer';
import { Unavailable } from '@/components/unavailable';
import { resolveSharedRoom, SHARED_ROOM_MISSING } from '@/lib/room-share';
import type { ChatMsg, Friend, GameId, Room, RoomKind } from '@/lib/api/types';
import type { NavTarget } from '@/router';
import type { StaggerStyle } from '@/components/design/shared';

const { useState: useStateL, useMemo: useMemoL, useEffect: useEffectL, useRef: useRefL } = React;
const { Button: BtnL, Avatar: AvL, Input: InpL } = UI;
const { ServerRail: RailL, Row: RowL, SectionLabel: SLL, Tabs: TabsL, IdentityCard: IdL, StatusDot: SDL, ChatMessage: CML } = SHARED;


/**
 * The title for each supported game.
 *
 * The heading used to be a literal 永夜抄 next to `{gameId.toUpperCase()}`,
 * so picking TH06 from the 版本 row rendered "永夜抄 · TH06" — a game title
 * for a different game than the one the id names. The id is what the room
 * list was actually filtered by, so the title has to come from it.
 */
const GAME_TITLES: Record<GameId, string> = {
  th06: '红魔乡',
  th07: '妖妖梦',
  th08: '永夜抄',
  th09: '弹幕天童',
};

/** What the three sort buttons order by. All three use fields the API returns. */
type SortKey = 'ping' | 'players' | 'region';
type KindFilter = 'all' | RoomKind;

const SORTS: { id: SortKey; label: string }[] = [
  { id: 'ping', label: '延迟最低' },
  { id: 'players', label: '人数最多' },
  { id: 'region', label: '按区域' },
];

const KIND_FILTERS: { id: KindFilter; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: 'Official', label: '官方房间' },
  { id: 'Personal', label: '个人房间' },
];

/** What a room that has never been listed would need from the server. */
const CREATE_ROOM_MISSING =
  '开房间需要 POST /v1/rooms。服务端目前只有 GET /v1/rooms、/v1/rooms/{id}、/seats、/spectators、/chat，没有任何创建接口。';

function RoomRow({ r, index = 0, onClick }: { r: Room; index?: number; onClick?: () => void }) {
  const [hov, setHov] = useStateL(false);
  return (
    <div
      onMouseEnter={() => setHov(true)} onMouseLeave={() => setHov(false)}
      onClick={onClick}
      className="anim-row-in"
      style={{
        display: 'flex', alignItems: 'center', gap: 12,
        padding: '12px 14px',
        background: hov ? 'var(--hover)' : 'var(--bg-1)',
        border: '1px solid',
        borderColor: hov ? 'var(--border-strong)' : 'var(--border)',
        borderRadius: 'var(--r-md)',
        cursor: 'pointer',
        transform: hov ? 'translateX(2px)' : 'translateX(0)',
        transition: 'background var(--duration-fast) var(--ease-out-quart), border-color var(--duration-fast) var(--ease-out-quart), transform var(--duration-fast) var(--ease-out-quart)',
        '--i': index,
      } as StaggerStyle}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
          <span className="t-tag" style={{ color: 'var(--fg-2)', padding: '1px 6px', border: '1px solid var(--border)', borderRadius: 4 }}>{r.kind === 'Official' ? '官方' : '个人'}</span>
          <span className="cjk t-body-lg" style={{ color: 'var(--fg-0)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{r.title}</span>
        </div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          <span><span style={{ color: 'var(--fg-1)' }}>主</span> {r.host}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span>
          <span className="num">{r.ping}ms</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span><span>{r.region}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span><span>{r.diff}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span><span>{r.mode}</span>
        </div>
      </div>
      <div style={{ display: 'flex', alignItems: 'center' }}>
        {/* Occupancy pips. The 幽/妖/咲/魔/灵/蕾 glyphs this used to draw were
            invented occupants standing in for real players; the room list
            carries no roster, only a count, so a count is what is drawn. */}
        {Array.from({ length: Math.max(0, Math.min(r.taken, 4)) }).map((_, i) => (
          <span key={i} style={{
            width: 22, height: 22, borderRadius: '50%',
            background: 'var(--bg-2)', border: '2px solid var(--bg-1)',
            marginLeft: i === 0 ? 0 : -6,
          }} />
        ))}
        {Array.from({ length: Math.max(0, Math.min(r.total - r.taken, 4)) }).map((_, i) => (
          <span key={`e${i}`} style={{
            width: 22, height: 22, borderRadius: '50%',
            background: 'transparent', border: '1px dashed var(--border-strong)',
            marginLeft: -6,
          }} />
        ))}
        <span className="num" style={{ marginLeft: 8, fontSize: 11, color: 'var(--fg-2)' }}>{r.taken}/{r.total}</span>
      </div>
    </div>
  );
}

type LobbyProps = {
  theme?: 'dark' | 'light';
  gameId?: 'th06' | 'th07' | 'th08' | 'th09';
  onNavigate?: (target: NavTarget) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function Lobby({ theme = 'dark', gameId = 'th08', onNavigate, onToast }: LobbyProps) {
  const { data: rooms = [] } = useRooms(gameId);
  // The client resolves a failed collection to [], so an empty room list is
  // ambiguous on its own; the probe is what lets the empty state say which.
  const roomsFailed = useBackendReachable() === 'down';
  const { data: friends = [] } = useLobbyFriends();
  const { data: chat = [] } = useLobbyChat(gameId);
  const { data: me } = useMe();
  // The three tabs in the right column were rendered with active="lobby" and
  // onChange={() => {}}: three buttons that did nothing at all. All three views
  // are already loaded here, so they switch.
  const [tab, setTab] = useStateL('lobby');
  // 排序 / 筛选 toasted "该功能将在 V1 后期开放". Both are pure functions of the
  // rooms the page already has — every field they order or filter on is in the
  // Room record — so they are real now, and they are what the header count
  const [query, setQuery] = useStateL('');
  const [sort, setSort] = useStateL<SortKey>('ping');
  const [kind, setKind] = useStateL<KindFilter>('all');
  const searchRef = useRefL<HTMLInputElement>(null);

  const q = query.trim().toLowerCase();
  const visibleRooms = useMemoL(() => {
    const filtered = rooms
      .filter((r) => kind === 'all' || r.kind === kind)
      .filter((r) => !q || r.title.toLowerCase().includes(q) || r.host.toLowerCase().includes(q) || r.region.toLowerCase().includes(q));
    const sorted = [...filtered];
    if (sort === 'ping') sorted.sort((a, b) => a.ping - b.ping);
    else if (sort === 'players') sorted.sort((a, b) => b.taken - a.taken || a.ping - b.ping);
    else sorted.sort((a, b) => a.region.localeCompare(b.region) || a.ping - b.ping);
    return sorted;
  }, [rooms, kind, sort, q]);

  // The "⌘K" badge on the search field advertised a shortcut that had no
  // handler anywhere in the app. Now it has one.
  useEffectL(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        searchRef.current?.focus();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  const nav = (t: NavTarget) => onNavigate && onNavigate(t);
  const joinShare = (share: NonNullable<ChatMsg['share']>) => {
    const target = resolveSharedRoom(share, rooms);
    if (target) nav({ name: 'room', id: target.id });
    else onToast?.({ tone: 'warn', title: '这张分享卡指向的房间不在列表里', body: SHARED_ROOM_MISSING });
  };

  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)', position: 'relative' }}>
      <BackendBanner />
      <RailL active={gameId} onPick={(id: string) => {
        if (id === 'home') nav({ name: 'lobby', gameId: 'th08' });
        else if (id === 'settings') nav({ name: 'settings' });
        else nav({ name: 'lobby', gameId: id });
      }} />
      {/* Col 2 — Lobby navigator */}
      <aside className="thp-col-nav" style={{ width: 256, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: 14, borderBottom: '1px solid var(--border)' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div className="cjk h-display-sm" style={{ color: 'var(--fg-0)' }}>大厅</div>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 10.5, color: 'var(--fg-2)' }}>
              {/* "CN-East · 24ms" was a literal, next to a header that reported
                  the real region and ping of a real room. The client is not
                  connected to a lobby host, so there is nothing to report. */}
              <SDL status={roomsFailed ? 'idle' : 'online'} /> {roomsFailed ? '未连接' : '已连接'}
            </span>
          </div>
          <div style={{ marginTop: 10 }}>
            <span style={{ display: 'block' }}>
              <InpL
                leading={<Lu name="search" size={14} />}
                inputRef={searchRef}
                placeholder="搜索房间 · 玩家 · 频道"
                kbd="⌘K"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
              />
            </span>
          </div>
        </div>
        <div style={{ padding: 10, overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div>
            <SLL>分类</SLL>
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 1 }}>
              {KIND_FILTERS.map((k) => (
                <RowL
                  key={k.id}
                  active={kind === k.id}
                  leading={<Lu name={k.id === 'all' ? 'globe' : k.id === 'Official' ? 'globe' : 'user'} size={14} />}
                  onClick={() => setKind(k.id)}
                >
                  <span className="cjk t-body" style={{ fontWeight: kind === k.id ? 600 : 500, color: kind === k.id ? 'var(--fg-0)' : undefined }}>
                    {k.label}
                  </span>
                </RowL>
              ))}
              {/* Was dimmed with no handler and no explanation. There is no
                  community-channel route at all, so it is unavailable. */}
              <RowL
                disabledReason="社区频道需要 GET /v1/channels 一类的频道目录；服务端只提供群组自己的频道列表。"
                leading={<Lu name="users" size={14} />}
                trailing={<Lu name="lock" size={11} color="var(--fg-3)" />}
              >
                <span className="cjk t-body">社区频道</span>
              </RowL>
            </div>
          </div>
          <div>
            <SLL>版本</SLL>
            <div style={{ marginTop: 6, display: 'flex', gap: 4, flexWrap: 'wrap' }}>
              {['TH06', 'TH07', 'TH08', 'TH09'].map((v) => {
                const id = v.toLowerCase() as 'th06' | 'th07' | 'th08' | 'th09';
                const on = id === gameId;
                return (
                  <button key={v} className="num btn-pressable" onClick={() => nav({ name: 'lobby', gameId: id })} style={{
                    height: 24, paddingInline: 8, display: 'inline-flex', alignItems: 'center',
                    borderRadius: 6, fontSize: 11, fontWeight: 600, cursor: 'pointer',
                    background: on ? 'var(--bg-3)' : 'var(--bg-2)',
                    color: on ? 'var(--fg-0)' : 'var(--fg-2)',
                    border: `1px solid ${on ? 'var(--border-strong)' : 'var(--border)'}`,
                  }}>{v}</button>
                );
              })}
            </div>
          </div>
          <div>
            {/*
              "我的房间" listed two hardcoded rooms ("昨日的房间 #1 · TH08 · 3 人"
              and "咲夜的茶话会 #2 · TH07 · 待机中"), neither of which any request
              produced, and the section claimed to be about rooms belonging to
              the viewer — for whom there is no route. It is now 最近房间, and it
              is the same list the middle column shows.
            */}
            <SLL right={<span className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)' }}>{rooms.length}</span>}>最近房间</SLL>
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 1 }}>
              {rooms.length === 0 ? (
                <div className="cjk t-caption" style={{ color: 'var(--fg-3)', padding: '6px 8px' }}>
                  {roomsFailed ? '连不上服务器，读不到房间列表。' : '这个版本暂时没有开着的房间。'}
                </div>
              ) : rooms.slice(0, 4).map((r) => (
                <RowL key={r.id} onClick={() => nav({ name: 'room', id: r.id })}
                  leading={<span style={{ width: 6, height: 6, borderRadius: '50%', background: r.taken >= r.total ? 'var(--fg-3)' : 'var(--status-online)' }} />}>
                  <span className="cjk t-body" style={{ color: 'var(--fg-0)' }}>{r.title}</span>
                  <div className="t-caption num" style={{ color: 'var(--fg-2)' }}>{r.gameId.toUpperCase()} · {r.taken}/{r.total}</div>
                </RowL>
              ))}
            </div>
          </div>
          <div>
            <SLL right={<span className="num" style={{ fontSize: 10.5, color: 'var(--status-online)' }}>{friends.filter((f) => f.status === 'online').length}</span>}>好友在线</SLL>
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 1 }}>
              {friends.length === 0 ? (
                <div className="cjk t-caption" style={{ color: 'var(--fg-3)', padding: '6px 8px' }}>
                  {roomsFailed ? '连不上服务器。' : '服务端还没有返回任何在线好友。'}
                </div>
              ) : friends.map((f) => (
                <RowL key={f.handle} onClick={() => nav({ name: 'dm', view: 'dm', peer: f.handle })}
                  leading={<AvL size={22} name={f.name} status={f.status} />}>
                  <div className="cjk t-body" style={{ color: 'var(--fg-0)', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{f.name}</div>
                  <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{f.game}</div>
                </RowL>
              ))}
            </div>
          </div>
        </div>
        <IdL me={me ?? null} onSettings={() => nav({ name: 'settings' })} onProfile={() => nav({ name: 'profile' })} />
      </aside>

      {/* Col 3 — Rooms list */}
      <main className="thp-col-main" style={{ display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border)' }}>
        <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <div style={{ flex: 1, minWidth: 180 }}>
            <h2 className="cjk h-display-md" style={{ margin: 0 }}>
              {GAME_TITLES[gameId]} <span style={{ color: 'var(--fg-2)' }}>·</span> <span className="num" style={{ color: 'var(--fg-1)', fontSize: 14 }}>{gameId.toUpperCase()}</span>
            </h2>
            <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2 }}>
              {q || kind !== 'all'
                ? `${visibleRooms.length} / ${rooms.length} 个房间符合条件 · ${visibleRooms.reduce((s, r) => s + r.taken, 0)} 名玩家`
                : `当前 ${rooms.length} 个房间在线 · ${rooms.reduce((s, r) => s + r.taken, 0)} 名玩家`}
            </div>
          </div>
          <div style={{ display: 'inline-flex', gap: 2, padding: 2, background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 6 }}>
            {SORTS.map((s) => (
              <button
                key={s.id}
                aria-pressed={sort === s.id}
                title={`按${s.label}排序`}
                onClick={() => setSort(s.id)}
                className="cjk btn-pressable"
                style={{
                  height: 22, paddingInline: 8, borderRadius: 4, border: 'none',
                  background: sort === s.id ? 'var(--bg-1)' : 'transparent',
                  color: sort === s.id ? 'var(--fg-0)' : 'var(--fg-2)',
                  fontSize: 11, fontWeight: 600, cursor: 'pointer',
                }}
              >{s.label}</button>
            ))}
          </div>
          <div style={{ display: 'inline-flex', gap: 2, padding: 2, background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 6 }}>
            {KIND_FILTERS.map((k) => (
              <button
                key={k.id}
                aria-pressed={kind === k.id}
                title={`只看${k.label}`}
                onClick={() => setKind(k.id)}
                className="cjk btn-pressable"
                style={{
                  height: 22, paddingInline: 8, borderRadius: 4, border: 'none',
                  background: kind === k.id ? 'var(--bg-1)' : 'transparent',
                  color: kind === k.id ? 'var(--fg-0)' : 'var(--fg-2)',
                  fontSize: 11, fontWeight: 600, cursor: 'pointer',
                }}
              >{k.label}</button>
            ))}
          </div>
          <Unavailable reason={CREATE_ROOM_MISSING}>
            <BtnL variant="primary" size="sm" disabled icon={<Lu name="plus" size={13} />}><span className="cjk">新房间</span></BtnL>
          </Unavailable>
        </div>

        <div style={{ flex: 1, overflowY: 'auto', padding: 14, display: 'flex', flexDirection: 'column', gap: 10 }}>
          {visibleRooms.length === 0 ? (
            <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <UI.EmptyState
                icon={q || kind !== 'all' ? 'search' : 'door-open'}
                title={q || kind !== 'all' ? '没有符合条件的房间' : roomsFailed ? '读不到房间列表' : '现在没有开放的房间'}
                body={
                  q || kind !== 'all'
                    ? `「${query || KIND_FILTERS.find((k) => k.id === kind)?.label}」没有匹配到房间。清掉搜索词或切回「全部」就能看到 ${rooms.length} 间。`
                    : roomsFailed
                      ? '请确认服务端已启动，然后重试。'
                      : '这个版本暂时没人开桌。'
                }
                action={
                  q || kind !== 'all' ? (
                    <BtnL variant="secondary" size="md" onClick={() => { setQuery(''); setKind('all'); }}>
                      <span className="cjk">清除条件</span>
                    </BtnL>
                  ) : (
                    <Unavailable reason={CREATE_ROOM_MISSING}>
                      <BtnL variant="primary" size="md" disabled>
                        <Lu name="plus" size={12} />
                        <span className="cjk" style={{ marginLeft: 6 }}>开一间</span>
                      </BtnL>
                    </Unavailable>
                  )
                }
              />
            </div>
          ) : visibleRooms.map((r, i) => <RoomRow key={r.id} r={r} index={i} onClick={() => nav({ name: 'room', id: r.id })} />)}
        </div>
      </main>

      {/* Col 4 — Chat */}
      <aside className="thp-col-aside" style={{ width: 320, background: 'var(--bg-0)', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '0 14px', borderBottom: '1px solid var(--border)' }}>
          <TabsL
            tabs={[
              { id: 'lobby', label: <span className="cjk">大厅</span> },
              { id: 'fr',    label: <span className="cjk">好友</span>, dot: friends.some((f) => f.status !== 'offline') },
              { id: 'room',  label: <span className="cjk">房间</span> },
            ]}
            active={tab}
            onChange={setTab}
          />
        </div>
        {tab === 'lobby' ? (
          <>
            <div style={{ padding: '10px 14px', borderBottom: '1px solid var(--border)' }}>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                <span style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--fg-0)' }}># lobby-{gameId}</span>
                {/* Was a literal "47 online" — a number no request produced, and
                    it contradicted the header two columns over. Counted from the
                    roster instead. */}
                <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>
                  {friends.filter((f) => f.status !== 'offline').length} 在线好友
                </span>
              </div>
            </div>
            <div style={{ flex: 1, overflowY: 'auto', padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 12 }}>
              {chat.length === 0 ? (
                <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <UI.EmptyState
                    icon="message-square"
                    title={roomsFailed ? '读不到聊天记录' : '还没有人说话'}
                    body={roomsFailed
                      ? '连不上服务器，消息可能已经在路上了。'
                      : '现在还没人在这个大厅说话。'}
                  />
                </div>
              ) : chat.map((m, i) => {
                const prev = chat[i - 1];
                const samegroup = prev && prev.who === m.who;
                return (
                  <div key={i}>
                    <CML msg={m} samegroup={samegroup} />
                    {m.share ? (
                      <div style={{ marginLeft: 38, marginTop: 6 }}>
                        <SHARED.ServerCardFlat compact {...m.share} onJoin={() => joinShare(m.share!)} />
                      </div>
                    ) : null}
                  </div>
                );
              })}
            </div>
            <ChatComposer
              channelId={`lobby-${gameId}`}
              placeholder={`发个消息到 #lobby-${gameId}`}
              onSent={() => onToast?.({ tone: 'success', title: '已发送', body: `#lobby-${gameId}` })}
              onFailed={(_c, error) => onToast?.(sendFailureToast(error))}
            />
          </>
        ) : tab === 'fr' ? (
          <LobbyFriendList friends={friends} failed={roomsFailed} onOpen={(handle) => nav({ name: 'dm', view: 'dm', peer: handle })} />
        ) : (
          <LobbyRoomList rooms={visibleRooms} total={rooms.length} failed={roomsFailed} onOpen={(id) => nav({ name: 'room', id })} />
        )}
      </aside>
    </div>
  );
}

/**
 * 好友 tab of the lobby side column. Same roster the left column shows, in a
 * panel that fits 320px, and clicking a row opens the real DM thread.
 */
function LobbyFriendList({ friends, failed, onOpen }: {
  friends: Friend[];
  failed: boolean;
  onOpen: (handle: string) => void;
}) {
  if (friends.length === 0) {
    return (
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <UI.EmptyState
          icon={failed ? 'unplug' : 'user-x'}
          title={failed ? '读不到好友列表' : '还没有好友'}
          body={failed ? '连不上服务器，好友列表可能已经在路上了。' : '服务端还没有返回任何好友。'}
        />
      </div>
    );
  }
  return (
    <div style={{ flex: 1, overflowY: 'auto', padding: 8 }}>
      {friends.map((f) => (
        <RowL key={f.handle} onClick={() => onOpen(f.handle)} leading={<AvL size={26} name={f.name} status={f.status} />}>
          <div className="cjk t-body" style={{ color: 'var(--fg-0)', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{f.name}</div>
          <div className="t-caption num" style={{ color: 'var(--fg-3)' }}>@{f.handle}</div>
        </RowL>
      ))}
    </div>
  );
}

/**
 * 房间 tab of the lobby side column. It shows the same list the middle column
 * shows, after the same sort and filter, and the one action that would create a
 * room is unavailable because the server has no route for it.
 */
function LobbyRoomList({ rooms, total, failed, onOpen }: {
  rooms: Room[];
  total: number;
  failed: boolean;
  onOpen: (id: number) => void;
}) {
  return (
    <>
      <div style={{ flex: 1, overflowY: 'auto', padding: 8 }}>
        {rooms.length === 0 ? (
          <UI.EmptyState
            icon={failed ? 'unplug' : 'door-open'}
            title={failed ? '读不到房间列表' : '没有符合条件的房间'}
            body={failed ? '连不上服务器，请确认服务端已启动。' : `筛选之后 ${total} 间房里没有匹配的。`}
          />
        ) : rooms.map((r) => (
          <RowL key={r.id} onClick={() => onOpen(r.id)} trailing={<span className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>{r.taken}/{r.total}</span>}>
            <div className="cjk t-body" style={{ color: 'var(--fg-0)', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</div>
            <div className="t-caption" style={{ color: 'var(--fg-2)' }}>主 {r.host} · {r.ping}ms</div>
          </RowL>
        ))}
      </div>
      <div style={{ padding: 12, borderTop: '1px solid var(--border)' }}>
        <Unavailable block reason={CREATE_ROOM_MISSING}>
          <BtnL variant="primary" size="sm" style={{ width: '100%' }} disabled>
            <Lu name="plus" size={13} />
            <span className="cjk" style={{ marginLeft: 6 }}>开一间</span>
          </BtnL>
        </Unavailable>
      </div>
    </>
  );
}

export { Lobby };
