// TH-Platform Lobby — 4-column Discord-style layout.
// Soft, friendly, no metallic / cinematic / tactical.
// Generated by Claude Design from spec, hand-converted to TS.

import { useState, type ReactNode } from 'react';
import { Avatar, Badge, Button, Card, Icon, Input } from '@/components/design/ui';

type Game = {
  id: string;
  code: string;
  name: string;
  short: string;
  grad: string;
};

type RoomKind = 'Official' | 'Personal';

type Room = {
  id: number;
  kind: RoomKind;
  title: string;
  host: string;
  region: string;
  ping: number;
  diff: string;
  mode: string;
  lives: number;
  seats: number;
  taken: number;
  grad: string;
};

type FriendStatus = 'online' | 'away' | 'dnd' | 'offline';

type Friend = {
  name: string;
  handle: string;
  status: FriendStatus;
  game: string;
};

type ChatLine = {
  who: string;
  handle: string;
  t: string;
  msg: string;
  mention?: string | false;
  share?: number;
};

// ---------- Mock data ----------
const GAMES: Game[] = [
  { id: 'th06', code: 'TH06', name: '红魔乡', short: 'EoSD', grad: 'var(--grad-rose)' },
  { id: 'th07', code: 'TH07', name: '妖妖梦', short: 'PCB', grad: 'var(--grad-mint)' },
  { id: 'th08', code: 'TH08', name: '永夜抄', short: 'IN', grad: 'var(--grad-violet)' },
  { id: 'th09', code: 'TH09', name: '花映塚', short: 'PoFV', grad: 'var(--grad-amber)' },
];

const ROOMS: Room[] = [
  { id: 1, kind: 'Official', title: '永夜抄 PvP — 北京', host: '幽幽子',   region: 'CN-East',  ping: 24, diff: 'Lunatic', mode: 'Standard', lives: 3, seats: 4, taken: 3, grad: 'var(--grad-violet)' },
  { id: 2, kind: 'Personal', title: '老咸鱼下午茶',         host: '咲夜',     region: 'CN-East',  ping: 31, diff: 'Hard',    mode: 'Standard', lives: 4, seats: 4, taken: 2, grad: 'var(--grad-teal)' },
  { id: 3, kind: 'Official', title: 'IN 周末锦标赛 #14',    host: '灵梦',     region: 'CN-South', ping: 42, diff: 'Lunatic', mode: 'Ranked',   lives: 3, seats: 4, taken: 4, grad: 'var(--grad-amber)' },
  { id: 4, kind: 'Personal', title: '萌新练习房 · 慢慢打',   host: '魔理沙',   region: 'CN-East',  ping: 19, diff: 'Normal',  mode: 'Casual',   lives: 5, seats: 4, taken: 1, grad: 'var(--grad-mint)' },
  { id: 5, kind: 'Official', title: 'Spell Card Showdown',  host: '妖梦',     region: 'JP-Tokyo', ping: 88, diff: 'Lunatic', mode: 'Spell',    lives: 1, seats: 4, taken: 2, grad: 'var(--grad-dusk)' },
  { id: 6, kind: 'Personal', title: '深夜不困局 · 03:00',    host: '蕾米莉亚', region: 'CN-East',  ping: 27, diff: 'Hard',    mode: 'Standard', lives: 3, seats: 4, taken: 3, grad: 'var(--grad-rose)' },
];

const MY_ROOMS = [
  { name: '昨日的房间', sub: 'TH08 · 3 人' },
  { name: '咲夜的茶话会', sub: 'TH07 · 待机中' },
];

const FRIENDS: Friend[] = [
  { name: '小野塚小町', handle: 'komachi', status: 'online', game: 'TH09 中' },
  { name: '河城荷取',   handle: 'nitori',  status: 'online', game: 'TH08 中' },
  { name: '雾雨魔理沙', handle: 'marisa',  status: 'away',   game: '挂机' },
  { name: '十六夜咲夜', handle: 'sakuya',  status: 'online', game: 'TH06 中' },
  { name: '博丽灵梦',   handle: 'reimu',   status: 'dnd',    game: '勿扰' },
];

const CHAT: ChatLine[] = [
  { who: '河城荷取',   handle: 'nitori',  t: '21:04', msg: '今晚有人上分吗，本命永夜抄' },
  { who: '小野塚小町', handle: 'komachi', t: '21:05', msg: '刚下班，等我十分钟' },
  { who: '十六夜咲夜', handle: 'sakuya',  t: '21:07', msg: '@nitori 我开了一桌，进来吧', mention: 'nitori', share: 1 },
  { who: '雾雨魔理沙', handle: 'marisa',  t: '21:09', msg: '稳，先来一把试试手感' },
  { who: '河城荷取',   handle: 'nitori',  t: '21:10', msg: '好嘞，路上' },
];

// ---------- Tiny pieces ----------
function GameTile({ g, active, onClick }: { g: Game; active: boolean; onClick: () => void }) {
  return (
    <div style={{ position: 'relative', display: 'flex', justifyContent: 'center' }}>
      <span
        style={{
          position: 'absolute',
          left: -10,
          top: '50%',
          transform: 'translateY(-50%)',
          width: 4,
          height: active ? 28 : 0,
          background: 'var(--fg-0)',
          borderRadius: 999,
          transition: 'height .2s ease',
        }}
      />
      <button
        onClick={onClick}
        title={`${g.code} · ${g.name}`}
        style={{
          width: 48,
          height: 48,
          borderRadius: active ? 14 : 24,
          background: g.grad,
          color: '#fff',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontFamily: 'var(--font-thp-display)',
          fontWeight: 800,
          fontSize: 13,
          letterSpacing: '0.02em',
          cursor: 'pointer',
          border: 'none',
          padding: 0,
          boxShadow: active ? '0 4px 14px rgba(0,0,0,0.18)' : 'var(--shadow-sm)',
          transition: 'border-radius .18s ease, transform .18s ease',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.borderRadius = '14px';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.borderRadius = active ? '14px' : '24px';
        }}
      >
        {g.code}
      </button>
    </div>
  );
}

function PlainTile({
  children,
  label,
  active,
  onClick,
  color,
}: {
  children: ReactNode;
  label: string;
  active?: boolean;
  onClick?: () => void;
  color?: string;
}) {
  return (
    <div style={{ position: 'relative', display: 'flex', justifyContent: 'center' }}>
      <span
        style={{
          position: 'absolute',
          left: -10,
          top: '50%',
          transform: 'translateY(-50%)',
          width: 4,
          height: active ? 28 : 0,
          background: 'var(--fg-0)',
          borderRadius: 999,
        }}
      />
      <button
        onClick={onClick}
        title={label}
        style={{
          width: 48,
          height: 48,
          borderRadius: active ? 14 : 24,
          background: 'var(--bg-2)',
          color: color || 'var(--fg-1)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer',
          border: '1px solid var(--border)',
          padding: 0,
          transition: 'border-radius .18s ease, color .18s, background .18s',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.borderRadius = '14px';
          e.currentTarget.style.color = 'var(--brand)';
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.borderRadius = active ? '14px' : '24px';
          e.currentTarget.style.color = color || 'var(--fg-1)';
        }}
      >
        {children}
      </button>
    </div>
  );
}

function Chip({
  active,
  locked,
  children,
  onClick,
  tooltip,
}: {
  active?: boolean;
  locked?: boolean;
  children: ReactNode;
  onClick?: () => void;
  tooltip?: string;
}) {
  return (
    <button
      onClick={onClick}
      title={tooltip}
      style={{
        height: 28,
        paddingInline: 11,
        gap: 6,
        display: 'inline-flex',
        alignItems: 'center',
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-thp-sans)',
        background: active ? 'var(--brand-soft)' : 'transparent',
        color: active ? 'var(--brand)' : locked ? 'var(--fg-3)' : 'var(--fg-1)',
        border: `1px solid ${active ? 'transparent' : 'var(--border-strong)'}`,
        cursor: locked ? 'help' : 'pointer',
        opacity: locked ? 0.7 : 1,
      }}
    >
      {locked ? <span style={{ display: 'inline-flex' }}>{Icon.lock}</span> : null}
      {children}
    </button>
  );
}

function VersionPill({
  active,
  dim,
  children,
}: {
  active?: boolean;
  dim?: boolean;
  children: ReactNode;
}) {
  return (
    <span
      style={{
        height: 24,
        paddingInline: 10,
        display: 'inline-flex',
        alignItems: 'center',
        borderRadius: 999,
        fontSize: 11.5,
        fontWeight: 700,
        letterSpacing: '0.02em',
        cursor: 'pointer',
        fontFamily: 'var(--font-thp-sans)',
        background: active ? 'var(--brand)' : 'var(--bg-2)',
        color: active ? '#fff' : dim ? 'var(--fg-3)' : 'var(--fg-1)',
        border: active ? 'none' : '1px solid var(--border)',
        opacity: dim ? 0.6 : 1,
      }}
    >
      {children}
    </span>
  );
}

function CardCover({ grad, kind }: { grad: string; kind: RoomKind }) {
  return (
    <div
      style={{
        position: 'relative',
        aspectRatio: '16 / 9',
        borderRadius: 'var(--r-md)',
        background: grad,
        overflow: 'hidden',
      }}
    >
      <div
        style={{
          position: 'absolute',
          inset: 0,
          background:
            'radial-gradient(60% 50% at 80% 20%, rgba(255,255,255,0.28) 0%, transparent 60%), radial-gradient(50% 50% at 15% 85%, rgba(255,255,255,0.16) 0%, transparent 60%)',
        }}
      />
      <span
        style={{
          position: 'absolute',
          top: 10,
          left: 10,
          height: 22,
          paddingInline: 9,
          display: 'inline-flex',
          alignItems: 'center',
          gap: 5,
          borderRadius: 999,
          background: 'rgba(0,0,0,0.28)',
          color: '#fff',
          backdropFilter: 'blur(8px)',
          WebkitBackdropFilter: 'blur(8px)',
          fontSize: 10.5,
          fontWeight: 700,
          letterSpacing: '0.02em',
        }}
      >
        <span
          style={{
            width: 5,
            height: 5,
            borderRadius: '50%',
            background: kind === 'Official' ? '#4ADE80' : '#F5B544',
          }}
        />
        {kind}
      </span>
    </div>
  );
}

function PlayerSeats({ taken, total }: { taken: number; total: number }) {
  const palette = [
    'var(--grad-violet)',
    'var(--grad-teal)',
    'var(--grad-amber)',
    'var(--grad-mint)',
  ];
  return (
    <div style={{ display: 'flex', gap: 6 }}>
      {Array.from({ length: total }).map((_, i) => {
        const filled = i < taken;
        return (
          <span key={i} style={{ position: 'relative' }}>
            <span
              style={{
                width: 26,
                height: 26,
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                background: filled ? palette[i % palette.length] : 'var(--bg-2)',
                border: filled
                  ? '2px solid var(--bg-1)'
                  : '1.5px dashed var(--border-strong)',
                boxSizing: 'border-box',
                color: '#fff',
                fontSize: 10,
                fontWeight: 700,
              }}
            >
              {!filled && <span style={{ color: 'var(--fg-3)' }}>+</span>}
            </span>
            {filled && i === 0 ? (
              <span
                style={{
                  position: 'absolute',
                  top: -3,
                  right: -3,
                  width: 14,
                  height: 14,
                  borderRadius: '50%',
                  background: 'var(--warning)',
                  color: '#1A1B22',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  border: '1.5px solid var(--bg-1)',
                }}
              >
                {Icon.crown}
              </span>
            ) : null}
          </span>
        );
      })}
    </div>
  );
}

function RoomCard({ r, onJoin }: { r: Room; onJoin?: () => void }) {
  const full = r.taken >= r.seats;
  return (
    <Card padded={false} hover style={{ display: 'flex', flexDirection: 'column' }}>
      <div style={{ padding: 10 }}>
        <CardCover grad={r.grad} kind={r.kind} />
      </div>
      <div
        style={{
          padding: '4px 14px 14px 14px',
          display: 'flex',
          flexDirection: 'column',
          gap: 10,
        }}
      >
        <div>
          <div
            className="cjk"
            style={{
              fontSize: 16,
              fontWeight: 700,
              color: 'var(--fg-0)',
              letterSpacing: '-0.005em',
              lineHeight: 1.25,
            }}
          >
            {r.title}
          </div>
          <div
            style={{
              fontSize: 12,
              color: 'var(--fg-2)',
              marginTop: 4,
              display: 'flex',
              alignItems: 'center',
              gap: 6,
            }}
          >
            TH08 ·{' '}
            <span
              style={{
                color:
                  r.ping < 40
                    ? 'var(--success)'
                    : r.ping < 70
                      ? 'var(--warning)'
                      : 'var(--danger)',
              }}
            >
              {r.ping}ms
            </span>{' '}
            · {r.region}
          </div>
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
          <Badge tone="brand">{r.diff}</Badge>
          <Badge tone="neutral">{r.mode}</Badge>
          <Badge tone="neutral">{r.lives} lives</Badge>
        </div>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 8,
          }}
        >
          <PlayerSeats taken={r.taken} total={r.seats} />
          <span className="cjk" style={{ fontSize: 11.5, color: 'var(--fg-2)' }}>
            <span style={{ color: 'var(--fg-1)', fontWeight: 600 }}>房主</span> {r.host}
          </span>
        </div>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 10,
            paddingTop: 6,
            borderTop: '1px solid var(--border)',
            marginTop: 2,
          }}
        >
          <span style={{ fontSize: 12, color: 'var(--fg-1)', fontWeight: 600 }}>
            {r.taken}/{r.seats}{' '}
            <span style={{ color: 'var(--fg-2)', fontWeight: 500 }}>seats taken</span>
          </span>
          <Button variant={full ? 'secondary' : 'primary'} size="sm" onClick={onJoin}>
            {full ? 'Watch' : 'Join'}
          </Button>
        </div>
      </div>
    </Card>
  );
}

function MiniShareCard({ r }: { r: Room }) {
  return (
    <div
      style={{
        marginTop: 6,
        borderRadius: 'var(--r-md)',
        border: '1px solid var(--border-strong)',
        background: 'var(--bg-2)',
        overflow: 'hidden',
        maxWidth: 270,
      }}
    >
      <div style={{ padding: 6 }}>
        <div
          style={{
            aspectRatio: '16 / 7',
            borderRadius: 8,
            background: r.grad,
            position: 'relative',
            overflow: 'hidden',
          }}
        >
          <div
            style={{
              position: 'absolute',
              inset: 0,
              background:
                'radial-gradient(60% 50% at 80% 20%, rgba(255,255,255,0.25), transparent 60%)',
            }}
          />
        </div>
      </div>
      <div style={{ padding: '2px 10px 10px' }}>
        <div className="cjk" style={{ fontSize: 13, fontWeight: 700, color: 'var(--fg-0)' }}>
          {r.title}
        </div>
        <div style={{ fontSize: 11.5, color: 'var(--fg-2)', marginTop: 2 }}>
          TH08 · {r.ping}ms · {r.taken}/{r.seats}
        </div>
        <div style={{ marginTop: 8 }}>
          <Button variant="soft" size="sm">
            Join room
          </Button>
        </div>
      </div>
    </div>
  );
}

function SectionLabel({ children, right }: { children: ReactNode; right?: ReactNode }) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
      }}
    >
      <span
        style={{
          fontSize: 10.5,
          fontWeight: 700,
          color: 'var(--fg-2)',
          textTransform: 'uppercase',
          letterSpacing: '0.08em',
        }}
      >
        {children}
      </span>
      {right}
    </div>
  );
}

function NavRow({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        padding: '6px 8px',
        borderRadius: 8,
        cursor: 'pointer',
        transition: 'background .12s',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.background = 'var(--hover)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.background = 'transparent';
      }}
    >
      {children}
    </div>
  );
}

function Col1Rail() {
  const [active, setActive] = useState('th08');
  return (
    <div
      style={{
        width: 72,
        background: 'var(--bg-0)',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        paddingTop: 14,
        paddingBottom: 14,
        gap: 10,
        borderRight: '1px solid var(--border)',
      }}
    >
      <div
        style={{
          width: 44,
          height: 44,
          borderRadius: 14,
          background: 'linear-gradient(135deg, var(--brand) 0%, #4FD1C5 100%)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: '#fff',
          fontWeight: 800,
          fontSize: 18,
          fontFamily: 'var(--font-thp-display)',
          boxShadow: 'var(--shadow-md)',
          letterSpacing: '-0.02em',
        }}
      >
        TH
      </div>
      <div style={{ width: 32, height: 1, background: 'var(--border)', margin: '4px 0' }} />
      {GAMES.map((g) => (
        <GameTile key={g.id} g={g} active={active === g.id} onClick={() => setActive(g.id)} />
      ))}
      <PlainTile label="Add server">
        <span style={{ color: 'var(--success)', fontSize: 22, fontWeight: 300, lineHeight: 1 }}>+</span>
      </PlainTile>
      <div style={{ flex: 1 }} />
      <PlainTile label="Discover">{Icon.compass}</PlainTile>
      <PlainTile label="Settings">{Icon.cog}</PlainTile>
    </div>
  );
}

function Col2Navigator() {
  return (
    <aside
      style={{
        width: 256,
        background: 'var(--bg-1)',
        display: 'flex',
        flexDirection: 'column',
        borderRight: '1px solid var(--border)',
      }}
    >
      <div style={{ padding: '16px 16px 12px', borderBottom: '1px solid var(--border)' }}>
        <div
          style={{
            fontSize: 15,
            fontWeight: 800,
            color: 'var(--fg-0)',
            fontFamily: 'var(--font-thp-display)',
            letterSpacing: '-0.01em',
          }}
        >
          Lobby
        </div>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            marginTop: 4,
            fontSize: 11.5,
            color: 'var(--fg-2)',
          }}
        >
          <span style={{ display: 'inline-flex' }}>{Icon.globe}</span> CN-East ·{' '}
          <span style={{ color: 'var(--success)', fontWeight: 600 }}>24ms</span>
        </div>
      </div>
      <div
        style={{
          padding: 12,
          display: 'flex',
          flexDirection: 'column',
          gap: 14,
          overflowY: 'auto',
          flex: 1,
        }}
      >
        <Input leading={Icon.search} placeholder="Search rooms…" kbd="⌘K" />

        <div>
          <SectionLabel>Server type</SectionLabel>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 8 }}>
            <Chip active>Official</Chip>
            <Chip>Personal</Chip>
            <Chip locked tooltip="Reach Lv.10 to unlock community servers">
              Community
            </Chip>
          </div>
        </div>

        <div>
          <SectionLabel>Game version</SectionLabel>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, marginTop: 8 }}>
            <VersionPill>TH06</VersionPill>
            <VersionPill>TH07</VersionPill>
            <VersionPill active>TH08</VersionPill>
            <VersionPill>TH09</VersionPill>
            <VersionPill dim>TH10–20</VersionPill>
          </div>
        </div>

        <div>
          <SectionLabel
            right={
              <span style={{ fontSize: 10.5, color: 'var(--fg-3)', fontWeight: 600 }}>
                {MY_ROOMS.length}/3
              </span>
            }
          >
            My rooms
          </SectionLabel>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 2, marginTop: 6 }}>
            {MY_ROOMS.map((r, i) => (
              <NavRow key={i}>
                <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--brand)' }} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div
                    className="cjk"
                    style={{
                      fontSize: 12.5,
                      fontWeight: 600,
                      color: 'var(--fg-0)',
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                    }}
                  >
                    {r.name}
                  </div>
                  <div style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>{r.sub}</div>
                </div>
              </NavRow>
            ))}
          </div>
        </div>

        <div>
          <SectionLabel
            right={
              <span style={{ fontSize: 10.5, color: 'var(--success)', fontWeight: 600 }}>
                {FRIENDS.filter((f) => f.status === 'online').length} online
              </span>
            }
          >
            Friends
          </SectionLabel>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 2, marginTop: 6 }}>
            {FRIENDS.map((f, i) => (
              <NavRow key={i}>
                <Avatar size={26} name={f.name} status={f.status} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div
                    className="cjk"
                    style={{
                      fontSize: 12.5,
                      fontWeight: 600,
                      color: 'var(--fg-0)',
                      whiteSpace: 'nowrap',
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                    }}
                  >
                    {f.name}
                  </div>
                  <div className="cjk" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>
                    {f.game}
                  </div>
                </div>
              </NavRow>
            ))}
          </div>
        </div>
      </div>

      <div
        style={{
          padding: 10,
          margin: 10,
          marginTop: 4,
          borderRadius: 'var(--r-md)',
          background: 'var(--bg-2)',
          display: 'flex',
          alignItems: 'center',
          gap: 10,
          border: '1px solid var(--border)',
        }}
      >
        <Avatar size={34} name="霖" status="online" ring={2} ringColor="var(--brand-ring)" />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div
            className="cjk"
            style={{
              fontSize: 13,
              fontWeight: 700,
              color: 'var(--fg-0)',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
            }}
          >
            东方霖之助
          </div>
          <div
            style={{
              fontSize: 10.5,
              color: 'var(--fg-2)',
              fontFamily: 'var(--font-thp-mono)',
            }}
          >
            @rinnosuke · online
          </div>
        </div>
        <button
          style={{
            width: 28,
            height: 28,
            borderRadius: 8,
            border: 'none',
            background: 'transparent',
            color: 'var(--fg-2)',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
          title="Settings"
        >
          {Icon.cog}
        </button>
      </div>
    </aside>
  );
}

function Col3Content() {
  return (
    <main
      style={{
        flex: 1,
        background: 'var(--bg-0)',
        overflowY: 'auto',
        minWidth: 0,
      }}
    >
      <div
        style={{
          padding: '24px 28px 32px',
          display: 'flex',
          flexDirection: 'column',
          gap: 22,
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'flex-end',
            justifyContent: 'space-between',
            gap: 16,
            flexWrap: 'wrap',
          }}
        >
          <div>
            <h1
              className="cjk"
              style={{
                margin: 0,
                fontFamily: 'var(--font-thp-display)',
                fontWeight: 800,
                fontSize: 30,
                letterSpacing: '-0.018em',
                color: 'var(--fg-0)',
                lineHeight: 1.15,
              }}
            >
              Imperishable Night{' '}
              <span style={{ color: 'var(--fg-2)', fontWeight: 500 }}>·</span>{' '}
              <span style={{ color: 'var(--fg-1)' }}>TH08</span>
            </h1>
            <div style={{ marginTop: 6, fontSize: 13, color: 'var(--fg-2)' }}>
              <span style={{ color: 'var(--fg-1)', fontWeight: 600 }}>12</span> active
              rooms ·{' '}
              <span style={{ color: 'var(--fg-1)', fontWeight: 600 }}>47</span> players
              online
            </div>
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <Button variant="ghost" size="md" icon={Icon.sort}>
              Sort: Ping
            </Button>
            <Button variant="secondary" size="md" icon={Icon.filter}>
              Filter
            </Button>
            <Button variant="primary" size="md" icon={Icon.plus}>
              New room
            </Button>
          </div>
        </div>

        <Card
          padded={false}
          style={{
            background: 'var(--featured-grad)',
            border: '1px solid var(--border)',
            padding: '22px 26px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 24,
            flexWrap: 'wrap',
            overflow: 'hidden',
            position: 'relative',
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 18,
              flex: 1,
              minWidth: 280,
            }}
          >
            <div
              style={{
                width: 56,
                height: 56,
                borderRadius: 16,
                background: 'linear-gradient(135deg, var(--brand) 0%, #4FD1C5 100%)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#fff',
                boxShadow: 'var(--shadow-md)',
              }}
            >
              {Icon.bolt}
            </div>
            <div style={{ flex: 1 }}>
              <Badge tone="brand" dot>
                Weekly event
              </Badge>
              <h2
                className="cjk"
                style={{
                  margin: '6px 0 4px',
                  fontSize: 20,
                  fontWeight: 700,
                  color: 'var(--fg-0)',
                  letterSpacing: '-0.01em',
                }}
              >
                Lunatic Friday · 永夜抄锦标赛
              </h2>
              <div
                className="cjk"
                style={{
                  fontSize: 13,
                  color: 'var(--fg-1)',
                  maxWidth: 540,
                  lineHeight: 1.5,
                }}
              >
                每周五晚上 21:00 开赛，胜者拿走整桌的奶茶券。带上妖梦或者咲夜，慢慢来就好。
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <Button variant="secondary" size="md">
              Details
            </Button>
            <Button variant="primary" size="md">
              Sign up
            </Button>
          </div>
        </Card>

        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <h3
            style={{
              margin: 0,
              fontFamily: 'var(--font-thp-display)',
              fontWeight: 700,
              fontSize: 15,
              color: 'var(--fg-0)',
              letterSpacing: '-0.005em',
            }}
          >
            Active rooms
          </h3>
          <span style={{ height: 1, background: 'var(--border)', flex: 1 }} />
          <span style={{ fontSize: 11.5, color: 'var(--fg-2)' }}>
            {ROOMS.length} rooms
          </span>
        </div>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(290px, 1fr))',
            gap: 16,
          }}
        >
          {ROOMS.map((r) => (
            <RoomCard key={r.id} r={r} />
          ))}
        </div>
      </div>
    </main>
  );
}

function Col4Chat() {
  const [tab, setTab] = useState('lobby');
  return (
    <aside
      style={{
        width: 320,
        background: 'var(--bg-1)',
        borderLeft: '1px solid var(--border)',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      <div
        style={{
          display: 'flex',
          padding: 10,
          gap: 4,
          borderBottom: '1px solid var(--border)',
        }}
      >
        {[
          { id: 'lobby', label: 'Lobby', dot: false },
          { id: 'friends', label: 'Friends', dot: true },
          { id: 'room', label: 'Room', dot: false },
        ].map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            style={{
              flex: 1,
              height: 30,
              borderRadius: 8,
              border: 'none',
              background: tab === t.id ? 'var(--bg-2)' : 'transparent',
              color: tab === t.id ? 'var(--fg-0)' : 'var(--fg-2)',
              fontSize: 12.5,
              fontWeight: 600,
              fontFamily: 'var(--font-thp-sans)',
              cursor: 'pointer',
              position: 'relative',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: 6,
            }}
          >
            {t.label}
            {t.dot ? (
              <span
                style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--danger)' }}
              />
            ) : null}
          </button>
        ))}
      </div>

      <div
        style={{
          padding: '12px 16px',
          borderBottom: '1px solid var(--border)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ color: 'var(--fg-2)', display: 'inline-flex' }}>{Icon.hash}</span>
          <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--fg-0)' }}>
            lobby-th08
          </span>
        </div>
        <span style={{ fontSize: 11, color: 'var(--fg-2)' }}>
          <span
            style={{
              display: 'inline-block',
              width: 6,
              height: 6,
              borderRadius: '50%',
              background: 'var(--success)',
              marginRight: 6,
              verticalAlign: 'middle',
            }}
          />
          47 online
        </span>
      </div>

      <div
        style={{
          flex: 1,
          overflowY: 'auto',
          padding: '14px 14px 8px',
          display: 'flex',
          flexDirection: 'column',
          gap: 14,
        }}
      >
        {CHAT.map((m, i) => {
          const share = m.share ? ROOMS.find((r) => r.id === m.share) : null;
          return (
            <div key={i} style={{ display: 'flex', gap: 10 }}>
              <Avatar size={28} name={m.who} />
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                  <span
                    className="cjk"
                    style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--fg-0)' }}
                  >
                    {m.who}
                  </span>
                  <span
                    style={{
                      fontSize: 10.5,
                      color: 'var(--fg-3)',
                      fontFamily: 'var(--font-thp-mono)',
                    }}
                  >
                    {m.t}
                  </span>
                </div>
                <div
                  className="cjk"
                  style={{
                    fontSize: 13,
                    color: 'var(--fg-1)',
                    lineHeight: 1.55,
                    marginTop: 1,
                    wordBreak: 'break-word',
                  }}
                >
                  {m.mention ? (
                    <>
                      <span
                        style={{
                          background: 'var(--brand-soft)',
                          color: 'var(--brand)',
                          padding: '1px 6px',
                          borderRadius: 6,
                          fontWeight: 600,
                          fontSize: 12.5,
                        }}
                      >
                        @{m.mention}
                      </span>
                      {' ' + m.msg.replace(`@${m.mention}`, '').trim()}
                    </>
                  ) : (
                    m.msg
                  )}
                </div>
                {share ? <MiniShareCard r={share} /> : null}
              </div>
            </div>
          );
        })}
        <div
          className="cjk"
          style={{
            marginTop: 4,
            padding: '10px 12px',
            fontSize: 12,
            color: 'var(--fg-2)',
            background: 'var(--bg-2)',
            borderRadius: 'var(--r-md)',
            border: '1px dashed var(--border-strong)',
            lineHeight: 1.5,
          }}
        >
          现在还没人在玩永夜抄，要不你来开第一桌?
        </div>
      </div>

      <div style={{ padding: 12, borderTop: '1px solid var(--border)' }}>
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            background: 'var(--bg-2)',
            borderRadius: 'var(--r-md)',
            border: '1px solid var(--border)',
            paddingInline: 10,
            height: 40,
          }}
        >
          <input
            placeholder="发个消息到 #闲聊…"
            className="cjk"
            style={{
              flex: 1,
              background: 'transparent',
              border: 'none',
              outline: 'none',
              color: 'var(--fg-0)',
              fontSize: 13,
              fontFamily: 'var(--font-thp-sans)',
            }}
          />
          <button
            style={{
              width: 28,
              height: 28,
              border: 'none',
              background: 'transparent',
              color: 'var(--fg-2)',
              cursor: 'pointer',
              borderRadius: 6,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            {Icon.smile}
          </button>
          <button
            style={{
              width: 28,
              height: 28,
              border: 'none',
              background: 'var(--brand)',
              color: '#fff',
              cursor: 'pointer',
              borderRadius: 8,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            {Icon.send}
          </button>
        </div>
      </div>
    </aside>
  );
}

export function LobbyPage({ theme = 'dark' }: { theme?: 'dark' | 'light' }) {
  return (
    <div
      className={`thp theme-${theme}`}
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'row',
        background: 'var(--bg-0)',
        overflow: 'hidden',
      }}
    >
      <Col1Rail />
      <Col2Navigator />
      <Col3Content />
      <Col4Chat />
    </div>
  );
}
