// @ts-nocheck
// Generated by Claude Design (Opus 4.7) v0.7 — Profile (popover + full).

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { useMe } from '@/hooks';

const { Button: BtnP, Tag: TagP } = UI;
const { ServerRail: RailP, Row: RowP, IdentityCard: IdP } = SHARED;

function PortraitPlate({ size = 96, mono = '幽' }) {
  return (
    <div style={{
      width: size, height: size, borderRadius: 'var(--r-md)',
      background: 'var(--bg-2)', border: '1px solid var(--border-strong)',
      display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
    }}>
      <span className="cjk" style={{ fontSize: size * 0.36, fontWeight: 700, color: 'var(--fg-0)', fontFamily: 'var(--font-display)' }}>{mono}</span>
    </div>
  );
}

function ProfilePopover({ onMessage }: any) {
  const { data: me } = useMe();
  if (!me) return null;
  return (
    <div className="anim-modal-in" style={{
      width: 320, background: 'var(--bg-1)', border: '1px solid var(--border)',
      borderRadius: 'var(--r-lg)', overflow: 'hidden', boxShadow: 'var(--shadow-lg)',
    }}>
      <div style={{ height: 64, background: 'var(--bg-2)', borderBottom: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', position: 'relative' }}>
        <span className="t-tag" style={{ position: 'absolute', top: 10, right: 12, color: 'var(--fg-2)' }}>夜组 · 管理员</span>
      </div>
      <div style={{ padding: '0 16px 16px', marginTop: -32 }}>
        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 10 }}>
          <div style={{ position: 'relative' }}>
            <PortraitPlate size={64} mono={me.name.slice(0,1)} />
            <span style={{ position: 'absolute', bottom: 2, right: 2, width: 14, height: 14, borderRadius: '50%', background: 'var(--status-online)', border: '2px solid var(--bg-1)' }} />
          </div>
          <div style={{ display: 'flex', gap: 6, marginBottom: 4, marginLeft: 'auto' }}>
            <BtnP variant="secondary" size="sm" onClick={onMessage}><Lu name="message-square" size={11} /><span className="cjk" style={{ marginLeft: 4 }}>消息</span></BtnP>
            <BtnP variant="ghost" size="sm"><Lu name="more-horizontal" size={12} /></BtnP>
          </div>
        </div>
        <div style={{ marginTop: 10 }}>
          <div className="cjk h-display-md">{me.name}</div>
          <div className="num" style={{ fontSize: 11, color: 'var(--fg-2)', marginTop: 2 }}>@{me.handle} · {me.pronoun}</div>
        </div>
        <div style={{ marginTop: 10, padding: 10, background: 'var(--bg-2)', border: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', borderRadius: 6 }}>
          <div className="t-tag" style={{ color: 'var(--accent)' }}>当前游戏</div>
          <div className="cjk t-body" style={{ color: 'var(--fg-0)', marginTop: 4, fontWeight: 600 }}>永夜抄 PvP — 北京</div>
          <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)', marginTop: 1 }}>#4912 · 已游玩 18 分钟 · Lunatic</div>
          <BtnP variant="primary" size="sm" style={{ marginTop: 8, width: '100%' }}><span className="cjk">围观这局</span></BtnP>
        </div>
        <div style={{ marginTop: 12 }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>关于</div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-1)', marginTop: 6, lineHeight: 1.6, whiteSpace: 'pre-line' }}>{me.bio}</div>
        </div>
        <div style={{ marginTop: 12 }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>共同群组 · {me.groups.length}</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 6 }}>
            {me.groups.map(g => (
              <div key={g.name} className="cjk t-caption" style={{ color: 'var(--fg-1)', display: 'flex', justifyContent: 'space-between' }}>
                <span>{g.name}</span><span style={{ color: 'var(--fg-3)' }}>{g.role}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

type ProfileFullProps = {
  theme?: 'dark' | 'light';
  handle?: string;
  onNavigate?: (target: { name: string; [k: string]: any }) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function ProfileFull({ theme = 'dark', onNavigate, onToast }: ProfileFullProps) {
  const { data: me } = useMe();
  const nav = (t: any) => onNavigate && onNavigate(t);
  const stub = (label: string) => onToast && onToast({ tone: 'info', title: label });
  if (!me) return null;
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)' }}>
      <RailP active="dm" onPick={(p: string) => {
        if (p === 'home') nav({ name: 'lobby' });
        else if (p === 'settings') nav({ name: 'settings' });
        else if (p === 'discover') stub('发现');
        else if (p === 'add-server') stub('添加服务器');
        else nav({ name: 'lobby', gameId: p });
      }} />
      <aside style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
        <div style={{ padding: '12px 14px', borderBottom: '1px solid var(--border)' }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>个人主页</div>
          <div className="cjk h-display-sm" style={{ marginTop: 4 }}>@{me.handle}</div>
        </div>
        <div style={{ padding: '8px 6px', flex: 1 }}>
          <RowP active onClick={() => {}} leading={<Lu name="user" size={13} color="var(--fg-2)" />}><span className="cjk t-body" style={{ fontWeight: 600, color: 'var(--fg-0)' }}>概览</span></RowP>
          <RowP onClick={() => stub('战绩详情')} leading={<Lu name="bar-chart-3" size={13} color="var(--fg-2)" />}><span className="cjk t-body">战绩</span></RowP>
          <RowP onClick={() => stub('录像列表')} leading={<Lu name="film" size={13} color="var(--fg-2)" />}><span className="cjk t-body">录像</span></RowP>
          <RowP onClick={() => stub('徽章详情')} leading={<Lu name="award" size={13} color="var(--fg-2)" />}><span className="cjk t-body">徽章</span></RowP>
          <RowP onClick={() => stub('共同群组')} leading={<Lu name="users" size={13} color="var(--fg-2)" />}><span className="cjk t-body">群组</span></RowP>
        </div>
        <IdP onSettings={() => nav({ name: 'settings' })} />
      </aside>
      <main style={{ flex: 1, minWidth: 0, overflowY: 'auto', background: 'var(--bg-0)', position: 'relative' }}>
        <div style={{ height: 120, background: 'var(--bg-2)', borderBottom: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', position: 'relative' }} />
        <div style={{ padding: '52px 28px 24px', display: 'flex', alignItems: 'center', gap: 16, position: 'relative' }}>
          <div style={{ position: 'absolute', top: -48, left: 28 }}><PortraitPlate size={96} mono={me.name.slice(0,1)} /></div>
          <div style={{ width: 96, flexShrink: 0 }} />
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <h1 className="cjk h-display-lg" style={{ margin: 0 }}>{me.name}</h1>
              <span style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--status-online)' }} />
              <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>在线</span>
            </div>
            <div className="num" style={{ fontSize: 12, color: 'var(--fg-2)', marginTop: 2 }}>@{me.handle} · {me.pronoun} · joined {me.joined}</div>
            <div className="cjk t-body" style={{ color: 'var(--fg-1)', marginTop: 4 }}>{me.presence}</div>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <BtnP variant="secondary" size="md" onClick={() => nav({ name: 'dm', view: 'dm', peer: me.handle })}><Lu name="message-square" size={12} /><span className="cjk" style={{ marginLeft: 6 }}>发消息</span></BtnP>
            <BtnP variant="primary" size="md" onClick={() => stub('围观对局')}><span className="cjk">围观对局</span></BtnP>
            <BtnP variant="ghost" size="md"><Lu name="more-horizontal" size={13} /></BtnP>
          </div>
        </div>
        <div style={{ padding: '0 28px 28px', display: 'grid', gridTemplateColumns: '1fr 320px', gap: 18 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
            <section style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>各作通关纪录</div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginTop: 10 }}>
                {Object.entries(me.ranks).map(([k, v]) => (
                  <div key={k} style={{ padding: '10px 12px', background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 6 }}>
                    <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>{k.toUpperCase()}</div>
                    <div className="num" style={{ fontSize: 13, fontWeight: 700, color: 'var(--fg-0)', marginTop: 2 }}>{v}</div>
                  </div>
                ))}
              </div>
            </section>
            <section style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div className="t-tag" style={{ color: 'var(--fg-2)' }}>最近对局</div>
                <button className="cjk t-caption btn-pressable" style={{ background: 'transparent', border: 'none', color: 'var(--fg-2)', cursor: 'pointer' }}>查看全部 →</button>
              </div>
              <div style={{ marginTop: 8 }}>
                {me.recent.map((r, i) => (
                  <div key={i} className="anim-row-in" style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0', borderTop: i === 0 ? 'none' : '1px solid var(--border)', '--i': i } as any}>
                    <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-1)', padding: '2px 6px', border: '1px solid var(--border)', borderRadius: 3, background: 'var(--bg-2)' }}>{r.game}</span>
                    <span className="cjk t-body-lg" style={{ color: 'var(--fg-0)', flex: 1 }}>{r.mode}</span>
                    <span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>{r.score}</span>
                    <span className="cjk t-caption" style={{ color: 'var(--fg-3)', minWidth: 56, textAlign: 'right' }}>{r.time}</span>
                  </div>
                ))}
              </div>
            </section>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            <section style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>关于</div>
              <div className="cjk t-body" style={{ color: 'var(--fg-1)', marginTop: 6, lineHeight: 1.65, whiteSpace: 'pre-line' }}>{me.bio}</div>
            </section>
            <section style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>徽章</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 8 }}>
                {me.badges.map(b => <TagP key={b}><span className="cjk">{b}</span></TagP>)}
              </div>
            </section>
            <section style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>群组 · {me.groups.length}</div>
              <div style={{ marginTop: 6 }}>
                {me.groups.map(g => (
                  <div key={g.name} style={{ padding: '8px 0', borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between' }}>
                    <span className="cjk t-body" style={{ color: 'var(--fg-1)' }}>{g.name}</span>
                    <span className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>{g.role}</span>
                  </div>
                ))}
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
}

export { ProfilePopover, ProfileFull };
