// Generated by Claude Design (Opus 4.7) v0.7 — Profile (popover + full).

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { useMe, useProfile } from '@/hooks';
import { Unavailable } from '@/components/unavailable';
import { currentViewUrl, copyToClipboard } from '@/lib/clipboard';
import type { NavTarget } from '@/router';
import type { Profile } from '@/lib/api/types';
import type { StaggerStyle } from '@/components/design/shared';

const { Button: BtnP, Tag: TagP } = UI;
const { ServerRail: RailP, Row: RowP, IdentityCard: IdP } = SHARED;

// How many 最近对局 rows show before 查看全部 appears. Without this the "see
// all" button had nothing to expand: the list rendered in full and the button
// still sat there, with no handler, directly above an empty state.
const PREVIEW_ROWS = 3;

function PortraitPlate({ size = 96, mono = '幽' }: { size?: number; mono?: string }) {
  return (
    <div style={{
      width: size, height: size, borderRadius: 'var(--r-md)',
      background: 'var(--bg-2)', border: '1px solid var(--border-strong)',
      display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
    }}>
      <span className="cjk" style={{ fontSize: size * 0.36, fontWeight: 700, color: 'var(--fg-0)', fontFamily: 'var(--font-display)' }}>{mono}</span>
    </div>
  );
}

/**
 * What the profile shows when there is no profile to show.
 *
 * `getMe()` is one of the four routes that reject rather than degrade, so a
 * server that is down -- or one the browser is not allowed to reach -- leaves
 * the profile undefined forever. Rendering `null` there is what turned a
 * transport failure into a blank window with no rail, no sidebar and no way
 * back. A blank page is not a state a person can act on, so this states the
 * reason and offers the one action that can change it.
 */
function ProfileUnavailable({
  loading,
  error,
  onRetry,
}: {
  loading: boolean;
  error: Error | null;
  onRetry: () => void;
}) {
  return (
    <UI.EmptyState
      icon={loading ? 'loader' : 'wifi-off'}
      title={loading ? '正在读取资料…' : '读不到这份资料'}
      body={
        loading
          ? '正在向服务器请求资料'
          : `无法连接服务器。${error?.message ? error.message : '请确认服务端已启动后重试。'}`
      }
      action={
        loading ? null : (
          <UI.Button variant="primary" size="md" onClick={onRetry}>
            <Lu name="refresh-cw" size={12} />
            <span className="cjk" style={{ marginLeft: 6 }}>重试</span>
          </UI.Button>
        )
      }
    />
  );
}

type ProfilePopoverProps = {
  /** The signed-in identity, from GET /v1/me. */
  me?: Profile | null;
  onMessage?: () => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function ProfilePopover({ me, onMessage, onToast }: ProfilePopoverProps) {
  const frame = (children: React.ReactNode) => (
    <div className="anim-modal-in" style={{
      width: 320, background: 'var(--bg-1)', border: '1px solid var(--border)',
      borderRadius: 'var(--r-lg)', overflow: 'hidden', boxShadow: 'var(--shadow-lg)',
    }}>{children}</div>
  );

  // The backdrop this popover sits on stays click-to-dismiss, so returning null
  // left a full-screen dim overlay with nothing in it. Give it the reason.
  if (!me) {
    return frame(
      <ProfileUnavailable loading={!me} error={null} onRetry={() => onToast?.({
        tone: 'warn', title: '读不到身份', body: 'GET /v1/me 没有返回资料，这个弹窗需要它才能显示。',
      })} />
    );
  }

  return frame(
    <>
      <div style={{ height: 64, background: 'var(--bg-2)', borderBottom: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', position: 'relative' }}>
        {/* "夜组 · 管理员" was a literal on every popover, for every account. */}
        <span className="t-tag" style={{ position: 'absolute', top: 10, right: 12, color: 'var(--fg-2)' }}>@{me.handle}</span>
      </div>
      <div style={{ padding: '0 16px 16px', marginTop: -32 }}>
        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 10 }}>
          <div style={{ position: 'relative' }}>
            <PortraitPlate size={64} mono={me.name.slice(0, 1)} />
            <span style={{ position: 'absolute', bottom: 2, right: 2, width: 14, height: 14, borderRadius: '50%', background: me.status === 'online' ? 'var(--status-online)' : 'var(--fg-3)', border: '2px solid var(--bg-1)' }} title={me.presence} />
          </div>
          <div style={{ display: 'flex', gap: 6, marginBottom: 4, marginLeft: 'auto' }}>
            <BtnP variant="secondary" size="sm" onClick={onMessage}><Lu name="message-square" size={11} /><span className="cjk" style={{ marginLeft: 4 }}>消息</span></BtnP>
            <Unavailable reason="更多操作需要服务端的下拉菜单接口；现在没有可列的动作。">
              <BtnP variant="ghost" size="sm" disabled><Lu name="more-horizontal" size={12} /></BtnP>
            </Unavailable>
          </div>
        </div>
        <div style={{ marginTop: 10 }}>
          <div className="cjk h-display-md">{me.name}</div>
          <div className="num" style={{ fontSize: 11, color: 'var(--fg-2)', marginTop: 2 }}>@{me.handle} · {me.pronoun}</div>
        </div>
        {/*
          This block used to read "永夜抄 PvP — 北京 / #4912 / 已游玩 18 分钟 ·
          Lunatic" with a 围观这局 button that did nothing, on every account.
          None of it came from a request: /v1/me carries no current-room field.
          It is now the real presence string and the real join date, and the
          watch button is gone rather than decorative.
        */}
        <div style={{ marginTop: 10, padding: 10, background: 'var(--bg-2)', border: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', borderRadius: 6 }}>
          <div className="t-tag" style={{ color: 'var(--accent)' }}>当前状态</div>
          <div className="cjk t-body" style={{ color: 'var(--fg-0)', marginTop: 4, fontWeight: 600 }}>{me.presence}</div>
          <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)', marginTop: 1 }}>加入于 {me.joined}</div>
        </div>
        <div style={{ marginTop: 12 }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>关于</div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-1)', marginTop: 6, lineHeight: 1.6, whiteSpace: 'pre-line' }}>{me.bio || '这个人还没有写简介。'}</div>
        </div>
        <div style={{ marginTop: 12 }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>共同群组 · {me.groups.length}</div>
          {me.groups.length === 0 ? (
            <div className="cjk t-caption" style={{ color: 'var(--fg-3)', marginTop: 6 }}>服务端没有记录共同群组。</div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 6 }}>
              {me.groups.map((g) => (
                <div key={g.name} className="cjk t-caption" style={{ color: 'var(--fg-1)', display: 'flex', justifyContent: 'space-between' }}>
                  <span>{g.name}</span><span style={{ color: 'var(--fg-3)' }}>{g.role}</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  );
}

/** The five rows in the left column. `section` scrolls the main column to it. */
type ProfileSection = 'overview' | 'ranks' | 'recent' | 'badges' | 'groups';

const SECTIONS: { id: ProfileSection; label: string; icon: string }[] = [
  { id: 'overview', label: '概览', icon: 'user' },
  { id: 'ranks', label: '战绩', icon: 'bar-chart-3' },
  { id: 'recent', label: '对局', icon: 'swords' },
  { id: 'badges', label: '徽章', icon: 'award' },
  { id: 'groups', label: '群组', icon: 'users' },
];

type ProfileFullProps = {
  theme?: 'dark' | 'light';
  handle?: string;
  onNavigate?: (target: NavTarget) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function ProfileFull({ theme = 'dark', handle, onNavigate, onToast }: ProfileFullProps) {
  // A handle in the route means "this person's profile", and the server has a
  // route for it: GET /v1/users/{handle}. This page ignored it and always read
  // /v1/me, so every "open profile" in the app — the room's player list, the
  // lobby's share cards, a link in chat — landed on the viewer's own profile
  // while claiming to be someone else's.
  const mine = useMe();
  const theirs = useProfile(handle ?? '');
  const lookingAtOther = !!handle && handle !== mine.data?.handle;
  const state = lookingAtOther ? theirs : mine;
  const me = state.data;

  const [section, setSection] = React.useState<ProfileSection>('overview');
  const [showAllRecent, setShowAllRecent] = React.useState(false);
  const bodyRef = React.useRef<HTMLDivElement>(null);
  const visibleRecent = me && !showAllRecent ? me.recent.slice(0, PREVIEW_ROWS) : (me?.recent ?? []);

  const nav = (t: NavTarget) => onNavigate && onNavigate(t);
  // These two were declared in ProfileFullProps and never bound, so every nav
  // row and every button on this page called an undefined identifier and threw
  // a ReferenceError on click -- behind a green `tsc -b` and a green
  // `vite build`, because the file carried @ts-nocheck. The blanket suppression
  // hid 261 errors across nine files.
  //
  // The sidebar rows are no longer toasts either: all five sections are on this
  // page already, so they scroll to the section they name.
  const goTo = (id: ProfileSection) => {
    setSection(id);
    const node = bodyRef.current?.querySelector<HTMLElement>(`[data-profile-section="${id}"]`);
    node?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };
  const stub = (label: string) => onToast && onToast({ tone: 'info', title: label, body: '该功能将在 V1 后期开放' });

  // No early return. The rail, the sidebar and the navigation rows render in
  // every state, so a person who cannot reach the server is still standing in
  // the app with a way out, instead of looking at an empty window.
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)' }}>
      <RailP active="dm" onPick={(p: string) => {
        if (p === 'home') nav({ name: 'lobby' });
        else if (p === 'settings') nav({ name: 'settings' });
        else if (p === 'discover') stub('发现');
        else if (p === 'add-server') stub('添加服务器');
        else nav({ name: 'lobby', gameId: p });
      }} />
      <aside className="thp-col-nav" style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '12px 14px', borderBottom: '1px solid var(--border)' }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>个人主页</div>
          <div className="cjk h-display-sm" style={{ marginTop: 4 }}>{me ? `@${me.handle}` : '未载入'}</div>
        </div>
        <div style={{ padding: '8px 6px', flex: 1 }}>
          {SECTIONS.map((s) => (
            <RowP
              key={s.id}
              active={section === s.id}
              onClick={() => goTo(s.id)}
              leading={<Lu name={s.icon} size={13} color={section === s.id ? 'var(--fg-0)' : 'var(--fg-2)'} />}
            >
              <span className="cjk t-body" style={{ fontWeight: section === s.id ? 600 : 500, color: section === s.id ? 'var(--fg-0)' : undefined }}>
                {s.label}
              </span>
            </RowP>
          ))}
          <div style={{ height: 1, background: 'var(--border)', margin: '8px 6px' }} />
          <Unavailable block reason="录像需要服务端按房间存回放文件与索引；现在没有任何录像相关的接口。">
            <span className="btn-pressable" style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '6px 10px', borderRadius: 6, color: 'var(--fg-2)' }}>
              <Lu name="film" size={13} color="var(--fg-3)" />
              <span className="cjk t-body">录像</span>
            </span>
          </Unavailable>
        </div>
        <IdP me={mine.data ?? null} onSettings={() => nav({ name: 'settings' })} onProfile={() => nav({ name: 'profile' })} />
      </aside>
      <main ref={bodyRef} className="thp-col-main" style={{ overflowY: 'auto', background: 'var(--bg-0)', position: 'relative' }}>
        <div style={{ height: 120, background: 'var(--bg-2)', borderBottom: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', position: 'relative' }} />
        {me && (
        <>
        <div style={{ padding: '52px 28px 24px', display: 'flex', alignItems: 'center', gap: 16, position: 'relative' }}>
          <div style={{ position: 'absolute', top: -48, left: 28 }}><PortraitPlate size={96} mono={me.name.slice(0, 1)} /></div>
          <div style={{ width: 96, flexShrink: 0 }} />
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <h1 className="cjk h-display-lg" style={{ margin: 0 }}>{me.name}</h1>
              <span style={{ width: 8, height: 8, borderRadius: '50%', background: me.status === 'online' ? 'var(--status-online)' : me.status === 'offline' ? 'var(--fg-3)' : 'var(--status-warn)' }} />
              <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{me.presence}</span>
            </div>
            <div className="num" style={{ fontSize: 12, color: 'var(--fg-2)', marginTop: 2 }}>@{me.handle} · {me.pronoun} · joined {me.joined}</div>
            {me.bio ? (
              <div className="cjk t-body" style={{ color: 'var(--fg-1)', marginTop: 4 }}>{me.bio}</div>
            ) : null}
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            {lookingAtOther ? (
              <BtnP variant="secondary" size="md" onClick={() => nav({ name: 'dm', view: 'dm', peer: me.handle })}><Lu name="message-square" size={12} /><span className="cjk" style={{ marginLeft: 6 }}>发消息</span></BtnP>
            ) : null}
            {/*
              围观对局 needs a per-player "current room" field, and /v1/me has no
              such column. It is not disabled for looks: the room it would open
              is a room id this client has never been told.
            */}
            <Unavailable reason="围观对局需要服务端给每个玩家一个「当前房间」字段；/v1/me 没有这一项，客户端也就无从知道该开哪一间。">
              <BtnP variant="primary" size="md" disabled><span className="cjk">围观对局</span></BtnP>
            </Unavailable>
            <Unavailable reason="更多操作没有可列的动作：置顶、拉黑、举报都要服务端先有对应的写接口。">
              <BtnP variant="ghost" size="md" disabled title="更多操作" aria-label="更多操作"><Lu name="more-horizontal" size={13} /></BtnP>
            </Unavailable>
          </div>
        </div>
        <div className="thp-split" style={{ padding: '0 28px 28px' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
            <section data-profile-section="ranks" style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16, scrollMarginTop: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>各作通关纪录</div>
              {Object.entries(me.ranks).length === 0 ? (
                <UI.EmptyState icon="trophy" title="服务端没有记录通关成绩" body="通关数据要由对局结算写回，目前 /v1/me 的 ranks 永远是空的。" />
              ) : (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginTop: 10 }}>
                {Object.entries(me.ranks).map(([k, v]) => (
                  <div key={k} style={{ padding: '10px 12px', background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 6 }}>
                    <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>{k.toUpperCase()}</div>
                    <div className="num" style={{ fontSize: 13, fontWeight: 700, color: 'var(--fg-0)', marginTop: 2 }}>{v}</div>
                  </div>
                ))}
              </div>
              )}
            </section>
            <section data-profile-section="recent" style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16, scrollMarginTop: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div className="t-tag" style={{ color: 'var(--fg-2)' }}>最近对局</div>
                {/* Had no onClick at all, and rendered even when there was
                    nothing to expand — a dead "see all" sitting directly above
                    an empty state saying there are no records. It now collapses
                    the list to 3 and expands back, and disappears when there is
                    nothing behind it. */}
                {me.recent.length > PREVIEW_ROWS ? (
                  <button aria-expanded={showAllRecent} onClick={() => setShowAllRecent((v) => !v)} className="cjk t-caption btn-pressable" style={{ background: 'transparent', border: 'none', color: 'var(--fg-2)', cursor: 'pointer' }}>
                    {showAllRecent ? '收起' : `查看全部 ${me.recent.length} 场 →`}
                  </button>
                ) : null}
              </div>
              <div style={{ marginTop: 8 }}>
                {me.recent.length === 0 ? (
                  <UI.EmptyState icon="swords" title="服务端没有记录对局" body="对局记录要由结算写回，目前 /v1/me 的 recent 永远是空的。" />
                ) : visibleRecent.map((r, i) => (
                  <div key={i} className="anim-row-in" style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0', borderTop: i === 0 ? 'none' : '1px solid var(--border)', '--i': i } as StaggerStyle}>
                    <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-1)', padding: '2px 6px', border: '1px solid var(--border)', borderRadius: 3, background: 'var(--bg-2)' }}>{r.game}</span>
                    <span className="cjk t-body-lg" style={{ color: 'var(--fg-0)', flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.mode}</span>
                    <span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>{r.score}</span>
                    <span className="cjk t-caption" style={{ color: 'var(--fg-3)', minWidth: 56, textAlign: 'right' }}>{r.time}</span>
                  </div>
                ))}
              </div>
            </section>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            <section data-profile-section="overview" style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16, scrollMarginTop: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>关于</div>
              <div className="cjk t-body" style={{ color: 'var(--fg-1)', marginTop: 6, lineHeight: 1.65, whiteSpace: 'pre-line' }}>{me.bio || '这个人还没有写简介。'}</div>
            </section>
            <section data-profile-section="badges" style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16, scrollMarginTop: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>徽章</div>
              {me.badges.length === 0 ? (
                <UI.EmptyState icon="award" title="服务端没有记录徽章" body="徽章要由对局结算授予，目前 /v1/me 的 badges 永远是空的。" />
              ) : (
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 8 }}>
                {me.badges.map((b) => <TagP key={b}><span className="cjk">{b}</span></TagP>)}
              </div>
              )}
            </section>
            <section data-profile-section="groups" style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', padding: 16, scrollMarginTop: 16 }}>
              <div className="t-tag" style={{ color: 'var(--fg-2)' }}>群组 · {me.groups.length}</div>
              {me.groups.length === 0 ? (
                <UI.EmptyState icon="users" title="服务端没有记录群组" body="群组成员关系要由 /v1/me 带上，目前它永远是空的。" />
              ) : (
              <div style={{ marginTop: 6 }}>
                {me.groups.map((g) => (
                  <div key={g.name} style={{ padding: '8px 0', borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', gap: 12 }}>
                    <span className="cjk t-body" style={{ color: 'var(--fg-1)', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{g.name}</span>
                    <span className="cjk t-caption" style={{ color: 'var(--fg-3)', flexShrink: 0 }}>{g.role}</span>
                  </div>
                ))}
              </div>
              )}
            </section>
          </div>
        </div>
        </>
        )}
        {!me && (
          <div style={{ padding: '48px 28px' }}>
            <ProfileUnavailable
              loading={state.isLoading}
              error={state.error}
              onRetry={lookingAtOther ? theirs.refetch : mine.refetch}
            />
            <div style={{ textAlign: 'center' }}>
              <BtnP variant="ghost" size="sm" onClick={async () => {
                const ok = await copyToClipboard(currentViewUrl());
                onToast?.(ok
                  ? { tone: 'success', title: '已复制链接', body: handle ? `@${handle}` : currentViewUrl() }
                  : { tone: 'warn', title: '复制失败', body: '浏览器拒绝了剪贴板写入。' });
              }}>
                <Lu name="copy" size={12} />
                <span className="cjk" style={{ marginLeft: 6 }}>复制这个主页的链接</span>
              </BtnP>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

export { ProfilePopover, ProfileFull };
