
// Generated by Claude Design (Opus 4.7) v0.7 — Room page.
import { copyToClipboard, currentViewUrl } from '@/lib/clipboard';
import { ChatComposer, sendFailureToast } from '@/components/chat-composer';

import * as React from 'react';
import * as UI from '@/components/design/ui';
import * as SHARED from '@/components/design/shared';
import { Lu } from '@/components/design/lucide';
import { api } from '@/lib/api/client';
import { useAsync } from '@/hooks/use-async';
import { useBackendReachable, BackendBanner } from '@/components/backend-status';
import { peerAddr, type ChatMsg, type Difficulty, type Room, type RoomState, type Seat } from '@/lib/api/types';
import { Unavailable, UnavailablePanel } from '@/components/unavailable';
import { useMe } from '@/hooks';
import { launchRoomGame } from '@/lib/tauri/launch';
import type { NavTarget } from '@/router';
import type { StaggerStyle } from '@/components/design/shared';

const { useState: useStateR } = React;
const { Button: BtnR, Avatar: AvR } = UI;
const { ServerRail: RailR, Row: RowR, SectionLabel: SLR, Tabs: TabsR, IdentityCard: IdR, ChatMessage: CMR, StatusDot: SDR } = SHARED;

// Room.vis is the only source for the visibility wording below. The top chip
// and the sidebar info card each used to carry their own hardcoded label, so
// the two could disagree with the room they were describing.
const VIS_SHORT: Partial<Record<Room['vis'], string>> = { public: '公开', ask: '需申请', private: '私密' };
const VIS_ACTION: Partial<Record<Room['vis'], string>> = {
  public: '公开 · 直接加入',
  ask: '需申请 · 等待房主',
  private: '私密 · 仅邀请',
};

/**
 * The one surface this page shows when there is no room to render: still
 * loading, server unreachable, or a room the server says does not exist.
 *
 * These three used to be one case, and it was the loaded one. The page held its
 * seats, spectators and chat in module-level constants, so it rendered a
 * complete room with the backend stopped -- a screenshot of it proved nothing
 * about the wiring, and a person could not tell a dead server from a live one.
 *
 * `api.getRoom` resolves null for a 404 *and* for a refused connection, and the
 * three collection routes resolve [] for both, so the reachability probe is the
 * only thing that can separate "this room is gone" from "I could not ask".
 */
function roomStatus({ loading, unreachable, roomId, onRetry, onBack }: {
  loading: boolean;
  unreachable: boolean;
  roomId: number;
  onRetry: () => void;
  onBack: () => void;
}) {
  if (loading) {
    return (
      <UI.EmptyState
        icon="loader"
        title="正在读取房间…"
        body={`正在向服务器请求 /v1/rooms/${roomId}`}
      />
    );
  }
  if (unreachable) {
    return (
      <UI.EmptyState
        icon="wifi-off"
        title="读不到这个房间"
        body="连不上服务器。下面这些列表可能是空的，也可能只是没读到。"
        action={
          <BtnR variant="primary" size="md" onClick={onRetry}>
            <Lu name="refresh-cw" size={12} />
            <span className="cjk" style={{ marginLeft: 6 }}>重试</span>
          </BtnR>
        }
      />
    );
  }
  return (
    <UI.EmptyState
      icon="door-open"
      title={`房间 #${roomId} 不存在`}
      body="服务器回答了，但它手上没有这个房间。"
      action={
        <BtnR variant="secondary" size="md" onClick={onBack}>
          <span className="cjk">返回大厅</span>
        </BtnR>
      }
    />
  );
}

function CharPlate({ mono, isActive }: { mono?: string | null; isActive?: boolean }) {
  return (
    <div style={{
      width: 84, height: 84, borderRadius: 10,
      background: 'var(--bg-2)',
      border: `1px ${mono ? 'solid' : 'dashed'} ${isActive ? 'var(--border-strong)' : 'var(--border)'}`,
      display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
    }}>
      {mono ? (
        <span className="cjk" style={{ fontSize: 18, fontWeight: 600, color: 'var(--fg-1)' }}>{mono}</span>
      ) : (
        <span className="cjk t-caption" style={{ color: 'var(--fg-3)', textAlign: 'center', lineHeight: 1.4 }}>未选择<br/>角色</span>
      )}
    </div>
  );
}

function RoleChipR({ value, options, disabled, onPick }: { value: string; options: string[]; disabled?: boolean; onPick?: (option: string) => void }) {
  return (
    <div style={{
      display: 'inline-flex', flexShrink: 0,
      background: 'var(--bg-2)', borderRadius: 999, padding: 2,
      border: '1px solid var(--border)',
    }}>
      {options.map(o => (
        <button key={o} title={value === o ? `当前身份 ${o}` : `设为 ${o}`} disabled={disabled} onClick={() => onPick && onPick(o)} className="btn-pressable" style={{
          height: 20, paddingInline: 8, borderRadius: 999, border: 'none',
          background: value === o ? 'var(--bg-1)' : 'transparent',
          color: value === o ? 'var(--fg-0)' : 'var(--fg-2)',
          fontSize: 10.5, fontWeight: 600, fontFamily: 'var(--font-sans)',
          cursor: disabled ? 'not-allowed' : 'pointer',
          // The three labels are two CJK glyphs each. Without this they broke
          // mid-word ("正 / 常") as soon as the seat card got narrow.
          whiteSpace: 'nowrap',
        }}><span className="cjk">{o}</span></button>
      ))}
    </div>
  );
}

function SeatCard({ seat, isHost, index = 0, onPickRole }: { seat: Seat; isHost: boolean; index?: number; onPickRole?: (role: string) => void }) {
  if (!seat.name) {
    return (
      <div className="anim-row-in" style={{ height: 196, padding: 14, borderRadius: 'var(--r-md)', border: '1px dashed var(--border-strong)', background: 'transparent', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8, '--i': index } as StaggerStyle}>
        <Lu name="user-plus" size={20} color="var(--fg-3)" />
        <div className="cjk t-body" style={{ color: 'var(--fg-2)', fontWeight: 600 }}>邀请玩家</div>
        <div className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>SEAT #{seat.idx}</div>
      </div>
    );
  }
  return (
    <div className="anim-row-in" style={{
      // minHeight, not height: at a fixed 196px a long name pushed the role
      // chip row past the bottom edge and out of the card.
      minHeight: 196, padding: 14, borderRadius: 'var(--r-md)',
      background: 'var(--bg-1)',
      border: `1px solid ${seat.ready ? 'var(--border-strong)' : 'var(--border)'}`,
      display: 'flex', flexDirection: 'column', gap: 10, position: 'relative',
      transition: 'border-color var(--duration-fast) var(--ease-out-quart)',
      '--i': index,
    } as StaggerStyle}>
      <div className="num" style={{ position: 'absolute', top: 10, right: 12, fontSize: 10, color: 'var(--fg-3)' }}>#{seat.idx}</div>
      <div style={{ display: 'flex', gap: 12 }}>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, minWidth: 0, flex: 1 }}>
          <AvR size={42} name={seat.name} status={seat.status} />
          <div style={{ minWidth: 0, textAlign: 'center', width: '100%' }}>
            <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)', display: 'inline-flex', alignItems: 'center', gap: 4, maxWidth: '100%' }}>
              <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{seat.name}</span>
              {isHost ? <Lu name="crown" size={11} color="var(--fg-2)" /> : null}
            </div>
            <div className="num" style={{ fontSize: 10, color: 'var(--fg-2)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>@{seat.handle}</div>
          </div>
        </div>
        <CharPlate mono={seat.mono} isActive={seat.ready} />
      </div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginTop: 'auto' }}>
        {/* `Seat.role` is optional, so an unassigned role showed no chip lit at
            all. '正常' is the domain default the rest of the UI already assumes. */}
        <RoleChipR value={seat.role ?? '正常'} options={['正常','观战','缺席']} disabled={!isHost} onPick={onPickRole} />
        <span className={seat.ready ? 'num anim-ready' : 'num'} style={{
          fontSize: 10, fontWeight: 600, padding: '3px 7px', borderRadius: 4,
          background: seat.ready ? 'var(--bg-3)' : 'transparent',
          color: seat.ready ? 'var(--fg-0)' : 'var(--fg-3)',
          border: '1px solid',
          borderColor: seat.ready ? 'var(--accent)' : 'var(--border)',
          letterSpacing: '0.06em',
        }}>{seat.ready ? 'READY' : 'WAITING'}</span>
      </div>
    </div>
  );
}

function ParamRowR({ label, children }: { label: React.ReactNode; children?: React.ReactNode }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, padding: '11px 0', borderBottom: '1px solid var(--border)' }}>
      <span className="cjk t-body" style={{ color: 'var(--fg-2)' }}>{label}</span>
      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>{children}</span>
    </div>
  );
}

/**
 * Read-only display of a match parameter.
 *
 * Every control in this panel used to render as an enabled button with no
 * `onClick`: difficulty, mode, max lives, max bombs, the seed reroll, and the
 * visibility dropdown. They looked editable, so a host clicked them, nothing
 * happened, and the page never said why. Persisting any of them needs
 * `PATCH /v1/rooms/{id}`, which the server does not implement (its room router
 * mounts only the four GETs — listRooms, getRoom, listSeats, listSpectators).
 * So they now say exactly that when clicked, instead of silently doing
 * nothing. When the route lands, `readOnly` is the one thing to flip.
 */
function DiffRadio({ value, onBlocked }: { value: Difficulty; onBlocked?: () => void }) {
  return (
    <div style={{ display: 'inline-flex', gap: 4, flexWrap: 'wrap' }}>
      {['Easy','Normal','Hard','Lunatic','Extra'].map(o => (
        <button key={o} title={value === o ? `当前难度 ${o}` : `改为 ${o}`} onClick={onBlocked} className="btn-pressable" style={{
          height: 24, paddingInline: 9, borderRadius: 6, border: '1px solid',
          background: value === o ? 'var(--bg-3)' : 'var(--bg-2)',
          borderColor: value === o ? 'var(--border-strong)' : 'var(--border)',
          color: value === o ? 'var(--fg-0)' : 'var(--fg-2)',
          fontSize: 11, fontWeight: 600, fontFamily: 'var(--font-mono)', cursor: 'pointer',
        }}>{o}</button>
      ))}
    </div>
  );
}

/**
 * A match parameter the server has no field for.
 *
 * `Room` (src/lib/api/types.ts is the contract) carries id, gameId, kind,
 * title, host, region, ping, diff, mode, taken, total, vis, state and endpoint
 * — nothing else about a match exists to render. So this row says exactly
 * that, with the specific route or measurement that would make it show a
 * value, instead of printing a number.
 *
 * Every row it replaces was a literal behind a control: `3` lives, `3` bombs,
 * `0x4F2A91C7` behind a reroll button, `Full Cone` with a green dot, `1492`,
 * `60 Hz`, `10s`, `SHA256:af3c…91d2`, `已通过`, `20:58:14`, `98 / 100`. A host
 * clicked them and read back a value the server had never seen, and a player
 * who probed the port learned we were making it up.
 */
function ParamMissing({ why }: { why: string }) {
  return (
    <Unavailable reason={why}>
      <span className="num" style={{ fontSize: 11.5, color: 'var(--fg-3)' }}>—</span>
    </Unavailable>
  );
}

/** What a parameter that only a server field could carry would need. */
const NEEDS_ROOM_FIELD = (field: string) =>
  `Room 里没有 ${field} 字段（src/lib/api/types.ts 是这份契约的唯一真源），服务端也没有对应的列。要显示它并允许修改，需要 PATCH /v1/rooms/{id}。`;

/** What a parameter the client has to measure itself would need. */
const NOT_MEASURED = (what: string) =>
  `${what}——客户端没有任何代码测量它，服务端也没有这个字段，所以这里没有可显示的值。`;

const SEED_NOT_READABLE =
  '随机种子由 DLL 在握手时自己抽（dll/src/net/lockstep.cpp：读 TH08_PLATFORM_SEED，没有就用 GetTickCount64() 与进程号异或），只走 THP 的 START 包，不经过服务端。客户端读不到它，也无法重掷。';

function ParamPanel({ room, onBlocked }: { room: Room; onBlocked?: (what: string) => void }) {
  const [tab, setTab] = useStateR('basic');
  return (
    <div style={{ background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-lg)', display: 'flex', flexDirection: 'column', height: '100%' }}>
      <div style={{ padding: '14px 16px 0' }}>
        <div className="cjk h-display-sm" style={{ color: 'var(--fg-0)', marginBottom: 10 }}>对局参数</div>
        <TabsR dense
          tabs={[{id:'basic',label:<span className="cjk">基础</span>},{id:'adv',label:<span className="cjk">进阶</span>},{id:'net',label:<span className="cjk">网络</span>},{id:'ac',label:<span className="cjk">反作弊</span>}]}
          active={tab} onChange={setTab} />
      </div>
      <div style={{ padding: '6px 16px 16px', overflowY: 'auto' }}>
        {tab === 'basic' && (<>
          <ParamRowR label="难度"><DiffRadio value={room.diff} onBlocked={() => onBlocked && onBlocked('难度')} /></ParamRowR>
          <ParamRowR label="模式">
            <button title="切换模式" onClick={() => onBlocked && onBlocked('模式')} className="btn-pressable" style={{ height: 26, paddingInline: 10, gap: 6, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-2)', color: 'var(--fg-0)', fontSize: 11.5, fontWeight: 600, cursor: 'pointer', display: 'inline-flex', alignItems: 'center' }}><span className="cjk">{room.mode}</span><Lu name="chevron-down" size={12} /></button>
          </ParamRowR>
          <ParamRowR label="最大 Lives"><ParamMissing why={NEEDS_ROOM_FIELD('lives')} /></ParamRowR>
          <ParamRowR label="最大 Bombs"><ParamMissing why={NEEDS_ROOM_FIELD('bombs')} /></ParamRowR>
          <ParamRowR label="随机种子"><ParamMissing why={SEED_NOT_READABLE} /></ParamRowR>
        </>)}
        {tab === 'net' && (<>
          {/* Four spans — P2P 直连 / Relay / LAN / FRP — with the first one
              highlighted. They read as a choice, they are not buttons, and no
              route reports a transport. What is true is the single line below:
              the client dials the address the room publishes, over plain UDP,
              and only once the host has published one. */}
          <ParamRowR label="连接方式">
            <span className="num" style={{ fontSize: 11.5, color: room.endpoint ? 'var(--fg-0)' : 'var(--fg-3)' }}>
              {room.endpoint ? `P2P 直连 ${peerAddr(room.endpoint)}` : '未公布'}
            </span>
          </ParamRowR>
          <ParamRowR label="NAT 类型"><ParamMissing why={NOT_MEASURED('NAT 类型要靠 STUN 或服务端探测 UDP 打洞结果才能知道')} /></ParamRowR>
          <ParamRowR label="当前 RTT"><span className="num" style={{ fontSize: 11.5, color: 'var(--fg-0)', fontWeight: 600 }}>{room.ping} ms</span></ParamRowR>
          <ParamRowR label="MTU"><ParamMissing why={NOT_MEASURED('路径 MTU 由操作系统与链路协商决定，客户端从不读取')} /></ParamRowR>
          {/* The transport is plaintext UDP. `dll/src/net/protocol.h` — the
              fixed 152-byte `Pack` this comment used to cite — no longer
              exists: `dll/src/net/thp_session.h` documents its deletion and its
              replacement by the versioned THP protocol, and there is no
              cryptography anywhere in dll/src. Do not label this AES-256-GCM or
              any cipher: a player who probes the port learns we lie, and then
              nothing else we say is worth anything. Say what is true — the peer
              is trusted, and the payload is not confidential. */}
          <ParamRowR label="加密"><span className="num" style={{ fontSize: 10.5, color: 'var(--fg-1)', padding: '2px 6px', background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 4 }}>无</span></ParamRowR>
        </>)}
        {tab === 'ac' && (<>
          <ParamRowR label="DLL 签名"><ParamMissing why={NOT_MEASURED('客户端跑在 WebView 里，读不到注入的 DLL 文件，也算不出它的 SHA-256；服务端没有校验接口')} /></ParamRowR>
          <ParamRowR label="哈希校验"><ParamMissing why={NOT_MEASURED('没有任何代码比对哈希，这条结论没有来源')} /></ParamRowR>
          <ParamRowR label="最近注入"><ParamMissing why="注入时刻只写进桌面壳的注入日志，客户端没有读日志的命令：src-tauri 只暴露 launch_game 与 terminate_game。" /></ParamRowR>
          <ParamRowR label="完整性评分"><ParamMissing why={NOT_MEASURED('没有任何评分算法，这条分数没有来源')} /></ParamRowR>
        </>)}
        {tab === 'adv' && (<>
          <ParamRowR label="自机机型 锁定"><ParamMissing why={NEEDS_ROOM_FIELD('自机机型锁定')} /></ParamRowR>
          <ParamRowR label="符卡同步频率"><ParamMissing why={NOT_MEASURED('lockstep 跟随游戏帧推进，客户端没有可配置的同步频率')} /></ParamRowR>
          <ParamRowR label="掉线宽限"><ParamMissing why={NOT_MEASURED('掉线宽限由 DLL 的 KEEPALIVE 判定，不经过客户端')} /></ParamRowR>
          <ParamRowR label="允许中途加入"><ParamMissing why={NEEDS_ROOM_FIELD('中途加入策略')} /></ParamRowR>
        </>)}
      </div>
    </div>
  );
}

function RoomTopBar({ room, onBack, onCopy, onSettings, onVis }: { room: Room; onBack?: () => void; onCopy?: () => void; onSettings?: () => void; onVis?: () => void }) {
  return (
    <div style={{ height: 56, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 14, borderBottom: '1px solid var(--border)', background: 'var(--bg-0)' }}>
      <button onClick={onBack} className="btn-pressable" style={{ height: 28, paddingInline: 10, gap: 6, display: 'inline-flex', alignItems: 'center', background: 'transparent', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--fg-1)', cursor: 'pointer', fontSize: 12, fontWeight: 600 }}><Lu name="arrow-left" size={13} /><span className="cjk">返回大厅</span></button>
      <div style={{ flex: 1, minWidth: 0, textAlign: 'center' }}>
        <div className="cjk h-display-sm" style={{ color: 'var(--fg-0)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {room.title} <span className="num" style={{ color: 'var(--fg-3)', fontSize: 12, fontWeight: 600 }}>#{room.id}</span>
        </div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', display: 'inline-flex', gap: 8, alignItems: 'center', marginTop: 2 }}>
          <span className="t-tag" style={{ color: 'var(--accent)' }}>{room.kind.toUpperCase()} · {room.gameId.toUpperCase()}</span>
          <span style={{ color: 'var(--fg-3)' }}>·</span>
          <span><span style={{ color: 'var(--fg-1)' }}>主</span> {room.host}</span><span style={{ color: 'var(--fg-3)' }}>·</span>
          <span className="num">{room.ping}ms</span><span style={{ color: 'var(--fg-3)' }}>·</span>
          <span className="num" style={{ color: 'var(--fg-1)', fontWeight: 600 }}>{room.taken}/{room.total}</span>
        </div>
      </div>
      <div style={{ display: 'flex', gap: 6 }}>
        <button title="切换可见性" onClick={onVis} className="btn-pressable" style={{ height: 28, paddingInline: 10, gap: 6, display: 'inline-flex', alignItems: 'center', borderRadius: 999, background: 'var(--bg-2)', border: '1px solid var(--border)', color: 'var(--fg-1)', fontSize: 11.5, fontWeight: 600, cursor: 'pointer' }}><span style={{ width: 6, height: 6, borderRadius: '50%', background: room.vis === 'public' ? 'var(--status-online)' : 'var(--status-warn)' }} /><span className="cjk">{VIS_ACTION[room.vis] ?? room.vis}</span><Lu name="chevron-down" size={12} /></button>
        <button title="复制邀请" onClick={onCopy} className="btn-pressable" style={{ width: 28, height: 28, borderRadius: 6, background: 'var(--bg-2)', border: '1px solid var(--border)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="copy" size={13} /></button>
        <button title="房间设置" onClick={onSettings} className="btn-pressable" style={{ width: 28, height: 28, borderRadius: 6, background: 'var(--bg-2)', border: '1px solid var(--border)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="settings" size={13} /></button>
      </div>
    </div>
  );
}

function RoomBottomBar({ state = 'lobby', readyCount = 0, lastMessage, roomId, onStart, onLeave }: { state?: RoomState; readyCount?: number; lastMessage?: ChatMsg; roomId: number; onStart?: () => void; onLeave?: () => void }) {
  // NOTE: the router only ever produces 'lobby' | 'post' (src/router/index.tsx),
  // so the 'loading' arm below is unreachable today. It stays because
  // `RoomState` is the domain's own union and a server poll is what will start
  // feeding it — not because anything reaches it now.
  const cta = state === 'loading' ? { label: '正在加载…', spin: true, disabled: true, glow: false }
    : state === 'post' ? { label: '再来一局 REMATCH', glow: false }
    : { label: `开始对局 START · ${readyCount} ready`, glow: true };
  return (
    <div style={{ height: 76, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 14, borderTop: '1px solid var(--border)', background: 'var(--bg-0)' }}>
      <div style={{ flex: 1, minWidth: 0, height: 44, background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', paddingInline: 12, display: 'flex', alignItems: 'center', gap: 10, cursor: 'pointer' }}>
        {lastMessage ? (<>
          <AvR size={24} name={lastMessage.who ?? ''} />
          <div style={{ minWidth: 0, flex: 1 }}>
            <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}><span style={{ color: 'var(--fg-1)', fontWeight: 600 }}>{lastMessage.who}</span> · {lastMessage.t}</div>
            <div className="cjk t-body" style={{ color: 'var(--fg-1)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
              {lastMessage.msg}
            </div>
          </div>
        </>) : (
          <div className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>还没有人说话</div>
        )}
        <span className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>展开 #room-{roomId} →</span>
      </div>
      <button onClick={onStart} disabled={cta.disabled} className={`btn-pressable ${cta.glow ? 'anim-cta-glow' : ''}`} style={{ minWidth: 220, height: 44, paddingInline: 22, borderRadius: 'var(--r-md)', background: 'var(--accent)', color: 'var(--bg-0)', border: '1px solid var(--accent)', fontSize: 13, fontWeight: 700, cursor: cta.disabled ? 'not-allowed' : 'pointer', opacity: cta.disabled ? 0.55 : 1, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8, fontFamily: 'var(--font-sans)' }}>
        {cta.spin ? <span className="spinner" style={{ width: 12, height: 12, border: '2px solid rgba(0,0,0,0.25)', borderTopColor: 'var(--bg-0)', borderRadius: '50%' }} /> : null}
        <span className="cjk">{cta.label}</span>
      </button>
      <button onClick={onLeave} className="btn-pressable" style={{ height: 44, paddingInline: 14, borderRadius: 'var(--r-md)', background: 'transparent', border: '1px solid var(--border-strong)', color: 'var(--fg-1)', fontSize: 12.5, fontWeight: 600, cursor: 'pointer' }}><span className="cjk">离开房间</span></button>
    </div>
  );
}

function ChatDrawerR({ roomId, chat, sysLog, unreachable, roomLoaded, onSent, onFailed }: { roomId: number; chat: ChatMsg[]; sysLog: ChatMsg[]; unreachable: boolean; roomLoaded: boolean; onSent?: (msg: unknown) => void; onFailed?: (channelId: string, error: unknown) => void }) {
  return (
    <aside className="thp-col-aside" style={{ width: 320, background: 'var(--bg-1)', borderLeft: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
      <div style={{ padding: '12px 14px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <div style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--fg-0)' }}># room-{roomId}</div>
          <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>房间私聊</div>
        </div>
        <button className="btn-pressable" style={{ width: 24, height: 24, borderRadius: 6, border: 'none', background: 'transparent', color: 'var(--fg-2)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}><Lu name="x" size={14} /></button>
      </div>
      {sysLog.length > 0 && (
      <div style={{ margin: 12, padding: 10, borderRadius: 'var(--r-md)', background: 'var(--bg-2)', border: '1px solid var(--border)' }}>
        <div className="t-tag" style={{ color: 'var(--fg-2)' }}>对局信息 · 最近 {sysLog.length} 条</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 8 }}>
          {sysLog.map((m, i) => (
            <div key={i} className="cjk t-caption" style={{ color: 'var(--fg-1)', display: 'flex', gap: 8 }}>
              <span className="num" style={{ color: 'var(--fg-3)', fontSize: 10 }}>{m.t}</span><span>{m.text}</span>
            </div>
          ))}
        </div>
      </div>
      )}
      <div style={{ flex: 1, overflowY: 'auto', padding: '4px 12px 8px', display: 'flex', flexDirection: 'column', gap: 8 }}>
        {chat.length === 0 ? (
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <UI.EmptyState
              icon="message-square"
              title={!roomLoaded ? '房间未载入' : unreachable ? '读不到聊天记录' : '还没有人说话'}
              body={!roomLoaded
                ? '这个房间还没有载入，聊天记录读不了。'
                : unreachable
                  ? '连不上服务器，房间消息可能已经在路上了。'
                  : '房间里现在没有人打字。'}
            />
          </div>
        ) : chat.map((m, i) => {
          if (m.kind === 'sys') return (
            <div key={i} className="cjk t-caption" style={{ color: 'var(--fg-3)', textAlign: 'center', padding: '4px 0' }}>
              <span className="num" style={{ marginRight: 6 }}>{m.t}</span>{m.text}
            </div>
          );
          if (m.kind === 'embed') return (
            <div key={i} style={{ marginLeft: 38, marginTop: 6 }}>
              <SHARED.ServerCardFlat compact {...m.share} onJoin={() => {}} />
            </div>
          );
          const prev = chat[i-1];
          const samegroup = prev && prev.kind !== 'sys' && prev.who === m.who;
          return <CMR key={i} msg={m} samegroup={samegroup} />;
        })}
      </div>
      <ChatComposer
        channelId={`room-${roomId}`}
        placeholder={`发个消息到 #room-${roomId}`}
        onSent={onSent}
        onFailed={onFailed}
      />
    </aside>
  );
}

/**
 * The post-match card.
 *
 * It used to render a finished game that never happened: `21:42:08 · 用时
 * 18:24`, `妖梦 通关 永夜抄 2 面`, `魔理沙·B装备 · Lunatic · 3 lives`, a score of
 * `4,128,920,470`, `Lives / Death 2 / 1`, and four spell cards with their own
 * timestamps and try counts — every field a literal, identical for every room
 * and every player, on a route (`#/room/{id}?state=post`) that a player reaches
 * by editing the URL.
 *
 * There is no result type in src/lib/api/types.ts and no result route on the
 * server, so there is nothing here to render. The card keeps its two real
 * actions and says what is missing.
 */
function ResultsCard({ onRematch, onBack }: { onRematch?: () => void; onBack?: () => void }) {
  return (
    <div className="anim-modal-in" style={{ maxWidth: 540, margin: '24px auto', background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-lg)', padding: 26 }}>
      <span className="t-tag" style={{ color: 'var(--accent)' }}>SESSION ENDED</span>
      <h2 className="cjk h-display-lg" style={{ margin: '6px 0 0' }}>没有这一局的结算数据</h2>
      <UnavailablePanel
        title="结算还没有数据来源"
        missing={<>需要服务端为一场对局落库并下发结果：<span className="num">GET /v1/rooms/{'{id}'}/results</span> 一类的接口，以及 <span className="num">src/lib/api/types.ts</span> 里的一个 <span className="num">MatchResult</span>（得分、用时、剩余残机、通关面数与关键符卡）。目前这两样都不存在，<span className="num">Room</span> 只带 <span className="num">state</span>，不带结果——所以这里不显示任何分数。</>}
      />
      <div style={{ display: 'flex', gap: 8, marginTop: 20 }}>
        <BtnR variant="primary" size="lg" style={{ flex: 1 }} onClick={onRematch}><span className="cjk">再来一局</span></BtnR>
        <BtnR variant="secondary" size="lg" style={{ flex: 1 }} onClick={onBack}><span className="cjk">返回房间席位</span></BtnR>
      </div>
    </div>
  );
}

type RoomProps = {
  theme?: 'dark' | 'light';
  state?: 'lobby' | 'post';
  id?: number;
  onNavigate?: (target: NavTarget) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function Room({ theme = 'dark', state = 'lobby', id = 4912, onNavigate, onToast }: RoomProps) {
  const nav = (t: NavTarget) => onNavigate && onNavigate(t);
  const stub = (label: string) => onToast && onToast({ tone: 'info', title: label });
  // Every editable match parameter needs `PATCH /v1/rooms/{id}`. The server's
  // room router mounts only four GETs (list, get, seats, spectators), so these
  // used to render as live controls that silently did nothing. Naming the
  // missing route is the honest answer, and it is one toast, not a redesign.
  const needsRoomPatch = (what: string) => onToast && onToast({
    tone: 'warn',
    title: `${what}暂时改不了`,
    body: '服务端还没有 PATCH /v1/rooms/{id}，房间参数目前是只读的。',
  });

  // One fetch for the page, four routes. They are the same room, so splitting
  // them across four useAsync calls would let the header render from one
  // response and the seat grid from another.
  const { data, isLoading, refetch } = useAsync(async () => {
    const [room, seats, spectators, chat] = await Promise.all([
      api.getRoom(id),
      api.getRoomSeats(id),
      api.getRoomSpectators(id),
      api.getRoomChat(id),
    ]);
    return { room, seats, spectators, chat };
  }, [id]);

  // `client.ts` resolves a failed collection to [] and a failed room to null
  // without throwing, so an unreachable server and an empty room arrive as the
  // same values. The probe is what lets each empty state say which one it is.
  const unreachable = useBackendReachable() === 'down';
  const { data: me } = useMe();
  const room = data?.room ?? null;
  const seats = data?.seats ?? [];
  const spectators = data?.spectators ?? [];
  const chat = data?.chat ?? [];
  // The sys lines are the room's own event log; the drawer used to show a
  // hardcoded five-line version of the same thing next to the real chat.
  const sysLog = chat.filter((m) => m.kind === 'sys').slice(-5).reverse();
  const lastMessage = [...chat].reverse().find((m) => m.kind !== 'sys' && m.msg);
  const named = seats.filter((s) => s.name);
  const readyCount = named.filter((s) => s.ready).length;
  // START is the only path from a room to a running game. It used to raise a
  // toast, so `launchGame` had no caller at all and the address the server now
  // hands out went nowhere. The launch resolves to a pid or to a message the
  // player can act on; either way it is reported rather than swallowed.
  const [launching, setLaunching] = useStateR(false);
  const startMatch = async () => {
    if (!room || launching) return;
    setLaunching(true);
    try {
      const result = await launchRoomGame(room, seats);
      onToast && onToast({ tone: 'success', title: '游戏已启动', body: `pid ${result.pid}` });
    } catch (err) {
      // A rejected launch can be anything: an Error, a Tauri string, or a
      // structured payload. `instanceof` is the only honest narrowing here;
      // `err?.message` on a non-Error yields undefined and swallowed the reason.
      const why = err instanceof Error ? err.message : String(err);
      onToast && onToast({ tone: 'error', title: '启动失败', body: why });
    } finally {
      setLaunching(false);
    }
  };
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)', position: 'relative' }}>
      <BackendBanner />
      <RailR active="th08" onPick={(p: string) => {
        if (p === 'home') nav({ name: 'lobby' });
        else if (p === 'settings') nav({ name: 'settings' });
        else if (p === 'discover') stub('发现');
        else if (p === 'add-server') stub('添加服务器');
        else nav({ name: 'lobby', gameId: p });
      }} />
      <aside className="thp-col-nav" style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '12px 14px 10px', borderBottom: '1px solid var(--border)' }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>当前房间</div>
          <div className="cjk h-display-sm" style={{ color: 'var(--fg-0)', marginTop: 4, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{room ? room.title : '未载入'}</div>
          <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-3)', marginTop: 2 }}>#{id} · {room ? `${room.taken}/${room.total}` : '—'}</div>
        </div>
        <div style={{ padding: 10, overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div>
            <SLR>本房频道</SLR>
            <div style={{ marginTop: 6 }}>
              {/* One channel, and its id is the one the composer's POST uses:
                  `room-{id}` is what GET /v1/rooms/{id}/chat answers to. The
                  战术讨论 row beside it named a channel no route serves, and
                  clicking it toasted its own name — the client inventing a
                  second room channel out of nothing. */}
              <RowR leading={<span style={{ color: 'var(--fg-2)', fontWeight: 500, fontSize: 14, width: 14, textAlign: 'center' }}>#</span>}>
                <span className="cjk t-body" style={{ fontWeight: 600, color: 'var(--fg-0)' }}>room-{id}</span>
              </RowR>
            </div>
          </div>
          <div>
            <SLR>房间信息</SLR>
            <div style={{ marginTop: 8, padding: 12, background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', display: 'flex', flexDirection: 'column', gap: 6 }}>
              {[
                ['难度', room?.diff ?? '—'],
                ['模式', room?.mode ?? '—'],
                ['区域', room?.region ?? '—'],
                ['可见性', room ? VIS_SHORT[room.vis] ?? room.vis : '—'],
                // The address START will actually dial. Showing it makes a
                // mis-published endpoint visible before anyone launches.
                ['主机地址', room?.endpoint ? peerAddr(room.endpoint) : '未公布'],
              ].map(([k, v]) => (
                <div key={k} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11 }}>
                  <span className="cjk" style={{ color: 'var(--fg-2)' }}>{k}</span>
                  <span className="num" style={{ color: 'var(--fg-0)', fontWeight: 600 }}>{v}</span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <SLR right={<span className="num" style={{ fontSize: 10, color: 'var(--status-online)' }}>{readyCount} ready</span>}>队伍</SLR>
            <div style={{ marginTop: 6 }}>
              {named.length === 0 ? (
                <div className="cjk t-caption" style={{ color: 'var(--fg-3)', padding: '6px 8px' }}>
                  {!room ? '房间未载入' : unreachable ? '读不到席位' : '还没有人入座'}
                </div>
              ) : named.map((s) => (
                <RowR key={s.idx} onClick={() => stub(`${s.name} 个人主页`)}
                  leading={<AvR size={22} name={s.name ?? ''} status={s.status} />}
                  trailing={s.idx === 1 ? <Lu name="crown" size={11} color="var(--fg-2)" /> : <SDR status={s.ready ? 'online' : 'idle'} />}>
                  <span className="cjk t-body" style={{ color: 'var(--fg-0)' }}>{s.name}</span>
                </RowR>
              ))}
            </div>
          </div>
        </div>
        <IdR me={me ?? null} onSettings={() => nav({ name: 'settings' })} onProfile={() => nav({ name: 'profile' })} />
      </aside>
      <main className="thp-col-main" style={{ display: 'flex', flexDirection: 'column' }}>
        {room
          ? <RoomTopBar room={room} onBack={() => nav({ name: 'lobby' })} onCopy={async () => {
              // This used to fire a "已复制邀请链接" toast without touching the
              // clipboard, so the toast was a lie and the pasted text was
              // whatever the user had copied before. Report the real outcome.
              const ok = await copyToClipboard(currentViewUrl());
              if (!onToast) return;
              onToast(ok
                ? { tone: 'success', title: '已复制邀请链接', body: currentViewUrl() }
                : { tone: 'warn', title: '复制失败', body: '浏览器拒绝了剪贴板写入，请手动复制地址栏的链接。' });
            }} onSettings={() => stub('房间设置')} onVis={() => needsRoomPatch('可见性')} />
          : <div style={{ height: 56, paddingInline: 18, display: 'flex', alignItems: 'center', gap: 14, borderBottom: '1px solid var(--border)', background: 'var(--bg-0)' }}>
              <button onClick={() => nav({ name: 'lobby' })} className="btn-pressable" style={{ height: 28, paddingInline: 10, gap: 6, display: 'inline-flex', alignItems: 'center', background: 'transparent', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--fg-1)', cursor: 'pointer', fontSize: 12, fontWeight: 600 }}><Lu name="arrow-left" size={13} /><span className="cjk">返回大厅</span></button>
              <div style={{ flex: 1, minWidth: 0, textAlign: 'center' }}>
                <div className="cjk h-display-sm" style={{ color: 'var(--fg-3)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>房间 #{id}</div>
              </div>
              <span style={{ width: 28 }} />
            </div>}
        <div className="thp-room-body" style={{ flex: 1, minHeight: 0, display: 'flex', overflow: 'hidden' }}>
          {!room ? (
            <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              {roomStatus({ loading: isLoading, unreachable, roomId: id, onRetry: refetch, onBack: () => nav({ name: 'lobby' }) })}
            </div>
          ) : state === 'post' ? (
            <div style={{ flex: 1, overflowY: 'auto', background: 'var(--bg-0)' }}>
              <ResultsCard onRematch={() => nav({ name: 'room', id, state: 'lobby' })} onBack={() => nav({ name: 'room', id, state: 'lobby' })} />
            </div>
          ) : (
            <>
              <section className="thp-room-seats" style={{ flex: '1 1 60%', minWidth: 0, padding: '18px 20px', overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 16 }}>
                <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}>
                  <h3 className="cjk h-display-sm" style={{ margin: 0, whiteSpace: 'nowrap' }}>席位 <span className="num" style={{ color: 'var(--fg-2)', fontSize: 12, fontWeight: 600 }}>{named.length}/{seats.length}</span></h3>
                  {/* Was "主机可调整 · 拖拽换位". Nothing is draggable: the seat
                      cards have no drag handler, and reordering would need
                      PATCH /v1/rooms/{id}/seats/{idx}, which the server does not
                      mount. A caption promising a gesture is a promise the
                      client cannot keep. */}
                  <span className="cjk t-caption" style={{ color: 'var(--fg-2)', whiteSpace: 'nowrap' }}>席位顺序由服务端返回 · 暂不可换位</span>
                </div>
                <div className="thp-seat-grid">
                  {seats.length === 0 ? (
                    <UI.EmptyState
                      icon="user-plus"
                      title={unreachable ? '读不到席位' : '这个房间还没有席位'}
                      body={unreachable
                        ? '连不上服务器，席位可能已经在路上了。'
                        : '房间是空的，先邀请几个人进来。'}
                    />
                  ) : seats.map((s, i) => <SeatCard key={s.idx} seat={s} isHost={s.idx === 1} index={i} onPickRole={(role: string) => onToast && onToast({
                      tone: 'warn',
                      title: `${s.name} 暂时改不了身份`,
                      body: `改为「${role}」需要 PATCH /v1/rooms/${id}/seats/${s.idx}，服务端还没有这个接口。`,
                    })} />)}
                </div>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
                    <span className="cjk t-body" style={{ fontWeight: 600, color: 'var(--fg-1)' }}>观战席</span>
                    <span style={{ height: 1, background: 'var(--border)', flex: 1 }} />
                    <span className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>{spectators.length}</span>
                  </div>
                  {spectators.length === 0 ? (
                    <UI.EmptyState
                      icon="eye"
                      title={unreachable ? '读不到观战名单' : '还没有人观战'}
                      body={unreachable ? '连不上服务器，观战名单可能已经在路上了。' : '把这个房间的链接发出去，就能有人进来围观。'}
                    />
                  ) : (
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
                    {spectators.slice(0, 8).map((n, i) => <AvR key={i} size={26} name={n} />)}
                    {spectators.length > 8 && (
                      <span className="num" style={{ height: 26, paddingInline: 9, borderRadius: 999, background: 'var(--bg-2)', border: '1px solid var(--border)', color: 'var(--fg-1)', fontSize: 11, fontWeight: 600, display: 'inline-flex', alignItems: 'center' }}>+{spectators.length - 8}</span>
                    )}
                  </div>
                  )}
                </div>
              </section>
              <section className="thp-room-params" style={{ flex: '1 1 40%', minWidth: 320, padding: '18px 20px 18px 0', overflow: 'hidden' }}>
                <ParamPanel room={room} onBlocked={needsRoomPatch} />
              </section>
            </>
          )}
        </div>
        {room && <RoomBottomBar state={state} readyCount={readyCount} lastMessage={lastMessage} roomId={id} onStart={startMatch} onLeave={() => nav({ name: 'lobby' })} />}
      </main>
      <ChatDrawerR roomId={id} chat={chat} sysLog={sysLog} unreachable={unreachable} roomLoaded={!!room}
        onSent={() => onToast && onToast({ tone: 'success', title: '已发送', body: `#room-${id}` })}
        onFailed={(_channelId: string, error: unknown) => onToast && onToast(sendFailureToast(error))} />
    </div>
  );
}

export { Room };
