// @ts-nocheck
// Generated by Claude Design (Opus 4.7) v0.7 — Settings.

import * as React from 'react';
import * as UI from '@/components/design/ui';
import { Lu } from '@/components/design/lucide';

const { useState: useStateS } = React;
const { Button: BtnS, Tag: TagS } = UI;

const NAV = [
  { id: 'account',  label: '我的账号',     icon: 'user' },
  { id: 'profile',  label: '个人资料',     icon: 'id-card' },
  { id: 'oauth',    label: '第三方绑定',   icon: 'link' },
  { id: 'appear',   label: '外观',         icon: 'palette' },
  { id: 'lang',     label: '语言',         icon: 'languages' },
  { id: 'notif',    label: '通知',         icon: 'bell' },
  { id: 'inject',   label: '游戏注入器',   icon: 'cpu' },
  { id: 'net',      label: '网络',         icon: 'globe' },
  { id: 'kbd',      label: '快捷键',       icon: 'keyboard' },
  { id: 'about',    label: '关于',         icon: 'info' },
];

function SettingsRow({ title, desc, children }) {
  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', gap: 24, padding: '14px 0', borderTop: '1px solid var(--border)' }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{title}</div>
        {desc ? <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 3, lineHeight: 1.55 }}>{desc}</div> : null}
      </div>
      <div style={{ flexShrink: 0 }}>{children}</div>
    </div>
  );
}

function ToggleS({ on: initial, onChange }) {
  const [on, setOn] = useStateS(!!initial);
  const toggle = () => { const next = !on; setOn(next); onChange && onChange(next); };
  return (
    <span onClick={toggle} style={{
      display: 'inline-block', width: 32, height: 18, borderRadius: 999,
      background: on ? 'var(--fg-1)' : 'var(--bg-3)',
      border: '1px solid var(--border)', position: 'relative', cursor: 'pointer',
      transition: 'background var(--duration-fast) var(--ease-out-quart)',
    }}>
      <span className="toggle-thumb" style={{ position: 'absolute', top: 1, left: on ? 15 : 1, width: 14, height: 14, borderRadius: '50%', background: on ? 'var(--bg-0)' : 'var(--fg-2)' }} />
    </span>
  );
}

function ThemeSwatch({ label, dark, active, onClick }) {
  return (
    <div onClick={onClick} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
      <div style={{
        width: 88, height: 60, borderRadius: 8,
        background: dark ? '#0F0F10' : '#F8F7F4',
        border: `2px solid ${active ? 'var(--accent)' : 'var(--border)'}`,
        position: 'relative', overflow: 'hidden',
      }}>
        <div style={{ position: 'absolute', inset: 6, borderRadius: 4, background: dark ? '#1A1A1B' : '#FFFFFF', border: `1px solid ${dark ? '#2A2A2C' : '#EAE8E2'}` }}>
          <div style={{ position: 'absolute', top: 6, left: 6, right: 6, height: 5, background: dark ? '#27272A' : '#EAE8E2', borderRadius: 2 }} />
          <div style={{ position: 'absolute', top: 14, left: 6, width: 16, height: 26, background: dark ? '#27272A' : '#EAE8E2', borderRadius: 2 }} />
          <div style={{ position: 'absolute', top: 14, left: 26, right: 6, height: 4, background: dark ? '#3A3A3D' : '#D6D3CA', borderRadius: 1 }} />
          <div style={{ position: 'absolute', top: 22, left: 26, right: 12, height: 3, background: dark ? '#3A3A3D' : '#D6D3CA', borderRadius: 1 }} />
        </div>
      </div>
      <div className="cjk t-caption" style={{ fontWeight: active ? 700 : 500, color: active ? 'var(--fg-0)' : 'var(--fg-2)' }}>{label}</div>
    </div>
  );
}

function FontSwatch({ label, family, sample, active, onClick }) {
  return (
    <div onClick={onClick} style={{
      padding: 12, borderRadius: 'var(--r-md)',
      border: `1px solid ${active ? 'var(--border-strong)' : 'var(--border)'}`,
      background: active ? 'var(--bg-2)' : 'var(--bg-1)',
      cursor: 'pointer',
    }}>
      <div className="cjk" style={{ fontFamily: family, fontSize: 16, fontWeight: 600, color: 'var(--fg-0)' }}>{sample}</div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 6 }}>
        <span className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{label}</span>
        {active ? <Lu name="check" size={12} color="var(--accent)" /> : null}
      </div>
    </div>
  );
}

function OAuthRow({ name, icon, handle, connected, onToggle }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '12px 14px', background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', marginBottom: 8 }}>
      <span style={{ width: 32, height: 32, borderRadius: 6, background: 'var(--bg-2)', border: '1px solid var(--border)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: 'var(--fg-1)' }}>
        <Lu name={icon} size={15} />
      </span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{name}</div>
        {connected ? (
          <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)', marginTop: 2, display: 'inline-flex', alignItems: 'center', gap: 6 }}>
            <span style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--status-online)' }} />
            {handle}
          </div>
        ) : (
          <div className="cjk t-caption" style={{ color: 'var(--fg-3)', marginTop: 2 }}>未绑定</div>
        )}
      </div>
      {connected ? (
        <BtnS variant="ghost" size="sm" onClick={onToggle}><span className="cjk">解绑</span></BtnS>
      ) : (
        <BtnS variant="secondary" size="sm" onClick={onToggle}><span className="cjk">绑定</span></BtnS>
      )}
    </div>
  );
}

function InjectorRow({ game, version, hash, ok }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 14px', background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', marginBottom: 8 }}>
      <span className="num" style={{ width: 56, fontSize: 11.5, fontWeight: 700, color: 'var(--fg-0)' }}>{game}</span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{version}</div>
        <div className="num" style={{ fontSize: 10.5, color: 'var(--fg-2)', marginTop: 2 }}>{hash}</div>
      </div>
      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 5, fontSize: 10.5, color: ok ? 'var(--status-online)' : 'var(--status-warn)', fontWeight: 600 }}>
        <Lu name={ok ? 'check' : 'alert-triangle'} size={11} /><span className="cjk">{ok ? '已就绪' : '需要更新'}</span>
      </span>
      <BtnS variant="ghost" size="sm"><Lu name="folder" size={11} /></BtnS>
    </div>
  );
}

function PaneAccount({ onToast }: any) {
  const t = (label: string) => onToast && onToast({ tone: 'info', title: label });
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>我的账号</h2>
      <div style={{ marginTop: 16, padding: 16, background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', display: 'flex', alignItems: 'center', gap: 14 }}>
        <span style={{ width: 56, height: 56, borderRadius: 'var(--r-md)', background: 'var(--bg-2)', border: '1px solid var(--border-strong)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>
          <span className="cjk" style={{ fontSize: 22, fontWeight: 700, color: 'var(--fg-0)', fontFamily: 'var(--font-display)' }}>幽</span>
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div className="cjk h-display-md">幽幽子</div>
          <div className="num" style={{ fontSize: 12, color: 'var(--fg-2)', marginTop: 2 }}>@yuyuko · UID 4128920</div>
        </div>
        <BtnS variant="secondary" size="sm" onClick={() => t('编辑资料')}><span className="cjk">编辑资料</span></BtnS>
      </div>
      <SettingsRow title="登录邮箱" desc="用于接收登录验证码与异常通知。"><span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>y***ko@protonmail.com</span></SettingsRow>
      <SettingsRow title="手机号" desc="用作两步验证的备用渠道。"><span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>+86 138 **** 0512</span></SettingsRow>
      <SettingsRow title="两步验证" desc="启用后，每次新设备登录都需要 6 位验证码。"><ToggleS on /></SettingsRow>
      <SettingsRow title="修改密码" desc="上次更新于 2024.03.14。"><BtnS variant="ghost" size="sm" onClick={() => t('修改密码')}><span className="cjk">修改</span></BtnS></SettingsRow>
      <SettingsRow title="登出所有设备" desc="将立即终止所有客户端会话，下次登录需重新输入密码。"><BtnS variant="ghost" size="sm" style={{ color: 'var(--status-error)' }} onClick={() => t('登出所有设备')}><span className="cjk">登出全部</span></BtnS></SettingsRow>
    </>
  );
}

function PaneAppear({ onSetTheme }: any) {
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>外观</h2>
      <div style={{ marginTop: 18 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>主题</div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4 }}>跟随系统会在每天 18:00 自动切换到夜间模式。</div>
        <div style={{ display: 'flex', gap: 18, marginTop: 14 }}>
          <ThemeSwatch label="夜间" dark active onClick={() => onSetTheme && onSetTheme('dark')} />
          <ThemeSwatch label="日间" dark={false} onClick={() => onSetTheme && onSetTheme('light')} />
          <ThemeSwatch label="跟随系统" dark={false} onClick={() => onSetTheme && onSetTheme('system')} />
        </div>
      </div>
      <div style={{ marginTop: 26 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>显示字体</div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4 }}>会同时影响中文与西文。重启后生效。</div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, marginTop: 12 }}>
          <FontSwatch label="苹方 + Manrope" family="'PingFang SC', 'Microsoft YaHei', sans-serif" sample="永夜抄 Lunatic" active />
          <FontSwatch label="思源黑体" family="'Source Han Sans SC', sans-serif" sample="永夜抄 Lunatic" />
          <FontSwatch label="霞鹜文楷" family="'LXGW WenKai', serif" sample="永夜抄 Lunatic" />
        </div>
      </div>
      <SettingsRow title="字号" desc="影响所有文字。系统默认 100%。">
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
          <span className="num" style={{ fontSize: 11, color: 'var(--fg-2)' }}>A</span>
          <span style={{ width: 140, height: 4, background: 'var(--bg-2)', borderRadius: 999, position: 'relative' }}>
            <span style={{ position: 'absolute', left: 0, top: 0, height: '100%', width: '40%', background: 'var(--fg-1)', borderRadius: 999 }} />
            <span style={{ position: 'absolute', left: '40%', top: -4, width: 12, height: 12, marginLeft: -6, borderRadius: '50%', background: 'var(--bg-0)', border: '2px solid var(--fg-1)' }} />
          </span>
          <span className="num" style={{ fontSize: 14, color: 'var(--fg-2)' }}>A</span>
          <span className="num" style={{ fontSize: 11, color: 'var(--fg-1)', width: 36 }}>100%</span>
        </div>
      </SettingsRow>
      <SettingsRow title="紧凑模式" desc="减少行间距与卡片留白，更接近 Discord 经典布局。"><ToggleS on={false} /></SettingsRow>
      <SettingsRow title="减少动效" desc="启用后将关闭过渡动画与加载动画。"><ToggleS on={false} /></SettingsRow>
      <SettingsRow title="圆角风格" desc="选择卡片与按钮的圆角强度。">
        <div style={{ display: 'inline-flex', gap: 6 }}>
          {['锐利','标准','柔和'].map((l, i) => (
            <button key={l} className="btn-pressable" style={{ height: 26, paddingInline: 10, borderRadius: 6, border: '1px solid', background: i === 1 ? 'var(--bg-3)' : 'var(--bg-2)', borderColor: i === 1 ? 'var(--border-strong)' : 'var(--border)', color: i === 1 ? 'var(--fg-0)' : 'var(--fg-2)', fontSize: 11.5, fontWeight: 600, cursor: 'pointer' }}><span className="cjk">{l}</span></button>
          ))}
        </div>
      </SettingsRow>
    </>
  );
}

function PaneOAuth({ onToast }: any) {
  const t = (label: string) => onToast && onToast({ tone: 'info', title: label });
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>第三方绑定</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6 }}>绑定后好友可在对应平台搜到你，对局结束的录像可一键同步。</div>
      <div style={{ marginTop: 16 }}>
        <OAuthRow name="bilibili"     icon="play"            handle="@yuyuko_th 已绑定"      connected onToggle={() => t('解绑 bilibili')} />
        <OAuthRow name="Twitter / X"  icon="twitter"         handle="@yuyuko_phantom 已绑定" connected onToggle={() => t('解绑 Twitter')} />
        <OAuthRow name="Discord"      icon="message-circle"  handle="yuyuko#0001 已绑定"     connected onToggle={() => t('解绑 Discord')} />
        <OAuthRow name="QQ"           icon="message-square"                                      onToggle={() => t('绑定 QQ')} />
        <OAuthRow name="GitHub"       icon="github"          handle="yuyuko-th 已绑定"       connected onToggle={() => t('解绑 GitHub')} />
        <OAuthRow name="Steam"        icon="gamepad-2"                                            onToggle={() => t('绑定 Steam')} />
      </div>
    </>
  );
}

function PaneInject({ onToast }: any) {
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>游戏注入器</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6 }}>注入器负责把联机模块挂载到原版游戏上。仅在加入房间时启动，对单机存档零影响。</div>
      <div style={{ marginTop: 16, padding: 14, background: 'var(--bg-1)', border: '1px solid var(--border)', borderLeft: '2px solid var(--accent)', borderRadius: 'var(--r-md)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Lu name="cpu" size={14} color="var(--accent)" />
          <span className="t-tag" style={{ color: 'var(--accent)' }}>注入器状态</span>
          <span style={{ flex: 1 }} />
          <span className="num" style={{ fontSize: 11, color: 'var(--status-online)', fontWeight: 600 }}>v0.4.12 · 在线</span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginTop: 12 }}>
          {[['内核','UAC + Hook'],['延迟','24 ms'],['最近一次','21:04:10']].map(([k, v]) => (
            <div key={k} style={{ background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 10px' }}>
              <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{k}</div>
              <div className="num" style={{ fontSize: 12.5, color: 'var(--fg-0)', fontWeight: 600, marginTop: 2 }}>{v}</div>
            </div>
          ))}
        </div>
      </div>
      <div style={{ marginTop: 18 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>已检测到的游戏</div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4, marginBottom: 10 }}>从这些路径加载并校验哈希。点击文件夹图标可手动指定。</div>
        <InjectorRow game="TH06" version="EoSD · v1.02h" hash="sha256:4af3c…2b91" ok />
        <InjectorRow game="TH07" version="PCB · v1.00b"  hash="sha256:9b21d…4a7e" ok />
        <InjectorRow game="TH08" version="IN · v1.00d"   hash="sha256:af3c2…91d2" ok />
        <InjectorRow game="TH09" version="PoFV · v1.50a" hash="sha256:c82e1…7f0a" ok={false} />
      </div>
      <SettingsRow title="自动启动游戏" desc="加入房间后自动唤起对应游戏；关闭则需手动启动。"><ToggleS on /></SettingsRow>
      <SettingsRow title="原版存档隔离" desc="对局期间使用沙盒存档，不写入你的本地分数。"><ToggleS on /></SettingsRow>
      <SettingsRow title="详细日志" desc="将注入流程写入 ~/th-platform/logs/inject.log。"><ToggleS on={false} /></SettingsRow>
    </>
  );
}

function PaneLang() {
  const langs = [
    { code: 'zh-CN', label: '简体中文', sub: '中国大陆 · 默认' },
    { code: 'zh-TW', label: '繁體中文', sub: '台灣 · 香港' },
    { code: 'ja-JP', label: '日本語',   sub: '東方 Project 的母语' },
    { code: 'en-US', label: 'English',  sub: 'United States' },
    { code: 'ko-KR', label: '한국어',   sub: '대한민국' },
  ];
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>语言</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6 }}>影响界面文字、日期格式与默认大厅排序。游戏内文本由原版决定。</div>
      <div style={{ marginTop: 16 }}>
        {langs.map((l, i) => (
          <button key={l.code} className="btn-pressable" style={{
            width: '100%', textAlign: 'left',
            display: 'flex', alignItems: 'center', gap: 14,
            padding: '12px 14px',
            background: i === 0 ? 'var(--bg-2)' : 'var(--bg-1)',
            border: '1px solid', borderColor: i === 0 ? 'var(--border-strong)' : 'var(--border)',
            borderRadius: 'var(--r-md)', marginBottom: 8, cursor: 'pointer',
          }}>
            <span className="num" style={{ width: 56, fontSize: 11, color: 'var(--fg-2)' }}>{l.code}</span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{l.label}</div>
              <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 2 }}>{l.sub}</div>
            </div>
            {i === 0 ? <Lu name="check" size={13} color="var(--accent)" /> : null}
          </button>
        ))}
      </div>
      <SettingsRow title="日期格式" desc="影响录像列表与对局历史。">
        <div style={{ display: 'inline-flex', gap: 6 }}>
          {['YYYY-MM-DD','MM/DD/YYYY','DD.MM.YYYY'].map((f, i) => (
            <button key={f} className="btn-pressable" style={{ height: 26, paddingInline: 10, borderRadius: 6, border: '1px solid', background: i === 0 ? 'var(--bg-3)' : 'var(--bg-2)', borderColor: i === 0 ? 'var(--border-strong)' : 'var(--border)', color: i === 0 ? 'var(--fg-0)' : 'var(--fg-2)', fontSize: 11, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-mono)' }}>{f}</button>
          ))}
        </div>
      </SettingsRow>
      <SettingsRow title="协助翻译" desc="去 GitHub 仓库提交术语建议或新增语言。"><BtnS variant="ghost" size="sm"><Lu name="external-link" size={11} /><span className="cjk" style={{ marginLeft: 4 }}>打开</span></BtnS></SettingsRow>
    </>
  );
}

function PaneStub({ title }: any) {
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>{title}</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 24, padding: 40, background: 'var(--bg-1)', border: '1px dashed var(--border-strong)', borderRadius: 'var(--r-md)', textAlign: 'center' }}>
        该章节正在搭建中，下次 Claude Design 续 prompt 时会补齐。
      </div>
    </>
  );
}

type SettingsProps = {
  theme?: 'dark' | 'light';
  section?: string;
  onClose?: () => void;
  onSetTheme?: (t: string) => void;
  onToast?: (msg: { tone?: string; title: string; body?: string }) => void;
};

function Settings({ theme = 'dark', section = 'appear', onClose, onSetTheme, onToast }: SettingsProps) {
  const [active, setActive] = useStateS(section);
  const navItem = NAV.find(n => n.id === active);
  const Pane = active === 'account' ? <PaneAccount onToast={onToast} />
    : active === 'oauth' ? <PaneOAuth onToast={onToast} />
    : active === 'inject' ? <PaneInject onToast={onToast} />
    : active === 'lang' ? <PaneLang />
    : active === 'appear' ? <PaneAppear onSetTheme={onSetTheme} />
    : <PaneStub title={navItem ? navItem.label : '设置'} />;
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)' }}>
      <aside style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
        <div style={{ padding: '14px 16px 10px' }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>设置</div>
        </div>
        <div style={{ padding: '4px 10px', overflowY: 'auto', flex: 1 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            {NAV.slice(0, 3).map(n => (
              <button key={n.id} onClick={() => setActive(n.id)} className="btn-pressable row-hoverable" style={{
                width: '100%', textAlign: 'left',
                display: 'flex', alignItems: 'center', gap: 10,
                height: 30, paddingInline: 10, borderRadius: 6, border: 'none',
                background: active === n.id ? 'var(--bg-2)' : 'transparent',
                color: active === n.id ? 'var(--fg-0)' : 'var(--fg-1)',
                cursor: 'pointer',
              }}>
                <Lu name={n.icon} size={13} color={active === n.id ? 'var(--fg-0)' : 'var(--fg-2)'} />
                <span className="cjk t-body" style={{ fontWeight: active === n.id ? 600 : 500 }}>{n.label}</span>
              </button>
            ))}
          </div>
          <div style={{ height: 1, background: 'var(--border)', margin: '10px 4px' }} />
          <div className="t-tag" style={{ color: 'var(--fg-2)', paddingLeft: 6, marginBottom: 4 }}>应用</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            {NAV.slice(3, 10).map(n => (
              <button key={n.id} onClick={() => setActive(n.id)} className="btn-pressable row-hoverable" style={{
                width: '100%', textAlign: 'left',
                display: 'flex', alignItems: 'center', gap: 10,
                height: 30, paddingInline: 10, borderRadius: 6, border: 'none',
                background: active === n.id ? 'var(--bg-2)' : 'transparent',
                color: active === n.id ? 'var(--fg-0)' : 'var(--fg-1)',
                cursor: 'pointer',
              }}>
                <Lu name={n.icon} size={13} color={active === n.id ? 'var(--fg-0)' : 'var(--fg-2)'} />
                <span className="cjk t-body" style={{ fontWeight: active === n.id ? 600 : 500 }}>{n.label}</span>
              </button>
            ))}
          </div>
          <div style={{ height: 1, background: 'var(--border)', margin: '10px 4px' }} />
          <button onClick={() => onToast && onToast({ tone: 'warn', title: '退出登录', body: '点击确认按钮以确认（暂未实现）' })} className="btn-pressable" style={{ width: '100%', textAlign: 'left', display: 'flex', alignItems: 'center', gap: 10, height: 30, paddingInline: 10, borderRadius: 6, border: 'none', background: 'transparent', color: 'var(--status-error)', cursor: 'pointer' }}>
            <Lu name="log-out" size={13} color="var(--status-error)" />
            <span className="cjk t-body" style={{ fontWeight: 500 }}>退出登录</span>
          </button>
        </div>
        <div style={{ padding: 10, borderTop: '1px solid var(--border)' }}>
          <div className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>TH-Platform v0.7.0 · build 2026.04.26</div>
        </div>
      </aside>
      <main style={{ flex: 1, minWidth: 0, overflowY: 'auto', background: 'var(--bg-0)', position: 'relative' }}>
        <button title="关闭" onClick={onClose} className="btn-pressable" style={{ position: 'absolute', top: 16, right: 20, width: 32, height: 32, borderRadius: 8, border: '1px solid var(--border)', background: 'var(--bg-1)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', zIndex: 2 }}>
          <Lu name="x" size={14} />
          <span style={{ position: 'absolute', top: 36, fontSize: 9, color: 'var(--fg-3)', fontFamily: 'var(--font-mono)', fontWeight: 600, letterSpacing: '0.05em' }}>ESC</span>
        </button>
        <div style={{ maxWidth: 720, padding: '32px 36px 60px' }}>
          {Pane}
        </div>
      </main>
    </div>
  );
}

export { Settings };
