// Generated by Claude Design (Opus 4.7) v0.7 — Settings.
//
// The rule this page now follows, after a sweep of every control on it:
//
//   A control either does the thing it looks like it does, or it is visibly
//   unavailable with the reason on it. There is no third option.
//
// The three failure modes this file used to contain, all of which survived a
// green `tsc -b` and a green `vite build`:
//
//   1. DISPLAYED VALUES THAT WERE NEVER TRUE. The account pane asserted an
//      email address, a phone number, a two-step-verification setting and a
//      last-changed date. The OAuth pane listed four accounts "bound" with live
//      handles. The injector pane reported a version, a latency, an injection
//      time, a DLL SHA-256 and an integrity score of 98/100, and listed four
//      games "detected". None of that came from anywhere: the server has no
//      account, OAuth, or integrity routes, the client scans no disk, and it
//      cannot hash a DLL from a web view.
//   2. CONTROLS THAT CHANGED NOTHING. Three font swatches with no onClick, a
//      font-size "slider" drawn as divs that always read 100%, and four
//      switches (紧凑模式 / 减少动效 / 自动启动游戏 / 原版存档隔离) that flipped a
//      local boolean and were forgotten on reload. These are now real
//      preferences, applied to <html> and persisted (src/lib/prefs.ts), or they
//      are disabled with what is missing.
//   3. A SECTION THAT SHOWED THE WRONG STUB. 个人资料 / 通知 / 网络 had honest
//      "not yet" copy; 快捷键 and 关于 fell through to the same PaneStub and
//      rendered "个人资料还没有开放" under a 关于 heading. 关于 now reports what
//      this build actually talks to.

import * as React from 'react';
import type { Resolved, Theme } from '@/lib/theme';
import type { RadiusStyle } from '@/lib/radius';
import { useRadius } from '@/lib/radius';
import { FONTS, SCALES, isFontAvailable, usePrefs, type FontChoice } from '@/lib/prefs';
import { API_BASE_URL, API_HANDLE } from '@/lib/api/client';
import { useMe } from '@/hooks';
import { isTauri } from '@/lib/tauri/loader';
import { useBackendReachable } from '@/components/backend-status';
import { Unavailable, UnavailablePanel } from '@/components/unavailable';
import { StatusDot } from '@/components/design/shared';
import * as UI from '@/components/design/ui';
import { Lu } from '@/components/design/lucide';

const { useState: useStateS } = React;
const { Button: BtnS } = UI;

const NAV = [
  { id: 'account',  label: '我的账号',     icon: 'user' },
  { id: 'profile',  label: '个人资料',     icon: 'id-card' },
  { id: 'oauth',    label: '第三方绑定',   icon: 'link' },
  { id: 'appear',   label: '外观',         icon: 'palette' },
  { id: 'lang',     label: '语言',         icon: 'languages' },
  { id: 'notif',    label: '通知',         icon: 'bell' },
  { id: 'inject',   label: '游戏注入器',   icon: 'cpu' },
  { id: 'net',      label: '网络',         icon: 'globe' },
  { id: 'kbd',      label: '快捷键',       icon: 'keyboard' },
  { id: 'about',    label: '关于',         icon: 'info' },
];

function SettingsRow({ title, desc, children }: { title: React.ReactNode; desc?: React.ReactNode; children?: React.ReactNode }) {
  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', gap: 24, padding: '14px 0', borderTop: '1px solid var(--border)' }}>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>{title}</div>
        {desc ? <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 3, lineHeight: 1.55 }}>{desc}</div> : null}
      </div>
      <div style={{ flexShrink: 0 }}>{children}</div>
    </div>
  );
}

/**
 * A switch that really switches.
 *
 * It used to hold its own `useState` seeded from a prop and never report the
 * change anywhere, so "紧凑模式" and "减少动效" flipped for as long as the pane
 * stayed mounted and reverted on the next visit — a settings page that displayed
 * a value without applying it. State now lives in the preference store, and the
 * control only renders a switch when the value is one the client can actually
 * hold. `locked` renders a read-only value with a reason instead, for the
 * settings that live on the server or in the DLL.
 */
function ToggleS({ on, onChange, lockedReason }: {
  on: boolean;
  onChange?: (next: boolean) => void;
  lockedReason?: string;
}) {
  const track = (
    <span
      role="switch"
      aria-checked={on}
      tabIndex={lockedReason ? -1 : 0}
      onClick={() => { if (!lockedReason) onChange?.(!on); }}
      onKeyDown={(e) => {
        if (lockedReason) return;
        if (e.key === ' ' || e.key === 'Enter') { e.preventDefault(); onChange?.(!on); }
      }}
      style={{
        display: 'inline-block', width: 32, height: 18, borderRadius: 999,
        background: on ? 'var(--fg-1)' : 'var(--bg-3)',
        border: '1px solid var(--border)', position: 'relative',
        cursor: lockedReason ? 'not-allowed' : 'pointer',
        opacity: lockedReason ? 0.5 : 1,
        transition: 'background var(--duration-fast) var(--ease-out-quart)',
      }}
    >
      <span className="toggle-thumb" style={{
        position: 'absolute', top: 1, left: on ? 15 : 1, width: 14, height: 14,
        borderRadius: '50%', background: on ? 'var(--bg-0)' : 'var(--fg-2)',
      }} />
    </span>
  );
  return lockedReason ? <Unavailable reason={lockedReason}>{track}</Unavailable> : track;
}

function ThemeSwatch({ label, dark, active, onClick }: { label: string; dark: boolean; active?: boolean; onClick?: () => void }) {
  return (
    <div onClick={onClick} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, cursor: 'pointer' }}>
      <div style={{
        width: 88, height: 60, borderRadius: 8,
        background: dark ? '#0F0F10' : '#F8F7F4',
        border: `2px solid ${active ? 'var(--accent)' : 'var(--border)'}`,
        position: 'relative', overflow: 'hidden',
      }}>
        <div style={{ position: 'absolute', inset: 6, borderRadius: 4, background: dark ? '#1A1A1B' : '#FFFFFF', border: `1px solid ${dark ? '#2A2A2C' : '#EAE8E2'}` }}>
          <div style={{ position: 'absolute', top: 6, left: 6, right: 6, height: 5, background: dark ? '#27272A' : '#EAE8E2', borderRadius: 2 }} />
          <div style={{ position: 'absolute', top: 14, left: 6, width: 16, height: 26, background: dark ? '#27272A' : '#EAE8E2', borderRadius: 2 }} />
          <div style={{ position: 'absolute', top: 14, left: 26, right: 6, height: 4, background: dark ? '#3A3A3D' : '#D6D3CA', borderRadius: 1 }} />
          <div style={{ position: 'absolute', top: 22, left: 26, right: 12, height: 3, background: dark ? '#3A3A3D' : '#D6D3CA', borderRadius: 1 }} />
        </div>
      </div>
      <div className="cjk t-caption" style={{ fontWeight: active ? 700 : 500, color: active ? 'var(--fg-0)' : 'var(--fg-2)' }}>{label}</div>
    </div>
  );
}

/**
 * A font swatch that knows whether the font exists.
 *
 * These three were the clearest case of a control that looks live and does
 * nothing: no onClick on any of them, and `active` was a literal on the first.
 * The two non-default stacks name fonts that are not guaranteed to be installed,
 * and picking an absent font renders the same glyphs — a click that appears to
 * fail. `fontAvailable` asks the browser instead, so a missing font is shown
 * missing rather than accepted.
 */
function FontSwatch({ choice, active, onPick }: {
  choice: FontChoice;
  active: boolean;
  onPick: (choice: FontChoice) => void;
}) {
  const font = FONTS[choice];
  const available = isFontAvailable(font.family);

  const card = (
    <div style={{
      padding: 12, borderRadius: 'var(--r-md)',
      border: `1px solid ${active ? 'var(--border-strong)' : 'var(--border)'}`,
      background: active ? 'var(--bg-2)' : 'var(--bg-1)',
      cursor: available ? 'pointer' : 'not-allowed',
    }}>
      <div className="cjk" style={{ fontFamily: font.family, fontSize: 16, fontWeight: 600, color: 'var(--fg-0)' }}>{font.sample}</div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 6, marginTop: 6 }}>
        <span className="cjk t-caption" style={{ color: available ? 'var(--fg-2)' : 'var(--fg-3)' }}>
          {available ? font.label : `${font.label} · 本机未安装`}
        </span>
        {active ? <Lu name="check" size={12} color="var(--accent)" /> : null}
      </div>
    </div>
  );
  return available ? (
    <div onClick={() => onPick(choice)}>{card}</div>
  ) : (
    <Unavailable reason={`本机没有安装 ${font.label}。装上之后这个选项会立刻可用。`}>{card}</Unavailable>
  );
}

// ---------- 我的账号 ----------

function PaneAccount() {
  const { data: me, isLoading, error, refetch } = useMe();
  const identity = `请求头 X-Handle: ${API_HANDLE}`;
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>我的账号</h2>
      <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 6, lineHeight: 1.6 }}>
        这一轮没有登录。身份是每个请求上的 <span className="num">X-Handle</span> 头，
        服务端按它区分玩家——所以下面每一行都是从 <span className="num">GET /v1/me</span> 读来的，
        不是本地存的一串假数据。
      </div>

      <div style={{ marginTop: 16, padding: 16, background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', display: 'flex', alignItems: 'center', gap: 14 }}>
        <span style={{ width: 56, height: 56, borderRadius: 'var(--r-md)', background: 'var(--bg-2)', border: '1px solid var(--border-strong)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>
          <span className="cjk" style={{ fontSize: 22, fontWeight: 700, color: 'var(--fg-0)', fontFamily: 'var(--font-display)' }}>
            {me ? me.name.slice(0, 1) : '—'}
          </span>
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div className="cjk h-display-md">{me ? me.name : isLoading ? '正在读取…' : '读不到'}</div>
          <div className="num" style={{ fontSize: 12, color: 'var(--fg-2)', marginTop: 2 }}>
            {me ? `@${me.handle}${me.uid ? ` · UID ${me.uid}` : ''}` : error ? error.message : identity}
          </div>
        </div>
        <Unavailable reason="修改资料需要 PATCH /v1/me。服务端目前只有 GET /v1/me，没有写入接口。">
          <BtnS variant="secondary" size="sm" disabled><span className="cjk">编辑资料</span></BtnS>
        </Unavailable>
      </div>

      {me ? (
        <>
          <SettingsRow title="状态" desc="服务端记录的在线状态。">
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 12, color: 'var(--fg-1)' }}>
              <UI.Avatar size={18} name={me.name} status={me.status} />
              <span className="cjk">{me.presence}</span>
            </span>
          </SettingsRow>
          <SettingsRow title="注册时间" desc="服务端记录的 joined 日期。">
            <span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>{me.joined}</span>
          </SettingsRow>
          <SettingsRow title="称谓" desc="服务端记录的 pronoun 字段。">
            <span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>{me.pronoun}</span>
          </SettingsRow>
        </>
      ) : (
        <div style={{ marginTop: 16 }}>
          <UI.EmptyState
            icon={isLoading ? 'loader' : 'unplug'}
            title={isLoading ? '正在读取 /v1/me' : '读不到账号信息'}
            body={error ? error.message : '服务端没有回答，请确认它已启动。'}
            action={isLoading ? null : (
              <BtnS variant="primary" size="md" onClick={refetch}>
                <Lu name="refresh-cw" size={12} />
                <span className="cjk" style={{ marginLeft: 6 }}>重试</span>
              </BtnS>
            )}
          />
        </div>
      )}

      <SettingsRow title="登录邮箱 / 手机号" desc="本轮没有账号体系，服务端不存这些字段。">
        <span className="cjk t-caption" style={{ color: 'var(--fg-3)' }}>服务端未提供</span>
      </SettingsRow>
      <SettingsRow title="两步验证" desc="启用后，每次新设备登录都需要 6 位验证码。">
        <ToggleS on={false} lockedReason="两步验证是服务端账号能力，需要 /v1/auth 这套接口；本轮的身份只是一个请求头。" />
      </SettingsRow>
      <SettingsRow title="修改密码" desc="没有密码可改——登录尚未实现。">
        <Unavailable reason="需要 /v1/auth 下的密码接口；本轮的身份是 X-Handle 请求头，没有密码。">
          <BtnS variant="ghost" size="sm" disabled><span className="cjk">修改</span></BtnS>
        </Unavailable>
      </SettingsRow>
      <SettingsRow title="登出所有设备" desc="没有会话可以终止。">
        <Unavailable reason="没有会话：本轮没有登录，令牌就是一个请求头，清不掉任何东西。">
          <BtnS variant="ghost" size="sm" disabled style={{ color: 'var(--status-error)' }}><span className="cjk">登出全部</span></BtnS>
        </Unavailable>
      </SettingsRow>
    </>
  );
}

// ---------- 外观 ----------

function PaneAppear({ theme, onSetTheme }: { theme: Theme; onSetTheme?: (t: Theme) => void }) {
  const [radius, setRadius] = useRadius();
  const [prefs, setPrefs] = usePrefs();
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>外观</h2>
      <div style={{ marginTop: 18 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>主题</div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4 }}>
          立即生效并记住你的选择。跟随系统只跟随系统的深浅色，不会按时间自动切换。
        </div>
        <div style={{ display: 'flex', gap: 18, marginTop: 14 }}>
          {/* `active` used to be a literal on the 夜间 swatch, so the selection
              ring stayed on 夜间 no matter which theme was in use. */}
          <ThemeSwatch label="夜间" dark active={theme === 'dark'} onClick={() => onSetTheme?.('dark')} />
          <ThemeSwatch label="日间" dark={false} active={theme === 'light'} onClick={() => onSetTheme?.('light')} />
          <ThemeSwatch label="跟随系统" dark={false} active={theme === 'system'} onClick={() => onSetTheme?.('system')} />
        </div>
      </div>

      <div style={{ marginTop: 26 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>显示字体</div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4 }}>
          立即生效并记住你的选择。切换到本机没装的字体不会有任何变化，所以没装的会标出来。
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, marginTop: 12 }}>
          {(Object.keys(FONTS) as FontChoice[]).map((choice) => (
            <FontSwatch key={choice} choice={choice} active={prefs.font === choice} onPick={(c) => setPrefs({ font: c })} />
          ))}
        </div>
      </div>

      <SettingsRow title="字号" desc="缩放整套文字（标题、正文、标签）。立即生效，刷新后保留。">
        <div style={{ display: 'inline-flex', gap: 6 }}>
          {SCALES.map((s) => (
            <button
              key={s}
              aria-pressed={prefs.scale === s}
              onClick={() => setPrefs({ scale: s })}
              className="btn-pressable"
              style={{
                minWidth: 52, height: 26, paddingInline: 8, borderRadius: 6, border: '1px solid',
                background: prefs.scale === s ? 'var(--bg-3)' : 'var(--bg-2)',
                borderColor: prefs.scale === s ? 'var(--border-strong)' : 'var(--border)',
                color: prefs.scale === s ? 'var(--fg-0)' : 'var(--fg-2)',
                fontSize: 11.5, fontWeight: 600, cursor: 'pointer',
              }}
            >
              <span className="num">{s}%</span>
            </button>
          ))}
        </div>
      </SettingsRow>

      <SettingsRow title="紧凑模式" desc="收紧行高和列表进场间隔，一屏能多看几行。立即生效，刷新后保留。">
        <ToggleS on={prefs.compact} onChange={(compact) => setPrefs({ compact })} />
      </SettingsRow>
      <SettingsRow title="减少动效" desc="关掉过渡与加载动画。立即生效，刷新后保留。">
        <ToggleS on={prefs.reduceMotion} onChange={(reduceMotion) => setPrefs({ reduceMotion })} />
      </SettingsRow>
      <SettingsRow title="圆角风格" desc="选择卡片与按钮的圆角强度。立即生效，并记住你的选择。">
        <div style={{ display: 'inline-flex', gap: 6 }}>
          {([['锐利','sharp'],['标准','standard'],['柔和','soft']] as const).map(([label, value]) => (
            <button
              key={value}
              aria-pressed={radius === value}
              onClick={() => setRadius(value as RadiusStyle)}
              className="btn-pressable"
              style={{
                height: 26, paddingInline: 10, borderRadius: 6, border: '1px solid',
                background: radius === value ? 'var(--bg-3)' : 'var(--bg-2)',
                borderColor: radius === value ? 'var(--border-strong)' : 'var(--border)',
                color: radius === value ? 'var(--fg-0)' : 'var(--fg-2)',
                fontSize: 11.5, fontWeight: 600, cursor: 'pointer',
              }}
            ><span className="cjk">{label}</span></button>
          ))}
        </div>
      </SettingsRow>
    </>
  );
}

// ---------- 游戏注入器 ----------

/** The one path the Tauri shell is configured with, or '' when unset. */
const TH08_EXE = import.meta.env.VITE_GAME_PATH_TH08 ?? '';
const PLATFORM_DLL = import.meta.env.VITE_DLL_PATH ?? '';

function PaneInject() {
  // Everything this pane can say that is true. The version string, the 24 ms
  // latency, the injection timestamp, the four SHA-256 prefixes and the 98/100
  // integrity score it used to render were literals: there is no endpoint that
  // produces any of them, no disk scan, and a web view cannot hash a file.
  const rows: { label: string; value: string; ok: boolean }[] = [
    { label: '桌面外壳 (Tauri)', value: isTauri() ? '已加载' : '未加载（当前是浏览器）', ok: isTauri() },
    { label: '游戏路径 VITE_GAME_PATH_TH08', value: TH08_EXE || '未配置', ok: !!TH08_EXE },
    { label: '联机模块 VITE_DLL_PATH', value: PLATFORM_DLL || '未配置', ok: !!PLATFORM_DLL },
  ];
  const ready = rows.every((r) => r.ok);
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>游戏注入器</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6, lineHeight: 1.65 }}>
        注入器负责把联机模块挂到原版游戏上。目前只随房间页的「开始对局」启动，
        不驻留、不改单机存档。下面是启动前真正会被检查的三件事。
      </div>

      <div style={{ marginTop: 16, padding: 14, background: 'var(--bg-1)', border: '1px solid var(--border)', borderLeft: `2px solid ${ready ? 'var(--accent)' : 'var(--border-strong)'}`, borderRadius: 'var(--r-md)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <Lu name={ready ? 'check' : 'alert-triangle'} size={14} color={ready ? 'var(--status-online)' : 'var(--status-warn)'} />
          <span className="t-tag" style={{ color: ready ? 'var(--status-online)' : 'var(--status-warn)' }}>
            {ready ? '可以启动' : '还不能启动'}
          </span>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginTop: 12 }}>
          {rows.map((r) => (
            <div key={r.label} style={{ background: 'var(--bg-2)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 10px', minWidth: 0 }}>
              <div className="cjk t-caption" style={{ color: 'var(--fg-2)' }}>{r.label}</div>
              <div className="num" style={{
                fontSize: 12, fontWeight: 600, marginTop: 2,
                color: r.ok ? 'var(--fg-0)' : 'var(--status-warn)',
                overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
              }} title={r.value}>{r.value}</div>
            </div>
          ))}
        </div>
      </div>

      <div style={{ marginTop: 18 }}>
        <div className="cjk t-body-lg" style={{ color: 'var(--fg-0)' }}>支持的游戏</div>
        <div className="cjk t-caption" style={{ color: 'var(--fg-2)', marginTop: 4, marginBottom: 10, lineHeight: 1.6 }}>
          注入器不扫描磁盘，也不校验哈希——它只按上面配好的路径启动。
          下列四作里目前只有 TH08 接了路径配置。
        </div>
        {[
          { id: 'TH06', note: '未配置路径' },
          { id: 'TH07', note: '未配置路径' },
          { id: 'TH08', note: TH08_EXE ? TH08_EXE : '未配置路径' },
          { id: 'TH09', note: '未配置路径' },
        ].map((g) => (
          <div key={g.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 14px', background: 'var(--bg-1)', border: '1px solid var(--border)', borderRadius: 'var(--r-md)', marginBottom: 8 }}>
            <span className="num" style={{ width: 56, fontSize: 11.5, fontWeight: 700, color: 'var(--fg-0)' }}>{g.id}</span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div className="cjk t-body-lg" style={{ color: 'var(--fg-1)' }}>{g.note}</div>
            </div>
            <Unavailable reason="没有文件选择器：Tauri 侧只有 launch_game / terminate_game 两个命令，没有打开目录对话框的命令。">
              <BtnS variant="ghost" size="sm" disabled><Lu name="folder" size={11} /></BtnS>
            </Unavailable>
          </div>
        ))}
      </div>

      <SettingsRow title="自动启动游戏" desc="加入房间后自动唤起对应游戏。">
        <ToggleS on={false} lockedReason="启动游戏由房间页的「开始对局」按钮触发，没有房间级的自动启动开关，也没有房间字段存它。" />
      </SettingsRow>
      <SettingsRow title="原版存档隔离" desc="对局期间使用沙盒存档。">
        <ToggleS on={false} lockedReason="存档隔离由 DLL 里的 TH08_PLATFORM_* 环境变量控制，不是客户端偏好，界面上关不掉它。" />
      </SettingsRow>
      <SettingsRow title="详细日志" desc="把注入流程写进日志文件。">
        <ToggleS on={false} lockedReason="日志由 loader 写进 %LOCALAPPDATA%\\th08_platform\\，由 DLL 的环境变量控制，不是客户端偏好。" />
      </SettingsRow>
    </>
  );
}

// ---------- 快捷键 ----------

function PaneShortcuts() {
  // Only the bindings that are actually installed. The pane used to fall
  // through to the 个人资料 stub, so 快捷键 rendered a paragraph about editing
  // your nickname.
  const bindings: { keys: string; what: string }[] = [
    { keys: 'Esc', what: '关闭设置' },
    { keys: 'Enter', what: '在聊天输入框里发送消息' },
    { keys: 'Shift + Enter', what: '在聊天输入框里换行' },
    { keys: '⌘K / Ctrl+K', what: '跳到大厅的搜索框' },
  ];
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>快捷键</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6 }}>
        下面是目前真的装在客户端里的按键。
      </div>
      <div style={{ marginTop: 16, border: '1px solid var(--border)', borderRadius: 'var(--r-md)', overflow: 'hidden' }}>
        {bindings.map((b, i) => (
          <div key={b.keys} style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16,
            padding: '10px 14px', background: i % 2 ? 'var(--bg-2)' : 'var(--bg-1)',
            borderTop: i === 0 ? 'none' : '1px solid var(--border)',
          }}>
            <span className="cjk t-body" style={{ color: 'var(--fg-1)' }}>{b.what}</span>
            <span className="num" style={{ fontSize: 11.5, color: 'var(--fg-0)', fontWeight: 600 }}>{b.keys}</span>
          </div>
        ))}
      </div>
      <UnavailablePanel
        title="自定义按键还没有开放"
        missing={<>需要一套可持久化的按键绑定表，并且所有页面都要走同一份绑定；目前这几条是各自写在组件里的。</>}
      />
    </>
  );
}

// ---------- 关于 ----------

function PaneAbout() {
  const reachable = useBackendReachable();
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>关于</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6, lineHeight: 1.65 }}>
        下面是这份客户端此刻真正知道的事情。没有编造的版本号和构建日期。
      </div>
      <SettingsRow title="后端地址" desc="api/client.ts 解析出来的 VITE_API_BASE_URL。">
        <span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>{API_BASE_URL}</span>
      </SettingsRow>
      <SettingsRow title="身份" desc="每个请求都带的 VITE_HANDLE。">
        <span className="num" style={{ fontSize: 12, color: 'var(--fg-1)' }}>{API_HANDLE}</span>
      </SettingsRow>
      <SettingsRow title="后端连通性" desc="探测 /healthz，10 秒一次。">
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 12, fontWeight: 600, color: reachable === 'up' ? 'var(--status-online)' : reachable === 'down' ? 'var(--status-warn)' : 'var(--fg-2)' }}>
          <StatusDot status={reachable === 'up' ? 'online' : reachable === 'down' ? 'idle' : 'offline'} />
          {reachable === 'up' ? '在线' : reachable === 'down' ? '连不上' : '正在探测'}
        </span>
      </SettingsRow>
      <SettingsRow title="桌面外壳" desc="启动游戏需要 Tauri 壳；浏览器里只能用浏览器的部分。">
        <span className="num" style={{ fontSize: 12, color: isTauri() ? 'var(--fg-0)' : 'var(--fg-2)' }}>
          {isTauri() ? 'Tauri' : '浏览器'}
        </span>
      </SettingsRow>
      <UnavailablePanel
        title="版本号还没有接进来"
        missing={<>服务端有 <span className="num">GET /v1/version</span>，客户端目前没有读它（AGENTS.md 第 6 节的客户端函数表里没有这一条），所以这里不写版本号。</>}
      />
    </>
  );
}

/**
 * A settings section that has no implementation yet.
 *
 * The copy used to be "该章节正在搭建中，下次 Claude Design 续 prompt 时会补齐。"
 * — a note addressed to the next person authoring the file, shipped to the user
 * on three of the ten sections. It is the single most demo-looking string in
 * the app and it says nothing about the product. Each section now states, in the
 * user's terms, that it is not available yet and exactly which server route is
 * missing.
 */
function PaneStub({ title, reason }: { title: string; reason: StubReason }) {
  return (
    <>
      <h2 className="cjk h-display-md" style={{ margin: 0 }}>{title}</h2>
      <div className="cjk t-body" style={{ color: 'var(--fg-2)', marginTop: 6 }}>{reason.desc}</div>
      <UnavailablePanel title={`${title}还没有开放`} missing={reason.pending} />
    </>
  );
}

type StubReason = { desc: React.ReactNode; pending: React.ReactNode };

const STUB_REASONS: Record<string, StubReason> = {
  profile: {
    desc: '编辑昵称、pronoun、在线状态与个人简介。',
    pending: '需要一个 PATCH /v1/me 来保存修改，服务端目前只有 GET /v1/me。',
  },
  oauth: {
    desc: '把第三方账号绑到平台上，好友能在对应平台搜到你。',
    pending: <>本轮没有登录，也没有账号表。这个页签过去列了四个「已绑定」的账号和它们的 handle——那些数据不存在，服务端没有 OAuth 表单，客户端也没有发起过任何绑定。</>,
  },
  lang: {
    desc: '界面语言、日期格式与默认大厅排序。',
    pending: <>整个界面的文案是写死在组件里的中文，没有 i18n 层，也没有语言偏好能存的地方。选一种语言需要先把文案抽出来，再加一个能持久化语言设置的服务端字段。</>,
  },
  notify: {
    desc: '房间开局、好友上线、群组 @ 提及时是否提醒你。',
    pending: '需要服务端为每个频道落库未读与订阅状态，并把 /ws/channels/{id} 接上。',
  },
  net: {
    desc: '端口、代理与区域选择。联机走 P2P 直连，客户端之间不经服务器中转。',
    pending: '需要每个房间真实下发 endpoint，现在 GET /v1/rooms 只有 seed 里的样例值。',
  },
};

type SettingsProps = {
  /** The resolved theme, used for the `theme-*` class. Only ever dark|light. */
  theme?: Resolved;
  /** What the user actually picked, including 'system'. Drives the swatches. */
  selectedTheme?: Theme;
  section?: string;
  onClose?: () => void;
  onSetTheme?: (t: Theme) => void;
  /** Keeps the active section in the URL, so 刷新 and 后退 work. */
  onSection?: (section: string) => void;
};

function Settings({ theme = 'dark', selectedTheme = 'system', section = 'appear', onClose, onSetTheme, onSection }: SettingsProps) {
  const [active, setActive] = useStateS(section);
  // The pane used to seed its state from `section` once and never look again,
  // so a URL change — a deep link, the browser back button, another pane
  // linking here — left the previous section on screen under a new address.
  React.useEffect(() => { setActive(section); }, [section]);
  const navItem = NAV.find((n) => n.id === active);
  const pick = (id: string) => { setActive(id); onSection?.(id); };
  const Pane = active === 'account' ? <PaneAccount />
    : active === 'appear' ? <PaneAppear theme={selectedTheme} onSetTheme={onSetTheme} />
    : active === 'inject' ? <PaneInject />
    : active === 'kbd' ? <PaneShortcuts />
    : active === 'about' ? <PaneAbout />
    : <PaneStub title={navItem ? navItem.label : '设置'} reason={STUB_REASONS[active] ?? STUB_REASONS.profile} />;
  return (
    <div className={`thp theme-${theme} anim-page-in`} style={{ width: '100%', height: '100%', display: 'flex', background: 'var(--bg-0)', overflow: 'hidden', borderRadius: 'var(--r-lg)' }}>
      <aside className="thp-col-nav" style={{ width: 240, background: 'var(--bg-1)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '14px 16px 10px' }}>
          <div className="t-tag" style={{ color: 'var(--fg-2)' }}>设置</div>
        </div>
        <div style={{ padding: '4px 10px', overflowY: 'auto', flex: 1 }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            {NAV.slice(0, 3).map((n) => (
              <button key={n.id} onClick={() => pick(n.id)} aria-current={active === n.id} className="btn-pressable row-hoverable" style={{
                width: '100%', textAlign: 'left',
                display: 'flex', alignItems: 'center', gap: 10,
                height: 30, paddingInline: 10, borderRadius: 6, border: 'none',
                background: active === n.id ? 'var(--bg-2)' : 'transparent',
                color: active === n.id ? 'var(--fg-0)' : 'var(--fg-1)',
                cursor: 'pointer',
              }}>
                <Lu name={n.icon} size={13} color={active === n.id ? 'var(--fg-0)' : 'var(--fg-2)'} />
                <span className="cjk t-body" style={{ fontWeight: active === n.id ? 600 : 500 }}>{n.label}</span>
              </button>
            ))}
          </div>
          <div style={{ height: 1, background: 'var(--border)', margin: '10px 4px' }} />
          <div className="t-tag" style={{ color: 'var(--fg-2)', paddingLeft: 6, marginBottom: 4 }}>应用</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            {NAV.slice(3, 10).map((n) => (
              <button key={n.id} onClick={() => pick(n.id)} aria-current={active === n.id} className="btn-pressable row-hoverable" style={{
                width: '100%', textAlign: 'left',
                display: 'flex', alignItems: 'center', gap: 10,
                height: 30, paddingInline: 10, borderRadius: 6, border: 'none',
                background: active === n.id ? 'var(--bg-2)' : 'transparent',
                color: active === n.id ? 'var(--fg-0)' : 'var(--fg-1)',
                cursor: 'pointer',
              }}>
                <Lu name={n.icon} size={13} color={active === n.id ? 'var(--fg-0)' : 'var(--fg-2)'} />
                <span className="cjk t-body" style={{ fontWeight: active === n.id ? 600 : 500 }}>{n.label}</span>
              </button>
            ))}
          </div>
          <div style={{ height: 1, background: 'var(--border)', margin: '10px 4px' }} />
          <Unavailable
            block
            reason="本轮没有登录：身份是 X-Handle 请求头，没有会话可退。要换身份请改 VITE_HANDLE 再重新构建。"
          >
            <span className="btn-pressable" style={{ width: '100%', textAlign: 'left', display: 'flex', alignItems: 'center', gap: 10, height: 30, paddingInline: 10, borderRadius: 6, border: 'none', background: 'transparent', color: 'var(--status-error)' }}>
              <Lu name="log-out" size={13} color="var(--status-error)" />
              <span className="cjk t-body" style={{ fontWeight: 500 }}>退出登录</span>
            </span>
          </Unavailable>
        </div>
        <div style={{ padding: 10, borderTop: '1px solid var(--border)' }}>
          <div className="num" style={{ fontSize: 10, color: 'var(--fg-3)' }}>{API_BASE_URL} · X-Handle {API_HANDLE}</div>
        </div>
      </aside>
      <main className="thp-col-main" style={{ overflowY: 'auto', background: 'var(--bg-0)', position: 'relative' }}>
        <button title="关闭" onClick={onClose} className="btn-pressable" style={{ position: 'absolute', top: 16, right: 20, width: 32, height: 32, borderRadius: 8, border: '1px solid var(--border)', background: 'var(--bg-1)', color: 'var(--fg-1)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', zIndex: 2 }}>
          <Lu name="x" size={14} />
          <span style={{ position: 'absolute', top: 36, fontSize: 9, color: 'var(--fg-3)', fontFamily: 'var(--font-mono)', fontWeight: 600, letterSpacing: '0.05em' }}>ESC</span>
        </button>
        <div style={{ maxWidth: 720, padding: '32px 36px 60px' }}>
          {Pane}
        </div>
      </main>
    </div>
  );
}

export { Settings };
