
// Generated by Claude Design (Opus 4.7) v0.7 — shared shell + helpers.
// v0.7: Row hoverable + stagger, Tabs sliding indicator, Avatar online-pulse.

import * as React from 'react';
import * as UI from '@/components/design/ui';
import { Lu } from '@/components/design/lucide';
import type { ChatMsg, Profile, Status, Visibility } from '@/lib/api/types';

const { useState: useStateS, useRef: useRefS, useLayoutEffect: useLayoutEffectS } = React;
const { Avatar: AvatarS } = UI;

/** One entry in the `Tabs` strip. Owned here, next to the component that renders it. */
type TabItem = {
  id: string;
  label: React.ReactNode;
  count?: number;
  dot?: boolean;
};

/**
 * A style object carrying the `--i` stagger index.
 *
 * `anim-row-in` reads `--i` to offset each row's entrance delay, but
 * `React.CSSProperties` has no index signature for custom properties, so every
 * site that set it had to cast the whole object `as any` — which threw away
 * the checking on the other twenty properties in the same literal. Naming the
 * one custom property keeps the rest of the object checked.
 */
export type StaggerStyle = React.CSSProperties & { '--i'?: number | string };

// ---------- prop types ----------
// Same story as ui.tsx: the parameters were untyped, so TypeScript inferred the
// props from the destructuring pattern and reported every binding that lacks a
// `= default` as required. `trailing`, `dense` and `index` have always been
// optional at runtime.

type ServerRailProps = {
  active?: string;
  onPick?: (id: string) => void;
};

type RailIconBtnProps = {
  children?: React.ReactNode;
  title?: string;
  onClick?: React.MouseEventHandler<HTMLButtonElement>;
};

type RowProps = {
  children?: React.ReactNode;
  active?: boolean;
  onClick?: React.MouseEventHandler<HTMLDivElement>;
  leading?: React.ReactNode;
  trailing?: React.ReactNode;
  dense?: boolean;
  style?: React.CSSProperties;
  padded?: boolean;
  /** Stagger index for the entrance animation; omit for no animation. */
  index?: number;
  animateIn?: boolean;
  hoverable?: boolean;
  /**
   * Why this row cannot be opened. Renders it inert and dimmed with the reason
   * on the tooltip, so a list entry that leads nowhere says so on the row
   * instead of swallowing the click.
   */
  disabledReason?: string;
};

type SectionLabelProps = {
  children?: React.ReactNode;
  right?: React.ReactNode;
  style?: React.CSSProperties;
};

type TabsProps = {
  tabs: TabItem[];
  active?: string;
  onChange?: (id: string) => void;
  dense?: boolean;
  style?: React.CSSProperties;
};

type IdentityCardProps = {
  /**
   * The signed-in identity, from GET /v1/me.
   *
   * This used to default to "东方霖之助 / @rinnosuke / UID 100029481" with a
   * hardcoded online dot, on every page of a client whose actual identity is
   * the `X-Handle` header — `local` by default. The bottom-left card therefore
   * named a person who does not exist, and clicking it opened `local`'s
   * profile. `null` renders an explicit placeholder instead.
   */
  me?: Profile | null;
  onSettings?: React.MouseEventHandler<HTMLButtonElement>;
  onProfile?: React.MouseEventHandler<HTMLSpanElement>;
};

type ServerCardFlatProps = {
  title?: string;
  host?: string;
  region?: string;
  ping?: number;
  diff?: string;
  mode?: string;
  taken?: number;
  total?: number;
  vis?: Visibility;
  /** Why joining is not possible, when it is not. Renders the button disabled. */
  joinBlockedReason?: string;
  compact?: boolean;
  onJoin?: React.MouseEventHandler<HTMLButtonElement>;
};

type StatusDotProps = {
  status?: Status;
  size?: number;
};

type ChatMessageProps = {
  msg: ChatMsg;
  samegroup?: boolean;
};

// ---------- ServerRail (Col 1 — 72px) ----------
function ServerRail({ active = 'th08', onPick }: ServerRailProps) {
  const games = [
    { id: 'th06', label: 'TH06' },
    { id: 'th07', label: 'TH07' },
    { id: 'th08', label: 'TH08' },
    { id: 'th09', label: 'TH09' },
  ];
  const [hover, setHover] = useStateS<string | null>(null);

  const Tile = ({ id, children, title }: { id: string; children: React.ReactNode; title: string }) => {
    const isActive = active === id;
    const isHovered = hover === id;
    return (
      <div className="relative" style={{ position: 'relative', display: 'flex', justifyContent: 'center' }}>
        <span style={{
          position: 'absolute', left: -10, top: '50%', transform: 'translateY(-50%)',
          width: 3, height: isActive ? 22 : isHovered ? 10 : 0,
          background: 'var(--accent)', borderRadius: 999,
          transition: 'height .18s ease',
        }} />
        <button
          title={title}
          onClick={() => onPick && onPick(id)}
          onMouseEnter={() => setHover(id)}
          onMouseLeave={() => setHover(null)}
          className="btn-pressable"
          style={{
            width: 44, height: 44,
            borderRadius: isActive || isHovered ? 12 : 22,
            background: isActive ? 'var(--bg-3)' : 'var(--bg-2)',
            color: isActive ? 'var(--fg-0)' : 'var(--fg-1)',
            fontWeight: 600, fontSize: 11,
            fontFamily: 'var(--font-mono)', letterSpacing: '0.02em',
            border: `1px solid ${isActive ? 'var(--border-strong)' : 'var(--border)'}`,
            padding: 0, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            transition: 'border-radius var(--duration-mid) var(--ease-spring), background var(--duration-fast), color var(--duration-fast)',
          }}
        >{children}</button>
      </div>
    );
  };

  return (
    <div style={{
      width: 72, background: 'var(--bg-0)',
      borderRight: '1px solid var(--border)',
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      padding: '14px 0', gap: 10, flexShrink: 0,
    }}>
      {/* Wireframe T brand glyph */}
      <div style={{ position: 'relative', display: 'flex', justifyContent: 'center' }}>
        <span style={{
          position: 'absolute', left: -10, top: '50%', transform: 'translateY(-50%)',
          width: 3, height: active === 'home' ? 22 : 0,
          background: 'var(--accent)', borderRadius: 999,
        }} />
        <button title="TH-Home" onClick={() => onPick && onPick('home')} className="btn-pressable" style={{
          width: 44, height: 44, borderRadius: active === 'home' ? 12 : 22,
          background: 'var(--bg-1)', color: 'var(--accent)',
          border: '1px solid var(--border-strong)',
          padding: 0, cursor: 'pointer',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          transition: 'border-radius var(--duration-mid) var(--ease-spring)',
        }}>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
            <path d="M5 6h14" />
            <path d="M12 6v13" />
          </svg>
        </button>
      </div>
      <div style={{ width: 26, height: 1, background: 'var(--border)', margin: '4px 0' }} />
      {games.map(g => (
        <Tile key={g.id} id={g.id} title={g.label}>{g.label.replace('TH','')}</Tile>
      ))}
      <button
        title="Add server"
        onClick={() => onPick && onPick('add-server')}
        style={{
          width: 44, height: 44, borderRadius: 22,
          background: 'transparent', color: 'var(--fg-2)',
          border: '1px dashed var(--border-strong)', cursor: 'pointer',
          padding: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
          transition: 'border-radius .18s ease, color .18s',
        }}
        onMouseEnter={(e) => { e.currentTarget.style.borderRadius = '12px'; e.currentTarget.style.color = 'var(--fg-0)'; }}
        onMouseLeave={(e) => { e.currentTarget.style.borderRadius = '22px'; e.currentTarget.style.color = 'var(--fg-2)'; }}
      ><Lu name="plus" size={16} /></button>
      <div style={{ flex: 1 }} />
      <RailIconBtn title="Discover" onClick={() => onPick && onPick('discover')}><Lu name="compass" size={18} /></RailIconBtn>
      <RailIconBtn title="Settings" onClick={() => onPick && onPick('settings')}><Lu name="settings" size={18} /></RailIconBtn>
    </div>
  );
}

function RailIconBtn({ children, title, onClick }: RailIconBtnProps) {
  return (
    <button title={title} onClick={onClick} className="btn-pressable" style={{
      width: 44, height: 44, borderRadius: 22,
      background: 'transparent', color: 'var(--fg-2)',
      border: '1px solid var(--border)', cursor: 'pointer',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      transition: 'border-radius var(--duration-mid) var(--ease-spring), color var(--duration-fast), background var(--duration-fast)',
    }}
      onMouseEnter={(e) => { e.currentTarget.style.borderRadius = '12px'; e.currentTarget.style.color = 'var(--fg-0)'; e.currentTarget.style.background = 'var(--hover)'; }}
      onMouseLeave={(e) => { e.currentTarget.style.borderRadius = '22px'; e.currentTarget.style.color = 'var(--fg-2)'; e.currentTarget.style.background = 'transparent'; }}
    >{children}</button>
  );
}

// ---------- Row (flat list item, hoverable + stagger) ----------
function Row({ children, active, onClick, leading, trailing, dense, style = {}, padded = true, index, animateIn = false, hoverable = true, disabledReason }: RowProps) {
  // A row with a reason is not a row you can click. Dropping `onClick` here
  // rather than at each call site is what makes "disabled" mean disabled: there
  // is no way to pass a handler and a reason and end up with a live row.
  const clickable = disabledReason ? undefined : onClick;
  const cls = [
    hoverable && clickable ? 'row-hoverable' : '',
    animateIn ? 'anim-row-in' : '',
  ].filter(Boolean).join(' ');
  const cssVars = index != null ? { '--i': index } : {};
  return (
    <div
      onClick={clickable}
      title={disabledReason}
      aria-disabled={disabledReason ? true : undefined}
      className={cls}
      style={{
        display: 'flex', alignItems: 'center', gap: 10,
        padding: dense ? '4px 8px' : padded ? '6px 10px' : 0,
        borderRadius: 6,
        background: active ? 'var(--active)' : 'transparent',
        color: active ? 'var(--fg-0)' : 'var(--fg-1)',
        cursor: disabledReason ? 'not-allowed' : clickable ? 'pointer' : 'default',
        opacity: disabledReason ? 0.5 : undefined,
        transition: 'background var(--duration-fast) var(--ease-out-quart), color var(--duration-fast) var(--ease-out-quart)',
        ...cssVars,
        ...style,
      }}
    >
      {leading}
      <div style={{ flex: 1, minWidth: 0 }}>{children}</div>
      {disabledReason ? <Lu name="ban" size={11} color="var(--fg-3)" /> : trailing}
    </div>
  );
}

// ---------- SectionLabel ----------
function SectionLabel({ children, right, style = {} }: SectionLabelProps) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 4px', ...style }}>
      <span className="uppercase-tag" style={{ color: 'var(--fg-2)' }}>{children}</span>
      {right}
    </div>
  );
}

function Divider({ label, style = {} }: { label?: string; style?: React.CSSProperties }) {
  if (!label) return <div style={{ height: 1, background: 'var(--border)', ...style }} />;
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 12, ...style }}>
      <span style={{ height: 1, background: 'var(--border)', flex: 1 }} />
      <span className="uppercase-tag" style={{ color: 'var(--fg-2)' }}>{label}</span>
      <span style={{ height: 1, background: 'var(--border)', flex: 1 }} />
    </div>
  );
}

// ---------- Tabs (sliding underline indicator) ----------
function Tabs({ tabs, active, onChange, dense, style = {} }: TabsProps) {
  const containerRef = useRefS<HTMLDivElement>(null);
  const btnRefs = useRefS<Record<string, HTMLButtonElement | null>>({});
  const [ind, setInd] = useStateS({ left: 0, width: 0, ready: false });
  useLayoutEffectS(() => {
    // `active` is optional: with no selection there is no indicator to place,
    // and indexing an object with `undefined` is not a lookup, it is a bug.
    const el = active != null ? btnRefs.current[active] : null;
    const wrap = containerRef.current;
    if (!el || !wrap) return;
    const wr = wrap.getBoundingClientRect();
    const r = el.getBoundingClientRect();
    setInd({ left: r.left - wr.left, width: r.width, ready: true });
  }, [active, tabs.length]);
  return (
    <div ref={containerRef} style={{
      position: 'relative',
      display: 'flex', gap: dense ? 4 : 14,
      borderBottom: '1px solid var(--border)',
      ...style,
    }}>
      {tabs.map(t => {
        const on = t.id === active;
        return (
          <button
            key={t.id}
            ref={(el) => { btnRefs.current[t.id] = el; }}
            onClick={() => onChange && onChange(t.id)}
            style={{
              position: 'relative', padding: dense ? '6px 10px' : '10px 6px',
              border: 'none', background: 'transparent',
              fontSize: dense ? 12 : 12.5, fontWeight: 600,
              fontFamily: 'var(--font-sans)',
              color: on ? 'var(--fg-0)' : 'var(--fg-2)',
              cursor: 'pointer',
              display: 'inline-flex', alignItems: 'center', gap: 6,
              transition: 'color var(--duration-fast) var(--ease-out-quart)',
            }}
          >
            {t.label}
            {t.count != null ? (
              <span className="mono num" style={{
                fontSize: 10, color: 'var(--fg-2)',
                padding: '1px 5px',
                background: 'var(--bg-3)', borderRadius: 4,
              }}>{t.count}</span>
            ) : null}
            {t.dot ? <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--status-error)' }} /> : null}
          </button>
        );
      })}
      <span className="tab-indicator" style={{
        position: 'absolute', bottom: -1,
        left: ind.left, width: ind.width, height: 2,
        background: 'var(--accent)', borderRadius: 2,
        opacity: ind.ready ? 1 : 0,
        pointerEvents: 'none',
      }} />
    </div>
  );
}

// ---------- IdentityCard ----------
function IdentityCard({ me, onSettings, onProfile }: IdentityCardProps) {
  // No invented default. This card used to render "东方霖之助 / @rinnosuke /
  // UID 100029481" with a hardcoded green dot at the bottom of every page,
  // while the identity the server actually knows is the `X-Handle` header —
  // `local` by default. It named a person who does not exist, and clicking it
  // opened that header's profile, not the one on the card.
  const loaded = !!me;
  return (
    <div style={{
      padding: 10, margin: 10, marginTop: 4,
      borderRadius: 'var(--r-md)',
      background: 'var(--bg-2)',
      display: 'flex', alignItems: 'center', gap: 10,
      border: '1px solid var(--border)',
    }}>
      <span
        onClick={loaded ? onProfile : undefined}
        title={loaded && onProfile ? '查看我的资料' : '正在读取 /v1/me'}
        style={{ cursor: loaded && onProfile ? 'pointer' : 'default' }}
      >
        {/* No status dot: /v1/me carries a `status`, but a permanent green dot
            was a claim about presence the shell cannot make, and IdentityCard is
            rendered on pages that have not read /v1/me at all. */}
        <AvatarS size={32} name={loaded ? me.name : ''} />
      </span>
      <div
        onClick={loaded ? onProfile : undefined}
        style={{ flex: 1, minWidth: 0, cursor: loaded && onProfile ? 'pointer' : 'default' }}
      >
        <div className="cjk" style={{
          fontSize: 12.5, fontWeight: 600, color: 'var(--fg-0)',
          whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
        }}>{loaded ? me.name : '未载入'}</div>
        <div className="mono" style={{ fontSize: 10.5, color: 'var(--fg-2)' }}>
          {loaded ? (me.uid ? `@${me.handle} · UID ${me.uid}` : `@${me.handle}`) : '正在读取身份…'}
        </div>
      </div>
      <button title="设置" onClick={onSettings} className="btn-pressable" style={{
        width: 26, height: 26, borderRadius: 6, border: 'none',
        background: 'transparent', color: 'var(--fg-2)', cursor: 'pointer',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
      }}><Lu name="settings" size={14} /></button>
    </div>
  );
}

// ---------- ServerCardFlat (room-share embed) ----------
function ServerCardFlat({ title, host, region, ping, diff, mode, taken = 0, total = 0, vis = 'public', compact, onJoin, joinBlockedReason }: ServerCardFlatProps) {
  // A private room is the one case where joining is impossible for a reason the
  // share itself carries. Anything else that blocks a join is passed in as
  // `joinBlockedReason`, so a caller cannot leave this button looking live.
  const visMap: Record<Visibility, { label: string; variant: 'primary' | 'secondary'; icon: React.ReactNode }> = {
    public:  { label: '立即加入', variant: 'primary',   icon: null },
    ask:     { label: '请求加入', variant: 'secondary', icon: null },
    private: { label: '私密',     variant: 'secondary', icon: <Lu name="lock" size={12} /> },
  };
  const v = visMap[vis];
  const blocked = vis === 'private' || !!joinBlockedReason;
  const blockedReason =
    vis === 'private' ? '这是私密房间，只有房主邀请的人能进。' : joinBlockedReason;

  return (
    <div style={{
      // Fluid, not a fixed 320/380. This card is embedded in a 320px chat column
      // with 14px of padding and in a 308px group aside, so a hard width pushed
      // the join button past the right edge of the window in both places.
      width: compact ? '100%' : 380,
      maxWidth: '100%',
      minWidth: 0,
      background: 'var(--bg-1)',
      border: '1px solid var(--border-strong)',
      borderRadius: 'var(--r-md)',
      padding: 12,
      display: 'flex', flexDirection: 'column', gap: 10,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        {/* The tag used to read a hardcoded "TH08" on every shared card, shares
            of a TH09 room included: `RoomShareEmbed` carries no gameId
            (src/lib/api/types.ts), so nothing was behind the label. What it does
            carry is visibility, which is what a reader needs here. */}
        <span className="uppercase-tag" style={{ color: 'var(--fg-2)', padding: '2px 6px', border: '1px solid var(--border-strong)', borderRadius: 4 }}>
          {vis === 'private' ? '私密' : vis === 'ask' ? '需申请' : '公开'}
        </span>
        <span className="cjk" style={{
          flex: 1, minWidth: 0, fontSize: 13, fontWeight: 600, color: 'var(--fg-0)',
          whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
        }}>{title}</span>
      </div>
      <div className="cjk" style={{ fontSize: 11.5, color: 'var(--fg-2)', display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        <span><span style={{ color: 'var(--fg-1)' }}>房主</span> {host}</span>
        <span style={{ color: 'var(--fg-3)' }}>·</span>
        <span className="mono" style={{ color: 'var(--fg-1)' }}>{ping}ms</span>
        <span style={{ color: 'var(--fg-3)' }}>·</span>
        <span>{region}</span>
        <span style={{ color: 'var(--fg-3)' }}>·</span>
        <span>{diff}</span>
        {mode ? <><span style={{ color: 'var(--fg-3)' }}>·</span><span>{mode}</span></> : null}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center' }}>
          {/* Occupancy pips, not invented names. The glyphs this used to render
              (幽/妖/咲/魔) stood in for the people actually sitting in the room,
              and a share card carries no roster to name them from. */}
          {Array.from({ length: Math.max(0, Math.min(taken, 4)) }).map((_, i) => (
            <span key={i} style={{
              width: 22, height: 22, borderRadius: '50%',
              background: 'var(--bg-2)',
              border: '2px solid var(--bg-1)',
              marginLeft: i === 0 ? 0 : -6,
            }} />
          ))}
          {Array.from({ length: Math.max(0, Math.min(total - taken, 4)) }).map((_, i) => (
            <span key={`e${i}`} style={{
              width: 22, height: 22, borderRadius: '50%',
              background: 'transparent',
              border: '1px dashed var(--border-strong)',
              marginLeft: -6,
            }} />
          ))}
          <span className="mono" style={{ marginLeft: 6, fontSize: 11, color: 'var(--fg-2)', alignSelf: 'center' }}>{taken}/{total}</span>
        </div>
        <span title={blockedReason} style={{ display: 'inline-flex' }}>
          <button
            disabled={blocked}
            onClick={onJoin}
            className="btn-pressable"
            style={{
              height: 28, paddingInline: 12,
              borderRadius: 'var(--r-md)',
              background: v.variant === 'primary' ? 'var(--accent)' : 'var(--bg-2)',
              color: v.variant === 'primary' ? 'var(--bg-0)' : 'var(--fg-1)',
              border: v.variant === 'primary' ? '1px solid var(--accent)' : '1px solid var(--border-strong)',
              fontSize: 12, fontWeight: 600,
              cursor: blocked ? 'not-allowed' : 'pointer',
              opacity: blocked ? 0.6 : 1,
              display: 'inline-flex', alignItems: 'center', gap: 5,
              fontFamily: 'var(--font-sans)',
            }}
          >
            {v.icon}<span className="cjk">{v.label}</span>
          </button>
        </span>
      </div>
    </div>
  );
}

// ---------- StatusDot ----------
function StatusDot({ status, size = 8 }: StatusDotProps) {
  const c = status === 'online' ? 'var(--status-online)'
    : status === 'away' || status === 'idle' ? 'var(--status-warn)'
    : status === 'dnd' ? 'var(--status-error)'
    : 'var(--fg-3)';
  return <span style={{ width: size, height: size, borderRadius: '50%', background: c, display: 'inline-block' }} />;
}

// ---------- ChannelRow ----------
function ChannelRow({ name, active, unread, mention, muted, onClick }: { name?: string; active?: boolean; unread?: number; mention?: number; muted?: boolean; onClick?: React.MouseEventHandler<HTMLDivElement> }) {
  return (
    <Row
      onClick={onClick}
      active={active}
      leading={<span style={{ color: muted ? 'var(--fg-3)' : 'var(--fg-2)', fontFamily: 'var(--font-sans)', fontWeight: 500, fontSize: 14, lineHeight: 1, width: 14, textAlign: 'center' }}>#</span>}
      trailing={
        <span style={{ display: 'inline-flex', gap: 6, alignItems: 'center' }}>
          {mention ? (
            <span className="mono" style={{ minWidth: 16, height: 16, padding: '0 4px', borderRadius: 8, background: 'var(--status-error)', color: '#fff', fontSize: 10, fontWeight: 600, display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>{mention}</span>
          ) : null}
          {unread && !mention ? <span style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--fg-0)' }} /> : null}
          {muted ? <Lu name="bell-off" size={12} color="var(--fg-3)" /> : null}
        </span>
      }
    >
      <span className="cjk" style={{
        fontSize: 12.5, fontWeight: unread ? 600 : 500,
        color: active ? 'var(--fg-0)' : muted ? 'var(--fg-3)' : unread ? 'var(--fg-0)' : 'var(--fg-1)',
      }}>{name}</span>
    </Row>
  );
}

// ---------- ChatMessage ----------
function ChatMessage({ msg, samegroup }: ChatMessageProps) {
  if (samegroup) {
    return (
      <div style={{ display: 'flex', gap: 10, paddingLeft: 38 }}>
        <div className="cjk" style={{ fontSize: 13, color: 'var(--fg-1)', lineHeight: 1.55, flex: 1 }}>
          {renderMsgBody(msg)}
        </div>
      </div>
    );
  }
  return (
    <div style={{ display: 'flex', gap: 10 }}>
      <AvatarS size={28} name={msg.who} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
          <span className="cjk" style={{ fontSize: 12.5, fontWeight: 600, color: 'var(--fg-0)' }}>{msg.who}</span>
          <span className="mono" style={{ fontSize: 10.5, color: 'var(--fg-3)' }}>{msg.t}</span>
        </div>
        <div className="cjk" style={{ fontSize: 13, color: 'var(--fg-1)', lineHeight: 1.55, marginTop: 1, wordBreak: 'break-word' }}>
          {renderMsgBody(msg)}
        </div>
        {msg.reactions ? (
          <div style={{ display: 'flex', gap: 4, marginTop: 6, flexWrap: 'wrap' }}>
            {msg.reactions.map((r, i) => (
              <span key={i} style={{
                display: 'inline-flex', alignItems: 'center', gap: 5,
                height: 22, padding: '0 8px', borderRadius: 999,
                background: r.mine ? 'var(--accent-soft)' : 'var(--bg-2)',
                // No `cursor: pointer` and no click target: a reaction chip is a
                // readout until the server grows a POST for it, and a chip that
                // invites a click it cannot answer is a lie in 22 pixels.
                color: 'var(--fg-1)',
                fontSize: 11, fontWeight: 600,
                userSelect: 'none',
              }}>
                <Lu name={r.icon || 'thumbs-up'} size={12} />
                <span className="mono">{r.count}</span>
              </span>
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
}

function renderMsgBody(m: ChatMsg) {
  const body = m.msg ?? '';
  if (m.mention) {
    // Split on the first occurrence only, so a message that repeats the mention
    // keeps its tail intact instead of being cut in half.
    const at = body.indexOf(`@${m.mention}`);
    const pre = at < 0 ? body : body.slice(0, at);
    const post = at < 0 ? '' : body.slice(at + m.mention.length + 1);
    return (
      <>
        {pre}
        <span style={{ background: 'var(--accent-soft)', color: 'var(--fg-0)', padding: '1px 6px', borderRadius: 4, fontWeight: 600, border: '1px solid var(--border-strong)' }}>@{m.mention}</span>
        {post}
      </>
    );
  }
  return body;
}

export {
  ServerRail, Row, SectionLabel, Divider, Tabs, IdentityCard,
  ServerCardFlat, StatusDot, ChannelRow, ChatMessage,
};
